/*This file is automatically generated by the tinyui tool and should not be modified.*/
#ifndef INCLUDE_MAIN_UI_H
#define INCLUDE_MAIN_UI_H
#include <memory>
#include <vector>

#include "goldie_display.h" 
// 控件头文件
#include "wifi_view.h"
#include "battery_view.h"
#include "label_view.h"
#include "nearlink_view.h"
#include "frame_view.h"
#include "scroll_view.h"
#include "datetime_view.h"
#include "window.h"

// 图片头文件
#include "rgb16_wifi_new_32_25.h"
#include "rgb16_nearlink2_24_27.h"
#include "rgb16_nearlink21_24_27.h"
#include "rgb16_norm_48_16.h"
// 掩码头文件
#include "round_rect_72_26_r3_boundary.h"
#include "round_rect_96_93_r2_boundary.h"
#include "round_rect_160_96_r2_boundary.h"
// 全局控件变量定义
static std::shared_ptr<WifiView> WifiView_main;
static std::shared_ptr<BatteryView> BatteryView_main;
static std::shared_ptr<LabelView> LabelView_nc;
static std::shared_ptr<NearLinkView> NearLinkView_main;
static std::shared_ptr<FrameView> FrameView_status;
static std::shared_ptr<ScrollView> ScrollView_main;
static std::shared_ptr<DateTimeView> DateTimeView_main;
static std::shared_ptr<FrameView> FrameView_main;
static std::shared_ptr<Window> Window_main;

static void main_ui_init()
{
    WifiView_main = std::make_shared<WifiView>(32, 25);
    WifiView_main->setColor(0x3F03);
    WifiView_main->setTextColor(0);
    WifiView_main->setVisible(true);
    WifiView_main->setImageBuffer((uint16_t*)&rgb16_wifi_new_32_25);

    BatteryView_main = std::make_shared<BatteryView>(48, 16);
    BatteryView_main->setColor(0x3F03);
    BatteryView_main->setTextColor(0);
    BatteryView_main->setVisible(true);
    BatteryView_main->setImageBuffer((uint16_t*)&rgb16_norm_48_16);

    LabelView_nc = std::make_shared<LabelView>(72, 26);
    LabelView_nc->setColor(0x8210);
    LabelView_nc->setTextColor(0);
    LabelView_nc->setBoundaryBuffer(round_rect_72_26_r3_boundary);
    LabelView_nc->setVisible(true);

    NearLinkView_main = std::make_shared<NearLinkView>(24, 27);
    NearLinkView_main->setColor(0x3F03);
    NearLinkView_main->setTextColor(0);
    NearLinkView_main->setVisible(true);
    NearLinkView_main->setImageBuffer((uint16_t*)&rgb16_nearlink21_24_27);

    FrameView_status = std::make_shared<FrameView>(96, 93);
    FrameView_status->setColor(0x5DE7);
    FrameView_status->setTextColor(0);
    FrameView_status->setBoundaryBuffer(round_rect_96_93_r2_boundary);
    FrameView_status->setVisible(true);

    ScrollView_main = std::make_shared<ScrollView>(320, 117);
    ScrollView_main->setColor(0xFFFF);
    ScrollView_main->setTextColor(0);
    ScrollView_main->setVisible(true);

    DateTimeView_main = std::make_shared<DateTimeView>(160, 96);
    DateTimeView_main->setColor(0x0000);
    DateTimeView_main->setTextColor(1);
    DateTimeView_main->setBoundaryBuffer(round_rect_160_96_r2_boundary);
    DateTimeView_main->setVisible(true);

    FrameView_main = std::make_shared<FrameView>(320, 240);
    FrameView_main->setColor(0xFFFF);
    FrameView_main->setTextColor(0);
    FrameView_main->setVisible(true);

    Window_main = std::make_shared<Window>(APP_WINDOW_START_X, APP_WINDOW_START_Y,320, 240);
    Window_main->setColor(0x8631);
    Window_main->setTextColor(0);
    Window_main->setVisible(true);

    // 建立控件父子关系
    FrameView_status->addView(NearLinkView_main, 64, 17);
    FrameView_status->addView(LabelView_nc, 16, 53);
    FrameView_status->addView(BatteryView_main, 32, 59);
    FrameView_status->addView(WifiView_main, 16, 18);
    FrameView_main->addView(DateTimeView_main, 136, 19);
    FrameView_main->addView(ScrollView_main, 0, 123);
    FrameView_main->addView(FrameView_status, 24, 20);
    Window_main->addView(FrameView_main, 0, 0);

    // 刷新窗口
    Window_main->flush(0, 0, APP_WINDOW_WIDTH, APP_WINDOW_HEIGHT);
}

static void window_exit(void)
{
    Window_main->setVisible(false);
    Window_main->removeAllViews();

    FrameView_status->removeAllChilds();
    FrameView_main->removeAllChilds();
    ScrollView_main->removeAllChilds();

    BatteryView_main.reset();
    NearLinkView_main.reset();
    LabelView_nc.reset();
    WifiView_main.reset();

    DateTimeView_main.reset();
    FrameView_status.reset();
    FrameView_main.reset();
    ScrollView_main.reset();    	
    Window_main.reset();
}

static void window_suspend(void)
{
    Window_main->setVisible(false);
}

static void window_resume(void)
{
    Window_main->setVisible(true);
    Window_main->flush(0, 0, APP_WINDOW_WIDTH, APP_WINDOW_HEIGHT);
}

#endif //INCLUDE_MAIN_UI_H 

