/*This file is automatically generated by the tinyui tool 
and contains the main_ui. h file, which calls the initialization 
function main_ui_init() to create the UI interface. You need to 
add code related to business logic here..*/
#include "main_ui.h"
#include "default_app_icon.h" 
#include "goldie_thread.h"
#include <cstdlib>
#include <ctime>
extern "C" { 
#include "goldie_osal.h" 
#include "service_manager.h" 
#include "driver_manager.h" 
#ifdef DRV_CORE
#include "driver_core.h"
#endif
#include "app_manager.h" 
#include "event_service.h"
} 
#include "button_view.h"

#ifdef SUPPORT_BATTERY
#ifdef DRV_CORE
static int battery_fd = -1;
#else
static BatDrv* battery_drv;
#endif
#endif

goldie_mutex ui_mutex;
static int app_status = 0;


// App icon layout constants (same as luncher)
#define LAUNCHER_ICON_SPACING 24
#define LAUNCHER_LABEL_HEIGHT 20
#define LAUNCHER_START_X 16


static std::vector<std::shared_ptr<ButtonView>> app_buttons;
static std::vector<std::shared_ptr<LabelView>> app_labels;

static int app_count = 0;
static App_t** app_list = NULL;

static int  g_month =1;
static int  g_day =1;
static int  g_weekday = 0;
static int  g_hour = 1;
static int  g_min = 1;


// Event service for receiving system broadcasts
static EventService *evt_service = NULL;
#ifdef SUPPORT_SLE
static SleSdpService *sle_service = NULL;
#endif
static WifiService *wifi_service =NULL;

// Timer thread for updating time display
static Goldie_Thread* time_update_thread = nullptr;
static volatile int time_thread_running = 0;

//#define RANDOM_TEST_BATTERY_SVC
// #define CYCLE_BATTERY_TEST//模拟器电量测试
#ifdef RANDOM_TEST_BATTERY_SVC
// Test counter for random battery level
static int test_battery_counter = 0;
#endif

const uint16_t __attribute__((section(".text"))) gImage_round_icon_boundary[168] = {
    0x01a7, 0x001d, 0x0029, 
    0x0155, 0x0022, 0x0051, 
    0x0124, 0x0025, 0x007f, 
    0x0104, 0x0027, 0x007f, 
    0x00e3, 0x0029, 0x00e2, 
    0x00c2, 0x002b, 0x01f0, 
    0x00b3, 0x002c, 0x00e2, 
    0x00a3, 0x002d, 0x00e2, 
    0x0093, 0x002e, 0x00e2, 
    0x0083, 0x002f, 0x00e2, 
    0x0072, 0x0030, 0x01f2, 
    0x0062, 0x0031, 0x01fe, 
    0x0052, 0x0032, 0x01fe, 
    0x0053, 0x0032, 0x00e0, 
    0x0042, 0x0033, 0x01fe, 
    0x0043, 0x0033, 0x00e1, 
    0x0032, 0x0034, 0x01fe, 
    0x0033, 0x0034, 0x00e2, 
    0x0022, 0x0035, 0x01fe, 
    0x0022, 0x0035, 0x01fe, 
    0x0022, 0x0035, 0x01e4, 
    0x0011, 0x0036, 0x05d8, 
    0x0011, 0x0036, 0x0410, 
    0x0011, 0x0036, 0x02a0, 
    0x0011, 0x0036, 0x0160, 
    0x0011, 0x0036, 0x00b8, 
    0x0001, 0x0037, 0x0020, 
    0x0001, 0x0037, 0x0000, 
    0x0001, 0x0037, 0x0000, 
    0x0001, 0x0037, 0x0020, 
    0x0011, 0x0036, 0x00b8, 
    0x0011, 0x0036, 0x0160, 
    0x0011, 0x0036, 0x02a0, 
    0x0011, 0x0036, 0x0410, 
    0x0011, 0x0036, 0x05d8, 
    0x0022, 0x0035, 0x01e4, 
    0x0022, 0x0035, 0x01fe, 
    0x0022, 0x0035, 0x01fe, 
    0x0033, 0x0034, 0x00e2, 
    0x0032, 0x0034, 0x01fe, 
    0x0043, 0x0033, 0x00e1, 
    0x0042, 0x0033, 0x01fe, 
    0x0053, 0x0032, 0x00e0, 
    0x0052, 0x0032, 0x01fe, 
    0x0062, 0x0031, 0x01fe, 
    0x0072, 0x0030, 0x01f2, 
    0x0083, 0x002f, 0x00e2, 
    0x0093, 0x002e, 0x00e2, 
    0x00a3, 0x002d, 0x00e2, 
    0x00b3, 0x002c, 0x00e2, 
    0x00c2, 0x002b, 0x01f0, 
    0x00e3, 0x0029, 0x00e2, 
    0x0104, 0x0027, 0x007f, 
    0x0124, 0x0025, 0x007f, 
    0x0155, 0x0022, 0x0051, 
    0x01a7, 0x001d, 0x0029, 
};

static void update_datetime_view()
{
	DateTimeView_main->setDate(g_month,g_day,g_weekday);
	DateTimeView_main->setTime(g_hour,g_min);
	DateTimeView_main->updateTime();

}
static void update_battery_view(){
#ifdef SUPPORT_BATTERY
#ifdef DRV_CORE
	int bat_soc;
         int charging_status;
	goldie_read(battery_fd, (uint8_t*)&bat_soc, sizeof(bat_soc));
	goldie_ioctl(battery_fd,BAT_IOCTL_GET_CHGSTATUS,&charging_status);
#else
	int bat_soc = battery_drv->read_power();
	int charging_status = battery_drv->is_charging();
#endif
	BatteryView_main->setBatteryLevel(bat_soc);
	if(charging_status){
		BatteryView_main->setCharging(true);
	}else{
		BatteryView_main->setCharging(false);
	}
#else
	BatteryView_main->setBatteryLevel(50);
#endif
}

// Battery power update callback from event service
static void update_bat_msg(BroadcastMessage* msg) {
    goldie_mutex_lock(&ui_mutex);
    if (msg && BatteryView_main) {
       update_battery_view();
    }
    goldie_mutex_unlock(&ui_mutex);	
}

// Timer thread function - updates time every second
static void time_update(BroadcastMessage* msg) {    
    (void)msg;
    goldie_mutex_lock(&ui_mutex);
	if((msg->msg)&&(msg->msg_len == sizeof(struct tm)))
	{	
		struct tm* current_time = (struct tm*)(msg->msg);
		printf("time_update: %04d-%02d-%02d %02d:%02d:%02d (Week%d)\r\n",
			   current_time->tm_year+1900, current_time->tm_mon+1, current_time->tm_mday,
			   current_time->tm_hour, current_time->tm_min, current_time->tm_sec,
			   current_time->tm_wday);
	
		   g_month =current_time->tm_mon+1;
		   g_day =current_time->tm_mday;
		   g_weekday = current_time->tm_wday;
		   g_hour = current_time->tm_hour+8;
		   if(g_hour>=24){
			g_hour = g_hour -24;
		   }
		   g_min = current_time->tm_min;
	}

	if ((app_status ==1) && (DateTimeView_main)) {
		update_datetime_view();
        }

#ifdef CYCLE_BATTERY_TEST
    // 测试：每秒循环电量变化（0→100→0）
    if (evt_service) {
        static int cycle_battery_level = 0;       // 当前电量，初始为0
        static int cycle_direction = 1;           // 变化方向：1表示增加，-1表示减少
        static int cycle_charging = 0;            // 充电状态，0表示未充电
        
        // 每秒变化10%
        cycle_battery_level += (10 * cycle_direction);
        
        // 边界检查与方向反转
        if (cycle_battery_level >= 100) {
            cycle_battery_level = 100;            // 确保不超过100
            cycle_direction = -1;                 // 到达100后开始减少
            cycle_charging = 0;                   // 电量满时停止充电（如果需要）
        } else if (cycle_battery_level <= 0) {
            cycle_battery_level = 0;              // 确保不低于0
            cycle_direction = 1;                  // 到达0后开始增加
            cycle_charging = 1;                   // 电量为0时开始充电（如果需要）
        }
        BatteryView_main->setBatteryLevel(cycle_battery_level);
        // 更新充电状态（可选，根据您的需求）
        if (BatteryView_main) {
            BatteryView_main->setCharging(cycle_charging);
        }
        
        // 调试信息
        printf("[CYCLE_TEST] Battery: %d%%, Charging: %d, Direction: %s\n", 
               cycle_battery_level, cycle_charging, 
               cycle_direction > 0 ? "UP" : "DOWN");
    }
#endif


#ifdef RANDOM_TEST_BATTERY_SVC
        // Test: Broadcast random battery status every second
        if (evt_service) {
            test_battery_counter++;
            // Generate random battery level (0-100) using counter for pseudo-randomness
            // Cycle through different battery levels for testing
            int random_battery = (test_battery_counter * 17 + 23) % 101;  // Pseudo-random 0-100
            
            // Also randomly toggle charging state
            bool random_charging = (test_battery_counter % 3) == 0;  // Charging 1/3 of the time
            
            // Create and send battery power broadcast message
            BroadcastMessage bat_msg = {0};
            bat_msg.id = EVENT_BROADCAST_POWER;
            bat_msg.ext[0] = random_battery;
            bat_msg.msg_len = sizeof(int);
            
            evt_service->send_broadcast(&bat_msg);
            
            // Update charging state directly (since there's no charging broadcast event yet)
            if (BatteryView_main) {
                BatteryView_main->setCharging(random_charging);
                // Refresh battery view area
                if (Window_main && Window_main->isVisible() && FrameView_main && FrameView_status) {
                    int bat_x = FrameView_main->getX() + FrameView_status->getX() + BatteryView_main->getX();
                    int bat_y = FrameView_main->getY() + FrameView_status->getY() + BatteryView_main->getY();
                    int bat_w = BatteryView_main->getWidth();
                    int bat_h = BatteryView_main->getHeight();
                    Window_main->flush(bat_x, bat_y, bat_w, bat_h);
                }
            }
        }
#endif
	if(wifi_service)
	{
		if(wifi_service->svr_sta_isConnected())
		{
			WifiView_main->setSignalLevel(WIFI_SIGNAL_STRONG);
		}else{
            WifiView_main->setSignalLevel(WIFI_SIGNAL_NONE);
        }
	}
    #ifdef SUPPORT_SLE
    if(sle_service)
    {
        if(sle_service->svr_is_enabled())
		{
			NearLinkView_main->setStatus(NEARLINK_ENABLED);
		}else{
            NearLinkView_main->setStatus(NEARLINK_DISABLED);
        }
    }else {
        // 如果支持SLE但服务获取失败，也视为禁用
        NearLinkView_main->setStatus(NEARLINK_DISABLED);
    }
    #else
        // 如果系统不支持SLE，则直接将其状态设置为禁用
        NearLinkView_main->setStatus(NEARLINK_DISABLED);
    #endif
    goldie_mutex_unlock(&ui_mutex);
	    return;
}

static void goldie_touch_event(int pressure, int x, int y)
{
    if (Window_main) {
        Window_main->handleEvent(pressure, x, y);
    }
}

// Show app icons in ScrollView (horizontal scroll)
// Uses ICON_WIDTH/ICON_HEIGHT from goldie_display.h (56x56)
static void show_apps(App_t** app_list, int list_count) {
    // Clear existing app buttons and labels
    for (auto& btn : app_buttons) {
        ScrollView_main->removeChild(btn);
    }
    for (auto& lbl : app_labels) {
        ScrollView_main->removeChild(lbl);
    }
    app_buttons.clear();
    app_labels.clear();
    
    int visible_app_count = 0;
    
    // Count visible apps (apps with icons)
    for (int i = 0; i < list_count; i++) {
        if (app_list[i]->icon) {
            visible_app_count++;
        }
    }
    
    // Calculate total content width (same layout as luncher)
    // Layout: start_x + n * (ICON_WIDTH + spacing)
    int total_width = LAUNCHER_START_X + visible_app_count * (ICON_WIDTH + LAUNCHER_ICON_SPACING);
    if (total_width <= APP_WINDOW_WIDTH) {
        total_width = APP_WINDOW_WIDTH;  // Minimum width
    } else {
        ScrollView_main->setScrollEnabled(true);
    }
    printf("total_width %d \r\n",total_width);
    ScrollView_main->setContentWidth(total_width);
    
    // Add app icons and labels
    int x_pos = LAUNCHER_START_X;  // Starting X position (same as luncher: 16)
    for (int i = 0; i < list_count; i++) {
        if (!app_list[i]->icon) {
            continue;
        }
        
        //不显示无屏设备
        if (app_list[i]->app_name && strcmp(app_list[i]->app_name, "test") == 0) {
            continue;
        }

        // Create button for app icon (56x56)
        auto button = std::make_shared<ButtonView>(ICON_WIDTH, ICON_HEIGHT);
        button->setBoundaryBuffer(gImage_round_icon_boundary);
        button->setImageBuffer(app_list[i]->icon);
        button->setVisible(true);
        
        // Calculate vertical centering: ScrollView height is 120, icon+label total is 76
        int total_content_height = ICON_HEIGHT + LAUNCHER_LABEL_HEIGHT;  // 56 + 20 = 76
        int scroll_view_height = 120;
        int y_icon = (scroll_view_height - total_content_height) / 2;  // Center vertically
        
        ScrollView_main->addView(button, x_pos, y_icon);
        
        // Create label for app name below icon (same as luncher: ICON_WIDTH x 20)
        auto label = std::make_shared<LabelView>(ICON_WIDTH, LAUNCHER_LABEL_HEIGHT);
        label->setTextColor(0);
        label->setTransparent(true);
        label->setText(app_list[i]->app_name);
        label->setVisible(true);
        
        // Label position: below icon
        int y_label = y_icon + ICON_HEIGHT;
        ScrollView_main->addView(label, x_pos, y_label);
        
        // Set click handler to run the app
        App_t* current_app = app_list[i];
        button->setOnClick([current_app](void*) {
            goldie_run_app(current_app);
        });
        
        app_buttons.push_back(button);
        app_labels.push_back(label);
        
        // Spacing same as luncher: ICON_WIDTH + 24
        x_pos += ICON_WIDTH + LAUNCHER_ICON_SPACING;
    }
    
    // Refresh display
    Window_main->flush(0, 0, APP_WINDOW_WIDTH, APP_WINDOW_HEIGHT);
}

static void goldie_app_run(void)
{
    goldie_mutex_init(&ui_mutex);
    goldie_mutex_lock(&ui_mutex);
    wifi_service = (WifiService*)wait_service(WIFI_SERVICE_INDEX);
    #ifdef SUPPORT_SLE
    sle_service = (SleSdpService*)wait_service(SLE_SDP_SERVICE_INDEX);
    #endif
#ifdef SUPPORT_BATTERY
#ifdef DRV_CORE
          battery_fd = goldie_open(BAT_DRV_NAME, O_RDONLY);
#else
	battery_drv = (BatDrv*)wait_drv(BATTERY_DRV_INDEX);
#endif
#endif
    // Get app list
    app_list = get_app_list(&app_count);
    
    // Initialize UI
    main_ui_init();
	
	update_datetime_view();
	update_battery_view();
    // Show apps in ScrollView
    show_apps(app_list, app_count);
    
    // Register event service for battery power updates
    evt_service = (EventService*)wait_service(EVENT_SERVICE_INDEX);
    if (evt_service) {
        evt_service->register_broadcast_recv(EVENT_BROADCAST_POWER, update_bat_msg);
        evt_service->register_broadcast_recv(EVENT_BROADCAST_TIMERUPDATE, time_update);
    }
    app_status = 1;
    goldie_mutex_unlock(&ui_mutex);		
}

static void goldie_app_suspend(void)
{
    goldie_mutex_lock(&ui_mutex);	
    window_suspend();
    app_status = 0;
    goldie_mutex_unlock(&ui_mutex);		
}

static void goldie_app_resume(void)
{
    goldie_mutex_lock(&ui_mutex);
    window_resume();
	update_datetime_view();
	update_battery_view();
    app_status = 1;
    goldie_mutex_unlock(&ui_mutex);			
}

static void goldie_app_exit(void)
{
    goldie_mutex_lock(&ui_mutex);
    window_exit();
    app_status = 0;
#ifdef SUPPORT_BATTERY	
#ifdef DRV_CORE
		goldie_close(battery_fd);
#endif
#endif
    goldie_mutex_unlock(&ui_mutex);	
}

static void goldie_keyboard_event(int pressure, int key);

static App_t launcher = {
    "launcher",       // app_name char*
    goldie_app_run,       // h_app_run
    nullptr, //goldie_app_exit,      // h_app_exit
    goldie_app_suspend,   // h_app_suspend
    goldie_app_resume,    // h_app_resume
    goldie_touch_event,   // h_touch_event
    goldie_keyboard_event,// h_keyboard_event
    nullptr, //(uint16_t*)gImage_default_icon,             
};

static void goldie_keyboard_event(int pressure, int key)
{
    if((key == SYSTEM_KEY_VALUE_BACK) && (pressure == 1))
    {
        goldie_exit_app(&launcher);
    }else if ((key == SYSTEM_KEY_VALUE_WAKEUP) && (pressure == 1)) //右键进入对讲机APP
    {
        for (int i = 0; i < app_count; i++) 
        {
            if (app_list[i] && app_list[i]->app_name) 
            {
                if (strcmp(app_list[i]->app_name, "对讲机") == 0) 
                {
                    goldie_run_app(app_list[i]);
                    return;
                }
            }
        }
        printf("[Launcher] 未在应用列表中找到“对讲机”应用。\n");
    }
}

static void launcher_entry(void)
{
    install_app(&launcher);
}

GOLDIE_INIT_CALL_(launcher_entry);
