/*This file is automatically generated by the tinyui tool 
and contains the main_ui. h file, which calls the initialization 
function main_ui_init() to create the UI interface. You need to 
add code related to business logic here..*/
#include <stdio.h>
#include <string.h>
#include <stdlib.h>
#include <atomic>
#include "main_ui.h"
#include "default_app_icon.h" 
// 包含信号图片头文件
#include "rgb16_Scene_32_20.h"
// 包含麦克风状态图片头文件
#include "rgb16_Record_24_20.h"
#include "rgb16_Record1_24_21.h"
// 包含录音按钮状态图片头文件
#include "rgb16_Recording_64_61.h"
#include "rgb16_Recording1_64_61.h"
#include "rgb16_Walkie_talkie_56_56.h"
extern "C" { 
#include "goldie_osal.h" 
#include "service_manager.h" 
#include "app_manager.h" 
#include "sle_sdp_service.h"
#include "sle_wtp_service.h"
} 

// 前向声明
static void goldie_app_run(void);
static void goldie_app_exit(void);
static void goldie_app_suspend(void);
static void goldie_app_resume(void);
static void goldie_touch_event(int pressure, int x, int y);
static void goldie_keyboard_event(int pressure, int key);

// 函数声明
static void update_device_display(void);
static void update_signal_images(void);
static int record_and_play_thread(void *arg);
uint16_t* audio_buffer = NULL;  

#ifdef PLATFORM_TYPE_WS63
static AualgoService* maualgo_service;
#endif
static   bool notify_ringing =  false;
#define MAX_PAIRED_DEVICES 6
static sle_connection_info_t paired_devices[MAX_PAIRED_DEVICES];
static uint32_t paired_device_count = 0;

// 线程管理
static void *reconnect_thread_handle = NULL;
static bool reconnect_thread_running = false;
static SleSdpService *sle_service = NULL;
static sleWtpService *sle_wtp_service = NULL;

static sle_device_info_t sle_devices[MAX_PAIRED_DEVICES];
static bool keyboard_wakeup_first_flag = false;
static App_t sle_recorder = {
    "对讲机",       // app_name char*
    goldie_app_run,       // h_app_run
    goldie_app_exit,      // h_app_exit
    goldie_app_suspend,   // h_app_suspend
    goldie_app_resume,    // h_app_resume
    goldie_touch_event,   // h_touch_event
    goldie_keyboard_event,// h_keyboard_event
    (uint16_t*)rgb16_Walkie_talkie_56_56,             
};

/* 更新设备显示 */
static void update_device_display(void) {
    char device_name[7];
    // 获取所有设备视图的数组
    std::shared_ptr<TextEditView> device_views[] = {
        TextEditView_device_1,
        TextEditView_device_2,
        TextEditView_device_3,
        TextEditView_device_4,
        TextEditView_device_5,
        TextEditView_device_6
    };
    
    std::shared_ptr<FrameView> frame_views[] = {
        FrameView_device_1,
        FrameView_device_2,
        FrameView_device_3,
        FrameView_device_4,
        FrameView_device_5,
        FrameView_device_6
    };
    
    #ifdef SUPPORT_SLE
    // 显示已配对的设备
    for (int i = 0; i < paired_device_count && i < 6; i++) {
        if (device_views[i]) {
	  memset(device_name,0,7);
	  snprintf(device_name, 7,
                             "%02X%02X%02X", paired_devices[i].addr.addr[3], paired_devices[i].addr.addr[4], 
                             paired_devices[i].addr.addr[5]);
            device_views[i]->setText(device_name);
            device_views[i]->setVisible(true);
        }
        if (frame_views[i]) {
            frame_views[i]->setVisible(true);
        }
    }
    
    // 隐藏未使用的设备视图
    for (int i = paired_device_count; i < 6; i++) {
        if (device_views[i]) {
            device_views[i]->setVisible(false);
        }
        if (frame_views[i]) {
            frame_views[i]->setVisible(false);
        }
    }
    #endif
    // 刷新窗口
    Window_record->flush(0, 0, APP_WINDOW_WIDTH, APP_WINDOW_HEIGHT);
}


/* 更新信号图片 */
static void update_signal_images(void) {
	// 获取所有信号控件的数组
       std::shared_ptr<LabelView> signal_views[] = {
		LabelView_signal_1,
		LabelView_signal_2,
		LabelView_signal_3,
		LabelView_signal_4,
		LabelView_signal_5,
		LabelView_signal_6
	};

    #ifdef SUPPORT_SLE
    if (sle_service == NULL) {
        sle_service = (SleSdpService*)get_service(SLE_SDP_SERVICE_INDEX);
        if (sle_service == NULL) {
            printf("[SLE Record] ERROR: Failed to get SLE service for signal update\n");
            return;
        }
    }
    printf("paired_device_count is %d \r\n",paired_device_count);
    // 检查每个已配对设备的连接状态并更新对应的信号图片
    for (int i = 0; i < paired_device_count && i < 6; i++) {
        if (!signal_views[i]) {
            continue;
        }
	printf("paired_devices[%d].state is%d \r\n",i,paired_devices[i].state);
        if (paired_devices[i].state) {
            // 使用连接状态的信号图片
            signal_views[i]->setImageBuffer((uint16_t*)&rgb16_Scene_32_20);
        } else {
            // 使用默认的信号图片
            signal_views[i]->setImageBuffer((uint16_t*)&rgb16_signal1_32_20);
        }
        
        // 刷新控件
        signal_views[i]->flush(0, 0, 32, 20);
    }
    
    // 对于未使用的设备，隐藏或显示默认图片
    for (int i = paired_device_count; i < 6; i++) {
        if (signal_views[i]) {
            // 显示默认信号图片
            signal_views[i]->setImageBuffer((uint16_t*)&rgb16_signal1_32_20);
            signal_views[i]->flush(0, 0, 32, 20);
        }
    }
    #endif
}

static void goldie_touch_event(int pressure, int x, int y)
{
    Window_record->handleEvent(pressure, x, y);
}

static void goldie_app_suspend(void)
{
    window_suspend();
}

static void goldie_app_resume(void)
{
    window_resume();
}

// ============================================
// 录音和对讲功能（简化版本，仅保留UI和发送功能）
// ============================================

// 录音相关全局变量
#define SAMPEL_RATE   8000
#define FRAME_MS  80
#define BYTES_PER_FRAME 2
#define RECORD_BUFFER_SIZE   2*(BYTES_PER_FRAME*FRAME_MS*SAMPEL_RATE/1000)  
#define MIN_DATA_SIZE 960

static int thread_stoped_flag  =1;
static int running_flag = 0;
static int record_status = 0;
static int send_index = 0;
static bool is_recording = false;
static AudioService *audio_service = NULL;
static SdCardService *sdcard_service = NULL;
static FIL record_file;
static uint32_t total_audio_data_size = 0;
static void *recording_task_handle = NULL;

// 对讲相关全局变量
static bool is_sending_intercom = false;
static void *intercom_send_task_handle = NULL;

// 接收相关全局变量
static goldie_mutex session_mutex;
static int playing_device_index = -1; // 正在播放音频的设备索引

// 录音按钮点击处理函数（带对讲发送功能）
static void on_record_button_click_with_intercom(void) {
    FRESULT res;
    if (!is_recording) {
        // 启动录音
        if (audio_service) {
            audio_service->record_start();
        }
        is_recording = true;
    } else {
        // 停止录音
        printf("[SLE Record] Stop recording...\n");
        is_recording = false;
        while (record_status) {
            goldie_msleep(100);
        }
        // 停止录音
        if (audio_service) {
            audio_service->record_stop();
        }
    }
}

static void start_record_and_play_thread(void) {
    if (running_flag == 1) {
        printf("[SLE Record] Record and reconnect thread is already running\n");
        return;
    }
    running_flag = 1;
    goldie_thread_lock();
    recording_task_handle = goldie_thread_create(record_and_play_thread, NULL, "record_play_thread", 0x1000);
    if (recording_task_handle) {
        goldie_thread_set_priority(recording_task_handle, 24);
        printf("[SLE Record] Record and play thread created successfully\n");
    }
    goldie_thread_unlock();
}
static void stop_record_and_play_thread(void){
    running_flag = 0;
    if (is_recording) {
        is_recording = false;
        while (record_status) {
            goldie_msleep(100);
        }
        
        if (audio_service) {
            audio_service->record_stop();
        }
    }
    while(!thread_stoped_flag){
         printf("wait for  thread_stoped_flag  \r\n");
    	goldie_msleep(100);
    }
    // 销毁线程资源
    if (recording_task_handle != NULL) {
        goldie_thread_destroy(recording_task_handle);
        recording_task_handle = NULL;
        printf("[SLE Record] Record and reconnect thread destroyed\n");
    }
}

// 更新麦克风图片状态
static void update_mic_images(bool is_playing, uint16_t connid) {
     int device_index = -1;
    // 获取所有麦克风控件的数组
    std::shared_ptr<LabelView> mic_views[] = {
        LabelView_mic_1,
        LabelView_mic_2,
        LabelView_mic_3,
        LabelView_mic_4,
        LabelView_mic_5,
        LabelView_mic_6
    };

    if (sle_service) {
		uint32_t count = MAX_PAIRED_DEVICES;	
		sle_service->svr_get_paired_devices(paired_devices,&count);
		paired_device_count = count;
    } 

    for(int i =0;i<paired_device_count;i++){
	   if((paired_devices[i].state == 1)&&(paired_devices[i].conn_id == connid)){
		device_index = i;
		break;
	   }
    }


    if (is_playing) {
	    // 检查设备索引是否有效
	    if (device_index < 0 || device_index >= paired_device_count || device_index >= 6) {
	        printf("[SLE Record] ERROR: Invalid device index %d for mic image update\n", device_index);
	        return;
	    }

	    if (!mic_views[device_index]) {
	        printf("[SLE Record] ERROR: Mic view %d is null\n", device_index);
	        return;
	    }
        // 正在播放音频，显示播放状态的图片
        printf("[SLE Record] Device %d is playing audio, showing playing mic image\n", 
               device_index);
        mic_views[device_index]->setImageBuffer((uint16_t*)&rgb16_Record_24_20);
	mic_views[device_index]->flush(0, 0, 24, 20);
    } else {
        // 未播放音频，显示原来的图片
        printf("[SLE Record] Device %d is not playing audio, showing default mic image\n", 
               device_index);
	for(int j =0;j<6;j++){
        		mic_views[j]->setImageBuffer((uint16_t*)&rgb16_Record1_24_21);
		mic_views[j]->flush(0, 0, 24, 20);
	}
    }
}

static uint16_t last_connid = 0xffff;
static uint16_t current_connid = 0xffff;

// 录音和重连合并线程函数
static int record_and_play_thread(void *arg) {
    // 音频缓冲区
    uint16_t* mono_buffer = NULL;    // 单声道缓冲区
    static int scan_count = 0;
    wtp_notify_data notify_data = {0};
    float record_volume = 0.0f;
    float play_volume = 0.0f;
    float current_record_volume = 0.0f;
    float current_play_volume = 0.0f;
    record_volume = audio_service->get_volume(AUDIO_RECORD_STREAM);
    play_volume = audio_service->get_volume(AUDIO_PLAY_STREAM_USER);
    // 分配音频缓冲区
    if (!audio_buffer) {
        printf("[SLE Record] Failed to allocate audio buffer\n");
        return -1;
    }
    mono_buffer = audio_buffer;
    
    printf("[SLE Record] Record and reconnect thread started\n");
    while (running_flag) {
	thread_stoped_flag = 0;
        // ========== 第一部分：录音处理 ==========
        if (is_recording) {
	   printf("is_recording \r\n");
            record_status = 1;
	   audio_service->set_volume(AUDIO_RECORD_STREAM,1.0f);
            // 从音频服务读取录音数据
            int read_len = audio_service->audio_read(audio_buffer, RECORD_BUFFER_SIZE);
            if (read_len > 0) {
                // 8k双通道PCM数据，丢弃通道1，只保存通道0
                int sample_count = read_len / sizeof(short);
                int mono_samples = sample_count / 2;
                // 提取通道0数据（左声道）
                for (int i = 0; i < mono_samples; i++) {
                    mono_buffer[i] = audio_buffer[i * 2];  // 取左声道数据
                }
	       int ret = -1; 
	       if(send_index ==0){
	       		ret = sle_wtp_service->write_data((uint8_t*)mono_buffer,mono_samples*2,true,false);
	       }else{
			ret = sle_wtp_service->write_data((uint8_t*)mono_buffer,mono_samples*2,false,false);
	       }
	       if(!ret){
	       	send_index++;
	       }
            } 
	   goldie_msleep(30);
        }
        else {
	    audio_service->set_volume(AUDIO_RECORD_STREAM,record_volume);
            record_status = 0;
	   if(send_index>10){
		  memset(audio_buffer, 0,RECORD_BUFFER_SIZE);
		  sle_wtp_service->write_data((uint8_t*)audio_buffer,MIN_DATA_SIZE,false,true);
            } 
	   send_index = 0;
	   int read_out = 0;
	   uint16_t connid =0;
	   read_out = sle_wtp_service->read_data((uint8_t*)audio_buffer,RECORD_BUFFER_SIZE,&connid);
	   if(read_out>0){
	   	audio_service->set_volume(AUDIO_PLAY_STREAM_USER,1.0);
	   	current_connid = connid;
	   	audio_service->audio_write((uint16_t*)audio_buffer,read_out);
		if(notify_ringing){
			audio_service->stop_ring();
			notify_ringing = false;
		}
		goldie_msleep(20);
	   }else{
	         audio_service->set_volume(AUDIO_PLAY_STREAM_USER,play_volume);
	         current_connid = 0xffff;
		goldie_msleep(50);
	   }
	   if(last_connid !=current_connid )
	   {
	   	if(current_connid == 0xffff){
			update_mic_images(false,current_connid);
		}else{
	   		update_mic_images(true,current_connid);
		}
		last_connid = current_connid;
	   }
        }
	if(sle_wtp_service->read_notify(&notify_data))
	{
		if(notify_data.notify_id == 1)
		{
			notify_ringing = true;
			audio_service->play_ring(AUDIO_RING_ID_ALARM,1);			
			sle_wtp_service->clear_notify();
		}
	}
    }
    thread_stoped_flag = 1;
    printf("[SLE Record] Record and reconnect thread stopped\n");
    return 0;
}

// 修改init_views函数，添加录音按钮回调
static void init_views(void)
{
    // 设置返回按钮点击回调
    ButtonView_record_back->setOnClick([](void* id) {
        printf("[SLE Record] Back button clicked, exiting app\n");
        goldie_exit_app(&sle_recorder);
    });
    
    update_device_display();
    //启动录音和重连合并线程
    start_record_and_play_thread();
}

#ifdef SUPPORT_SLE
/* 星闪状态回调函数 */
static void sle_status_callback(SleStatusType status, void* data) {
     uint32_t count	= MAX_PAIRED_DEVICES;
    switch (status) {
        case SLE_STATUS_ENABLED:
            printf("[Walkie-Talkie] SLE enabled\n");
            break;
        case SLE_STATUS_DISABLED:
            printf("[Walkie-Talkie] SLE disabled\n");
		if(sle_service){
			sle_service->svr_get_paired_devices(paired_devices,&count);
		}
		paired_device_count = count;
	   update_signal_images();
            break;
        case SLE_STATUS_SCANNING:
            printf("[Walkie-Talkie] Scanning started\n");
            break;
        case SLE_STATUS_SCAN_DONE:
            printf("[Walkie-Talkie] Scanning stopped\n");
            break;
        case SLE_STATUS_DEVICE_LIST_UPDATED:
            printf("[Walkie-Talkie] Device list updated\n");
		if(sle_service){
			sle_service->svr_get_paired_devices(paired_devices,&count);
		}
		paired_device_count = count;
		update_signal_images();			
            break;
        case SLE_STATUS_CONNECTION_LIST_UPDATED: {
            printf("[Walkie-Talkie] Connection list updated\n");
		if(sle_service){
			sle_service->svr_get_paired_devices(paired_devices,&count);
		}
		paired_device_count = count;
		update_signal_images();			
            break;
        }
        case SLE_STATUS_ANNOUNCING:
            break;
        case SLE_STATUS_ANNOUNCE_STOPPED:
            break;
	case SLE_STATUS_PAIRED_STATUS_UPDATED:
		if(sle_service){
			sle_service->svr_get_paired_devices(paired_devices,&count);
		}
		paired_device_count = count;
		update_signal_images();
	        printf("[Walkie-Talkie] piared status changed \n");
            break;
        default:
            printf("[Walkie-Talkie] Unknown status: %d\n", status);
            break;
    }
}
#endif

// 修改goldie_app_run函数，获取音频服务和启动录音线程，并注册接收回调
static void goldie_app_run(void)
{
    keyboard_wakeup_first_flag=1;//首次标志恢复
    main_ui_init();
    audio_buffer = (uint16_t*)goldie_malloc(RECORD_BUFFER_SIZE);
    // 获取音频服务和SD卡服务
    audio_service = (AudioService*)wait_service(AUDIO_SERVICE_INDEX);
    sdcard_service = (SdCardService*)wait_service(SDCARD_SERVICE_INDEX);
#ifdef PLATFORM_TYPE_WS63
    maualgo_service = (AualgoService*)wait_service(AUALGO_SERVICE_INDEX);
    maualgo_service->puase();
#endif
    // 获取SLE服务并注册数据接收回调
   sle_service = (SleSdpService*)wait_service(SLE_SDP_SERVICE_INDEX);
    if (sle_service) {
		uint32_t count	= MAX_PAIRED_DEVICES;	
		sle_service->svr_get_paired_devices(paired_devices,&count);
		paired_device_count = count;
        #ifdef SUPPORT_SLE
        sle_service->register_callback(sle_status_callback,SLE_PROFILE_INDEX_SDP);
        if (sle_service && sle_service->svr_get_mode() == 0) {
        sle_service->trigger_event(SLE_EVENT_START_SCAN, NULL);
        } else {
        sle_service->trigger_event(SLE_EVENT_START_ANNOUNCE, NULL);
        }
        #endif
		update_signal_images();
    }    
    sle_wtp_service = (sleWtpService*)wait_service(SLE_WTP_SERVICE_INDEX);
    if(sle_wtp_service){    	
    	sle_wtp_service ->voice_codec_init();
    }
    // 初始化互斥锁
    goldie_mutex_init(&session_mutex);
    init_views();
    audio_service->play_start();
    printf("goldie_app_run \r\n");
}

// 修改goldie_app_exit函数
static void goldie_app_exit(void)
{
     if(sle_service){
	sle_service->register_callback(NULL,SLE_PROFILE_INDEX_SDP);
     }
    // 停止录音和重连合并线程
    stop_record_and_play_thread();
    goldie_msleep(100);
    audio_service->play_stop();
    window_exit();
    goldie_free(audio_buffer);
    if(sle_wtp_service){
    	sle_wtp_service ->voice_codec_destroy();
    }
#ifdef PLATFORM_TYPE_WS63
    maualgo_service = (AualgoService*)wait_service(AUALGO_SERVICE_INDEX);
    maualgo_service->run();
#endif	
}
static void goldie_keyboard_event(int pressure, int key)
{
    if((key == SYSTEM_KEY_VALUE_BACK) && (pressure == 1))
    {
    	if(notify_ringing){
			audio_service->stop_ring();
			notify_ringing = false;
		}
        goldie_exit_app(&sle_recorder);
    }
    else if(key == SYSTEM_KEY_VALUE_WAKEUP && (pressure == 0) && keyboard_wakeup_first_flag)//第一次为松开
    {
   	    //这是首次触发按键抬起、是主界面右键触发的--直接返回
        printf("\r\n\r\n按键松开\r\n\r\n");
        return;
    }else if(key == SYSTEM_KEY_VALUE_WAKEUP)
    {
   	 if(notify_ringing){
		audio_service->stop_ring();
		notify_ringing = false;
	}
        printf("[SLE Record] WAKEUP key event: pressure=%d\n", pressure);
        
        // 更新LabelView_switch的背景图
        if (LabelView_switch) {
            if (pressure == 1) {
                // 按键按下：修改为rgb16_Recording_64_61
                printf("[SLE Record] WAKEUP key pressed\n");
                LabelView_switch->setImageBuffer((uint16_t*)&rgb16_Recording_64_61);
            } else if (pressure == 0) {
                // 按键松开：恢复为rgb16_Recording1_64_61
                printf("[SLE Record] WAKEUP key released\n");
                LabelView_switch->setImageBuffer((uint16_t*)&rgb16_Recording1_64_61);
            }
            // 刷新控件
            LabelView_switch->flush(0, 0, 64, 61);
        } else {
            printf("[SLE Record] WARNING: LabelView_switch is null\n");
        }
        
        // 调用录音按钮功能
        on_record_button_click_with_intercom();
    }
    keyboard_wakeup_first_flag=0;//首次标志清除
}

static void test_entry(void)
{
    install_app(&sle_recorder);
}

GOLDIE_INIT_CALL_(test_entry);
