/*This file is automatically generated by the tinyui tool and should not be modified.*/
#ifndef INCLUDE_MAIN_UI_H
#define INCLUDE_MAIN_UI_H
#include <memory>
#include <vector>

#include "goldie_display.h" 
// 控件头文件
#include "label_view.h"
#include "textedit_view.h"
#include "frame_view.h"
#include "button_view.h"
#include "window.h"

// 图片头文件
#include "rgb16_signal1_32_20.h"
#include "rgb16_Record1_24_21.h"
#include "rgb16_Record1_24_21.h"
#include "rgb16_signal1_32_20.h"
#include "rgb16_signal1_32_20.h"
#include "rgb16_Record1_24_21.h"
#include "rgb16_Record1_24_21.h"
#include "rgb16_signal1_32_20.h"
#include "rgb16_Recording1_64_61.h"
#include "rgb16_back2_24_24.h"
#include "rgb16_Record1_24_21.h"
#include "rgb16_signal1_32_20.h"
#include "rgb16_signal1_32_20.h"
#include "rgb16_Record1_24_21.h"

// 掩码头文件
#include "round_rect_32_20_r1_boundary.h"
#include "round_rect_24_21_r1_boundary.h"
#include "round_rect_64_16_r1_boundary.h"
#include "round_rect_72_42_r1_boundary.h"
#include "round_rect_24_21_r1_boundary.h"
#include "round_rect_32_20_r1_boundary.h"
#include "round_rect_64_16_r1_boundary.h"
#include "round_rect_72_42_r1_boundary.h"
#include "round_rect_32_20_r1_boundary.h"
#include "round_rect_64_16_r1_boundary.h"
#include "round_rect_24_21_r1_boundary.h"
#include "round_rect_72_42_r1_boundary.h"
#include "round_rect_64_16_r1_boundary.h"
#include "round_rect_24_21_r1_boundary.h"
#include "round_rect_32_20_r1_boundary.h"
#include "round_rect_72_42_r1_boundary.h"
#include "ellipse_64_61_boundary.h"
#include "round_rect_56_20_r1_boundary.h"
#include "round_rect_24_24_r1_boundary.h"
#include "round_rect_232_32_r4_boundary.h"
#include "round_rect_24_21_r1_boundary.h"
#include "round_rect_64_16_r1_boundary.h"
#include "round_rect_32_20_r1_boundary.h"
#include "round_rect_72_42_r1_boundary.h"
#include "round_rect_32_20_r1_boundary.h"
#include "round_rect_24_21_r1_boundary.h"
#include "round_rect_64_16_r1_boundary.h"
#include "round_rect_72_42_r1_boundary.h"
#include "round_rect_256_199_r0_boundary.h"
// 全局控件变量定义
static std::shared_ptr<LabelView> LabelView_signal_6;
static std::shared_ptr<LabelView> LabelView_mic_6;
static std::shared_ptr<TextEditView> TextEditView_device_6;
static std::shared_ptr<FrameView> FrameView_device_6;
static std::shared_ptr<LabelView> LabelView_mic_2;
static std::shared_ptr<LabelView> LabelView_signal_2;
static std::shared_ptr<TextEditView> TextEditView_device_2;
static std::shared_ptr<FrameView> FrameView_device_2;
static std::shared_ptr<LabelView> LabelView_signal_3;
static std::shared_ptr<TextEditView> TextEditView_device_3;
static std::shared_ptr<LabelView> LabelView_mic_3;
static std::shared_ptr<FrameView> FrameView_device_3;
static std::shared_ptr<TextEditView> TextEditView_device_1;
static std::shared_ptr<LabelView> LabelView_mic_1;
static std::shared_ptr<LabelView> LabelView_signal_1;
static std::shared_ptr<FrameView> FrameView_device_1;
static std::shared_ptr<LabelView> LabelView_switch;
static std::shared_ptr<TextEditView> TextEditView_1770083955802;
static std::shared_ptr<ButtonView> ButtonView_record_back;
static std::shared_ptr<FrameView> FrameView_top;
static std::shared_ptr<LabelView> LabelView_mic_4;
static std::shared_ptr<TextEditView> TextEditView_device_4;
static std::shared_ptr<LabelView> LabelView_signal_4;
static std::shared_ptr<FrameView> FrameView_device_4;
static std::shared_ptr<LabelView> LabelView_signal_5;
static std::shared_ptr<LabelView> LabelView_mic_5;
static std::shared_ptr<TextEditView> TextEditView_device_5;
static std::shared_ptr<FrameView> FrameView_device_5;
static std::shared_ptr<FrameView> FrameView_main;
static std::shared_ptr<FrameView> FrameView_background;
static std::shared_ptr<Window> Window_record;

static void main_ui_init()
{
    LabelView_signal_6 = std::make_shared<LabelView>(32, 20);
    LabelView_signal_6->setColor(0xBEF7);
    LabelView_signal_6->setTextColor(0);
    LabelView_signal_6->setBoundaryBuffer(round_rect_32_20_r1_boundary);
    LabelView_signal_6->setVisible(true);
    LabelView_signal_6->setImageBuffer((uint16_t*)&rgb16_signal1_32_20);

    LabelView_mic_6 = std::make_shared<LabelView>(24, 21);
    LabelView_mic_6->setColor(0xBEF7);
    LabelView_mic_6->setTextColor(0);
    LabelView_mic_6->setBoundaryBuffer(round_rect_24_21_r1_boundary);
    LabelView_mic_6->setVisible(true);
    LabelView_mic_6->setImageBuffer((uint16_t*)&rgb16_Record1_24_21);

    TextEditView_device_6 = std::make_shared<TextEditView>(64, 16);
    TextEditView_device_6->setColor(0xBEF7);
    TextEditView_device_6->setTextColor(0);
    TextEditView_device_6->setBoundaryBuffer(round_rect_64_16_r1_boundary);
    TextEditView_device_6->setVisible(true);

    FrameView_device_6 = std::make_shared<FrameView>(72, 42);
    FrameView_device_6->setColor(0xBEF7);
    FrameView_device_6->setTextColor(0);
    FrameView_device_6->setBoundaryBuffer(round_rect_72_42_r1_boundary);
    FrameView_device_6->setVisible(true);

    LabelView_mic_2 = std::make_shared<LabelView>(24, 21);
    LabelView_mic_2->setColor(0xBEF7);
    LabelView_mic_2->setTextColor(0);
    LabelView_mic_2->setBoundaryBuffer(round_rect_24_21_r1_boundary);
    LabelView_mic_2->setVisible(true);
    LabelView_mic_2->setImageBuffer((uint16_t*)&rgb16_Record1_24_21);

    LabelView_signal_2 = std::make_shared<LabelView>(32, 20);
    LabelView_signal_2->setColor(0xFFFF);
    LabelView_signal_2->setTextColor(0);
    LabelView_signal_2->setBoundaryBuffer(round_rect_32_20_r1_boundary);
    LabelView_signal_2->setVisible(true);
    LabelView_signal_2->setImageBuffer((uint16_t*)&rgb16_signal1_32_20);

    TextEditView_device_2 = std::make_shared<TextEditView>(64, 16);
    TextEditView_device_2->setColor(0xBEF7);
    TextEditView_device_2->setTextColor(0);
    TextEditView_device_2->setBoundaryBuffer(round_rect_64_16_r1_boundary);
    TextEditView_device_2->setVisible(true);

    FrameView_device_2 = std::make_shared<FrameView>(72, 42);
    FrameView_device_2->setColor(0xBEF7);
    FrameView_device_2->setTextColor(0);
    FrameView_device_2->setBoundaryBuffer(round_rect_72_42_r1_boundary);
    FrameView_device_2->setVisible(true);

    LabelView_signal_3 = std::make_shared<LabelView>(32, 20);
    LabelView_signal_3->setColor(0xFFFF);
    LabelView_signal_3->setTextColor(0);
    LabelView_signal_3->setBoundaryBuffer(round_rect_32_20_r1_boundary);
    LabelView_signal_3->setVisible(true);
    LabelView_signal_3->setImageBuffer((uint16_t*)&rgb16_signal1_32_20);

    TextEditView_device_3 = std::make_shared<TextEditView>(64, 16);
    TextEditView_device_3->setColor(0xBEF7);
    TextEditView_device_3->setTextColor(0);
    TextEditView_device_3->setBoundaryBuffer(round_rect_64_16_r1_boundary);
    TextEditView_device_3->setVisible(true);

    LabelView_mic_3 = std::make_shared<LabelView>(24, 21);
    LabelView_mic_3->setColor(0xBEF7);
    LabelView_mic_3->setTextColor(0);
    LabelView_mic_3->setBoundaryBuffer(round_rect_24_21_r1_boundary);
    LabelView_mic_3->setVisible(true);
    LabelView_mic_3->setImageBuffer((uint16_t*)&rgb16_Record1_24_21);

    FrameView_device_3 = std::make_shared<FrameView>(72, 42);
    FrameView_device_3->setColor(0xBEF7);
    FrameView_device_3->setTextColor(0);
    FrameView_device_3->setBoundaryBuffer(round_rect_72_42_r1_boundary);
    FrameView_device_3->setVisible(true);

    TextEditView_device_1 = std::make_shared<TextEditView>(64, 16);
    TextEditView_device_1->setColor(0xBEF7);
    TextEditView_device_1->setTextColor(0);
    TextEditView_device_1->setBoundaryBuffer(round_rect_64_16_r1_boundary);
    TextEditView_device_1->setVisible(true);

    LabelView_mic_1 = std::make_shared<LabelView>(24, 21);
    LabelView_mic_1->setColor(0xBEF7);
    LabelView_mic_1->setTextColor(0);
    LabelView_mic_1->setBoundaryBuffer(round_rect_24_21_r1_boundary);
    LabelView_mic_1->setVisible(true);
    LabelView_mic_1->setImageBuffer((uint16_t*)&rgb16_Record1_24_21);

    LabelView_signal_1 = std::make_shared<LabelView>(32, 20);
    LabelView_signal_1->setColor(0xFFFF);
    LabelView_signal_1->setTextColor(0);
    LabelView_signal_1->setBoundaryBuffer(round_rect_32_20_r1_boundary);
    LabelView_signal_1->setVisible(true);
    LabelView_signal_1->setImageBuffer((uint16_t*)&rgb16_signal1_32_20);

    FrameView_device_1 = std::make_shared<FrameView>(72, 42);
    FrameView_device_1->setColor(0xBEF7);
    FrameView_device_1->setTextColor(0);
    FrameView_device_1->setBoundaryBuffer(round_rect_72_42_r1_boundary);
    FrameView_device_1->setVisible(true);

    LabelView_switch = std::make_shared<LabelView>(64, 61);
    LabelView_switch->setColor(0xFFFF);
    LabelView_switch->setTextColor(0);
    LabelView_switch->setBoundaryBuffer(ellipse_64_61_boundary);
    LabelView_switch->setVisible(true);
    LabelView_switch->setImageBuffer((uint16_t*)&rgb16_Recording1_64_61);

    TextEditView_1770083955802 = std::make_shared<TextEditView>(56, 20);
    TextEditView_1770083955802->setColor(0x0000);
    TextEditView_1770083955802->setTextColor(1);
    TextEditView_1770083955802->setText("对讲机");
    TextEditView_1770083955802->setBoundaryBuffer(round_rect_56_20_r1_boundary);
    TextEditView_1770083955802->setVisible(true);

    ButtonView_record_back = std::make_shared<ButtonView>(24, 24);
    ButtonView_record_back->setColor(0xFFFF);
    ButtonView_record_back->setTextColor(0);
    ButtonView_record_back->setBoundaryBuffer(round_rect_24_24_r1_boundary);
    ButtonView_record_back->setVisible(true);
    ButtonView_record_back->setImageBuffer((uint16_t*)&rgb16_back2_24_24);

    FrameView_top = std::make_shared<FrameView>(232, 32);
    FrameView_top->setColor(0x0000);
    FrameView_top->setTextColor(0);
    FrameView_top->setBoundaryBuffer(round_rect_232_32_r4_boundary);
    FrameView_top->setVisible(true);

    LabelView_mic_4 = std::make_shared<LabelView>(24, 21);
    LabelView_mic_4->setColor(0xBEF7);
    LabelView_mic_4->setTextColor(0);
    LabelView_mic_4->setBoundaryBuffer(round_rect_24_21_r1_boundary);
    LabelView_mic_4->setVisible(true);
    LabelView_mic_4->setImageBuffer((uint16_t*)&rgb16_Record1_24_21);

    TextEditView_device_4 = std::make_shared<TextEditView>(64, 16);
    TextEditView_device_4->setColor(0xBEF7);
    TextEditView_device_4->setTextColor(0);
    TextEditView_device_4->setBoundaryBuffer(round_rect_64_16_r1_boundary);
    TextEditView_device_4->setVisible(true);

    LabelView_signal_4 = std::make_shared<LabelView>(32, 20);
    LabelView_signal_4->setColor(0xFFFF);
    LabelView_signal_4->setTextColor(0);
    LabelView_signal_4->setBoundaryBuffer(round_rect_32_20_r1_boundary);
    LabelView_signal_4->setVisible(true);
    LabelView_signal_4->setImageBuffer((uint16_t*)&rgb16_signal1_32_20);

    FrameView_device_4 = std::make_shared<FrameView>(72, 42);
    FrameView_device_4->setColor(0xBEF7);
    FrameView_device_4->setTextColor(0);
    FrameView_device_4->setBoundaryBuffer(round_rect_72_42_r1_boundary);
    FrameView_device_4->setVisible(true);

    LabelView_signal_5 = std::make_shared<LabelView>(32, 20);
    LabelView_signal_5->setColor(0xFFFF);
    LabelView_signal_5->setTextColor(0);
    LabelView_signal_5->setBoundaryBuffer(round_rect_32_20_r1_boundary);
    LabelView_signal_5->setVisible(true);
    LabelView_signal_5->setImageBuffer((uint16_t*)&rgb16_signal1_32_20);

    LabelView_mic_5 = std::make_shared<LabelView>(24, 21);
    LabelView_mic_5->setColor(0xBEF7);
    LabelView_mic_5->setTextColor(0);
    LabelView_mic_5->setBoundaryBuffer(round_rect_24_21_r1_boundary);
    LabelView_mic_5->setVisible(true);
    LabelView_mic_5->setImageBuffer((uint16_t*)&rgb16_Record1_24_21);

    TextEditView_device_5 = std::make_shared<TextEditView>(64, 16);
    TextEditView_device_5->setColor(0xBEF7);
    TextEditView_device_5->setTextColor(0);
    TextEditView_device_5->setBoundaryBuffer(round_rect_64_16_r1_boundary);
    TextEditView_device_5->setVisible(true);

    FrameView_device_5 = std::make_shared<FrameView>(72, 42);
    FrameView_device_5->setColor(0xBEF7);
    FrameView_device_5->setTextColor(0);
    FrameView_device_5->setBoundaryBuffer(round_rect_72_42_r1_boundary);
    FrameView_device_5->setVisible(true);

    FrameView_main = std::make_shared<FrameView>(256, 199);
    FrameView_main->setColor(0x7DEF);
    FrameView_main->setTextColor(0);
    FrameView_main->setBoundaryBuffer(round_rect_256_199_r0_boundary);
    FrameView_main->setVisible(true);

    FrameView_background = std::make_shared<FrameView>(320, 240);
    FrameView_background->setColor(0x3CE7);
    FrameView_background->setTextColor(0);
    FrameView_background->setVisible(true);

    Window_record = std::make_shared<Window>(APP_WINDOW_START_X, APP_WINDOW_START_Y,320, 240);
    Window_record->setColor(0x8631);
    Window_record->setTextColor(0);
    Window_record->setVisible(true);

    // 建立控件父子关系
    FrameView_device_6->addView(TextEditView_device_6, 8, 22);
    FrameView_device_6->addView(LabelView_mic_6, 8, 1);
    FrameView_device_6->addView(LabelView_signal_6, 40, 1);
    FrameView_main->addView(FrameView_device_5, 88, 92);
    FrameView_main->addView(FrameView_device_4, 8, 92);
    FrameView_main->addView(FrameView_top, 8, 5);
    FrameView_main->addView(LabelView_switch, 96, 138);
    FrameView_main->addView(FrameView_device_1, 8, 43);
    FrameView_main->addView(FrameView_device_3, 168, 43);
    FrameView_main->addView(FrameView_device_2, 88, 43);
    FrameView_main->addView(FrameView_device_6, 168, 91);
    FrameView_device_2->addView(TextEditView_device_2, 8, 22);
    FrameView_device_2->addView(LabelView_signal_2, 40, 1);
    FrameView_device_2->addView(LabelView_mic_2, 8, 1);
    FrameView_device_3->addView(LabelView_mic_3, 8, 1);
    FrameView_device_3->addView(TextEditView_device_3, 8, 22);
    FrameView_device_3->addView(LabelView_signal_3, 40, 1);
    FrameView_device_1->addView(LabelView_signal_1, 40, 1);
    FrameView_device_1->addView(LabelView_mic_1, 8, 1);
    FrameView_device_1->addView(TextEditView_device_1, 8, 22);
    FrameView_top->addView(ButtonView_record_back, 16, 3);
    FrameView_top->addView(TextEditView_1770083955802, 48, 6);
    FrameView_device_4->addView(LabelView_signal_4, 40, 1);
    FrameView_device_4->addView(TextEditView_device_4, 8, 22);
    FrameView_device_4->addView(LabelView_mic_4, 8, 1);
    FrameView_device_5->addView(TextEditView_device_5, 8, 22);
    FrameView_device_5->addView(LabelView_mic_5, 8, 1);
    FrameView_device_5->addView(LabelView_signal_5, 40, 1);
    FrameView_background->addView(FrameView_main, 32, 15);
    Window_record->addView(FrameView_background, 0, 0);

    // 刷新窗口
    Window_record->flush(0, 0, APP_WINDOW_WIDTH, APP_WINDOW_HEIGHT);
}

static void window_exit(void)
{
    Window_record->setVisible(false);
    Window_record->removeAllViews();
	
    FrameView_device_6->removeAllChilds();
    FrameView_device_2->removeAllChilds();
    FrameView_device_3->removeAllChilds();
    FrameView_device_1->removeAllChilds();
    FrameView_device_4->removeAllChilds();
    FrameView_top->removeAllChilds();
    FrameView_device_5->removeAllChilds();
    FrameView_main->removeAllChilds();
    FrameView_background->removeAllChilds();

    LabelView_signal_6.reset();
    LabelView_mic_6.reset();
    TextEditView_device_6.reset();
    LabelView_mic_2.reset();
    LabelView_signal_2.reset();
    TextEditView_device_2.reset();
    LabelView_signal_3.reset();
    TextEditView_device_3.reset();
    LabelView_mic_3.reset();
    TextEditView_device_1.reset();
    LabelView_mic_1.reset();
    LabelView_signal_1.reset();
    LabelView_switch.reset();
    TextEditView_1770083955802.reset();
    ButtonView_record_back.reset();
    LabelView_mic_4.reset();
    TextEditView_device_4.reset();
    LabelView_signal_4.reset();
    LabelView_signal_5.reset();
    LabelView_mic_5.reset();
    TextEditView_device_5.reset();
    FrameView_device_6.reset();
    FrameView_device_2.reset();
    FrameView_device_3.reset();
    FrameView_device_1.reset();
    FrameView_top.reset();
    FrameView_device_4.reset();
    FrameView_device_5.reset();
    FrameView_main.reset();
    FrameView_background.reset();
    Window_record.reset();
}

static void window_suspend(void)
{
    Window_record->setVisible(false);
}

static void window_resume(void)
{
    Window_record->setVisible(true);
    Window_record->flush(0, 0, APP_WINDOW_WIDTH, APP_WINDOW_HEIGHT);
}

#endif //INCLUDE_MAIN_UI_H 

