#ifndef INCLUDE_GOLDIE_PLATFORM_H
#define INCLUDE_GOLDIE_PLATFORM_H
#define  DISPLAY_WIDTH  320
#define  DISPLAY_HEIGHT 240

#define ICON_WIDTH  56
#define ICON_HEIGHT 56

#define STATUS_BAR_HEIGHT  28
#define STATUS_BAR_WIDTH  DISPLAY_WIDTH

#define APP_WINDOW_START_X 0
//#define APP_WINDOW_START_Y STATUS_BAR_HEIGHT
#define APP_WINDOW_START_Y 0

#define APP_WINDOW_WIDTH DISPLAY_WIDTH
//#define APP_WINDOW_HEIGHT (DISPLAY_HEIGHT - STATUS_BAR_HEIGHT)
#define APP_WINDOW_HEIGHT DISPLAY_HEIGHT
#endif

