/*This file is automatically generated by the tinyui tool 
and contains the main_ui. h file, which calls the initialization 
function main_ui_init() to create the UI interface. You need to 
add code related to business logic here..*/
#include "main_ui.h"
#include "default_app_icon.h" 
extern "C" { 
#include "goldie_osal.h" 
#include "service_manager.h" 
#include "app_manager.h" 
} 

static void goldie_touch_event(int pressure, int x, int y)
{
    Window_1775700353792->handleEvent(pressure, x, y);
}

static void goldie_app_run(void)
{
    main_ui_init();
}

static void goldie_app_suspend(void)
{
    window_suspend();
}

static void goldie_app_resume(void)
{
    window_resume();
}

static void goldie_app_exit(void)
{
    window_exit();
}

static void goldie_keyboard_event(int pressure, int key);

static App_t shut_down = {
    "shut_down",       // app_name char*
    goldie_app_run,       // h_app_run
    goldie_app_exit,      // h_app_exit
    goldie_app_suspend,   // h_app_suspend
    goldie_app_resume,    // h_app_resume
    goldie_touch_event,   // h_touch_event
    goldie_keyboard_event,// h_keyboard_event
    nullptr,               
};

static void goldie_keyboard_event(int pressure, int key)
{
    if((key == SYSTEM_KEY_VALUE_BACK) && (pressure == 1))
    {
        goldie_exit_app(&shut_down);
    }
}

static void test_entry(void)
{
    install_app(&shut_down);
}

GOLDIE_INIT_CALL_(test_entry);
