/*This file is automatically generated by the tinyui tool
and contains the main_ui. h file, which calls the initialization
function main_ui_init() to create the UI interface. You need to
add code related to business logic here..*/
#include "main_ui.h"
#include "string.h"
#include "rgb16_record_icon_56_56.h"
extern "C" {
#include "goldie_osal.h"
#include "service_manager.h"
#include "app_manager.h"
#include "ff.h"
#ifdef USE_OPUS_CODEC
#include "tiny_codec_opus.h"
#endif
}

// 调试开关：取消注释以下宏定义以启用PCM文件转储
 //#define DUMP_PCM_FOR_DEBUG
#ifdef USE_OPUS_CODEC
static encoder_t* enc;
static decoder_t* dec;
#endif
static int play_thread_exit_flag =0;
static int record_thread_exit_flag =0;

#ifdef USE_OPUS_CODEC
#define RECODER_FILE_NAME "0:/rec.c2"
#else
#define RECODER_FILE_NAME "0:/rec.wav"
#endif
static AualgoService* maualgo_service;

#define SAMPEL_RATE   8000
#define FRAME_MS  80
#define BYTES_PER_FRAME 2
#define RECORD_BUFFER_SIZE   2*(BYTES_PER_FRAME*FRAME_MS*SAMPEL_RATE/1000)  

#define PLAYBACK_BUFFER_SIZE 2048
#ifdef USE_OPUS_CODEC
#define CODEC2_BUFFER_SIZE 2048
#endif
static int running_flag = 0;
static int record_status = 0;
static int playback_status = 0;

#define RECORDER_MONO

#ifdef USE_OPUS_CODEC
// Codec2文件头结构（简单版本，只保存文件大小）
typedef struct {
    uint32_t magic;          // 魔数：0x43443200 (CD2\0)
    uint32_t data_size;      // 音频数据大小（字节）
    uint32_t sample_rate;    // 采样率（8000 Hz）
    uint16_t num_channels;   // 声道数（1）
    uint16_t bits_per_sample; // 位深（16）
    uint32_t codec2_mode;    // Codec2模式
} codec2_header_t;
#endif

// 录音状态
static bool is_recording = false;
static bool is_playing = false;
static bool recording_thread_running = true;
static bool playback_thread_running = true;
static AudioService *audio_service = NULL;
static SdCardService *sdcard_service = NULL;
static FIL record_file;
static FIL playback_file;
static uint32_t total_audio_data_size = 0;
static uint32_t playback_file_size = 0;
static uint32_t playback_position = 0;

#ifdef DUMP_PCM_FOR_DEBUG
// 用于调试的PCM文件句柄
static FIL dump_pcm_record_file;
static FIL dump_pcm_playback_file;
#endif

#ifndef USE_OPUS_CODEC
typedef struct {
    char chunk_id[4];        // "RIFF"
    uint32_t chunk_size;     // 文件总大小 - 8
    char format[4];          // "WAVE"
    char subchunk1_id[4];    // "fmt "
    uint32_t subchunk1_size; // PCM格式为16
    uint16_t audio_format;   // PCM为1
    uint16_t num_channels;   // 单声道为1
    uint32_t sample_rate;    // 8000 Hz
    uint32_t byte_rate;      // sample_rate * num_channels * bits_per_sample/8
    uint16_t block_align;    // num_channels * bits_per_sample/8
    uint16_t bits_per_sample; // 16 bits
    char subchunk2_id[4];    // "data"
    uint32_t subchunk2_size; // 音频数据大小
} wav_header_t;

static void create_wav_header(wav_header_t *header, uint32_t data_size) {
    // RIFF chunk
    memcpy(header->chunk_id, "RIFF", 4);
    header->chunk_size = data_size + sizeof(wav_header_t) - 8; // 文件总大小 - 8
    memcpy(header->format, "WAVE", 4);

    // fmt subchunk
    memcpy(header->subchunk1_id, "fmt ", 4);
    header->subchunk1_size = 16; // PCM格式固定为16
    header->audio_format = 1;    // PCM格式
    header->num_channels = 1;    // 单声道
    header->sample_rate = 8000;  // 8kHz采样率
    header->bits_per_sample = 16; // 16位采样
    header->byte_rate = header->sample_rate * header->num_channels * header->bits_per_sample / 8;
    header->block_align = header->num_channels * header->bits_per_sample / 8;

    // data subchunk
    memcpy(header->subchunk2_id, "data", 4);
    header->subchunk2_size = data_size;
}
#endif
// 按钮点击处理函数
static void on_record_button_click(void*) {
    FRESULT res;

    if (!is_recording) {
        // 开始录音
        printf("Start recording...\n");

        // 设置按钮背景为录音状态
        Button_record->setImageBuffer((uint16_t*)&rgb16_record_button_104_104);
        Button_record->flush(0, 0, 104, 104);

        // 检查SD卡是否存在
        if (!sdcard_service || !sdcard_service->IsSdCardExists()) {
            printf("SD card not available\n");
            return;
        }
#ifdef USE_OPUS_CODEC
        // 打开或创建record.codec2文件
        res = f_open(&record_file, RECODER_FILE_NAME, FA_WRITE | FA_CREATE_ALWAYS);
        if (res != FR_OK) {
            printf("Failed to open record.codec2 file: %d\n", res);
            return;
        }
#else
        // 打开或创建record.wav文件
        res = f_open(&record_file, RECODER_FILE_NAME, FA_WRITE | FA_CREATE_ALWAYS);
        if (res != FR_OK) {
            printf("Failed to open record.wav file: %d\n", res);
            return;
        }

        // 先写入空的WAV文件头（录音完成后填充数据大小）
        wav_header_t header;
        memset(&header, 0, sizeof(header));
        UINT bytes_written;
        res = f_write(&record_file, &header, sizeof(header), &bytes_written);
        if (res != FR_OK) {
            printf("Failed to write WAV header: %d\n", res);
            f_close(&record_file);
            return;
        }
#endif

#ifdef DUMP_PCM_FOR_DEBUG
        // 打开PCM转储文件（录音原始PCM）
        res = f_open(&dump_pcm_record_file, "0:/rec_dump.pcm", FA_WRITE | FA_CREATE_ALWAYS);
        if (res != FR_OK) {
            printf("Failed to open rec_dump.pcm file: %d\n", res);
            // 可以选择继续录音但不转储，这里简单打印警告后继续
        }
#endif

        total_audio_data_size = 0;

        // 启动录音
        if (audio_service) {
            audio_service->record_start();
        }

        is_recording = true;

    } else {
        // 停止录音
        printf("bf Stop recording...\n");
        is_recording = false;
        while (record_status) {
            goldie_msleep(100);
        }
        printf("af Stop recording...\n");
        // 恢复按钮背景为默认状态
        Button_record->setImageBuffer((uint16_t*)&rgb16_record_button_dis_104_104);
        Button_record->flush(0, 0, 104, 104);

        // 停止录音
        if (audio_service) {
            audio_service->record_stop();
        }
        
        if (record_file.fs) {
#ifndef USE_OPUS_CODEC		
            // 更新WAV文件头（填充音频数据大小）
            wav_header_t header;
            create_wav_header(&header, total_audio_data_size);
            
            f_lseek(&record_file, 0);
            UINT bytes_written;
            FRESULT res = f_write(&record_file, &header, sizeof(header), &bytes_written);
            if (res != FR_OK) {
                printf("Failed to update WAV header: %d\n", res);
            }
#endif            
            // 关闭文件
            f_close(&record_file);
            memset(&record_file, 0, sizeof(FIL));
        }
        
#ifdef DUMP_PCM_FOR_DEBUG
        if (dump_pcm_record_file.fs) {
            f_close(&dump_pcm_record_file);
            memset(&dump_pcm_record_file, 0, sizeof(FIL));
        }
#endif

        total_audio_data_size = 0;
    }
}

// 播放按钮点击处理函数
static void on_play_button_click(void*) {
    FRESULT res;
    
    if (!is_playing) {
        // 检查是否正在录音
        if (is_recording) {
            printf("Cannot play while recording\n");
            return;
        }
        
        // 检查SD卡是否存在
        if (!sdcard_service || !sdcard_service->IsSdCardExists()) {
            printf("SD card not available\n");
            return;
        }
        
#ifdef USE_OPUS_CODEC
        // 打开录音文件
        res = f_open(&playback_file,RECODER_FILE_NAME, FA_READ);
        if (res != FR_OK) {
            printf("Failed to open rec.codec2 file for playback: %d\n", res);
            return;
        }
	playback_file_size = f_size(&playback_file);
        
        playback_position = 0;
#else
        // 打开录音文件
        res = f_open(&playback_file,RECODER_FILE_NAME, FA_READ);
        if (res != FR_OK) {
            printf("Failed to open rec.wav file for playback: %d\n", res);
            return;
        }
	playback_file_size = f_size(&playback_file);
        
        // 验证WAV文件头
        wav_header_t header;
        UINT bytes_read;
        res = f_read(&playback_file, &header, sizeof(header), &bytes_read);
        if (res != FR_OK || bytes_read != sizeof(header) ||
            memcmp(header.chunk_id, "RIFF", 4) != 0 ||
            memcmp(header.format, "WAVE", 4) != 0 ||
            memcmp(header.subchunk1_id, "fmt ", 4) != 0 ||
            memcmp(header.subchunk2_id, "data", 4) != 0) {
            printf("Invalid WAV file format\n");
            f_close(&playback_file);
            return;
        }
        
        // 计算音频数据起始位置和大小
        uint32_t audio_data_start = sizeof(wav_header_t);
        uint32_t audio_data_size = header.subchunk2_size;
        
        if (audio_data_start + audio_data_size > playback_file_size) {
            printf("WAV data size exceeds file size\n");
            f_close(&playback_file);
            return;
        }
        
        // 定位到音频数据开始处
        f_lseek(&playback_file, audio_data_start);
        playback_file_size = audio_data_size; // 用于进度条计算的实际音频数据大小
        playback_position = 0;
#endif        
        // 重置进度条
        ProgressBarView_main->setProgress(0);

#ifdef DUMP_PCM_FOR_DEBUG
        // 打开PCM转储文件（播放解码后的PCM）
        res = f_open(&dump_pcm_playback_file, "0:/play_dump.pcm", FA_WRITE | FA_CREATE_ALWAYS);
        if (res != FR_OK) {
            printf("Failed to open play_dump.pcm file: %d\n", res);
        }
#endif
        
        // 启动音频播放
        if (audio_service) {
            audio_service->play_start();
        }

        is_playing = true;
        printf("Start playback...\n");
        
    } else {
        // 停止播放
        printf("Stop playback...\n");
        is_playing = false;
        
        // 等待播放线程结束
        while (playback_status) {
            goldie_msleep(100);
        }
        
        // 停止音频播放
        if (audio_service) {
            audio_service->play_stop();
        }
        
        
        // 关闭文件
        if (playback_file.fs) {
            f_close(&playback_file);
            memset(&playback_file, 0, sizeof(FIL));
        }

#ifdef DUMP_PCM_FOR_DEBUG
        if (dump_pcm_playback_file.fs) {
            f_close(&dump_pcm_playback_file);
            memset(&dump_pcm_playback_file, 0, sizeof(FIL));
        }
#endif
        
        playback_file_size = 0;
        playback_position = 0;
    }
}


// 录音数据处理线程（修改版）
static int recording_thread(void *arg) {
    short* audio_buffer = (short*)goldie_malloc(RECORD_BUFFER_SIZE);
    short* mono_buffer = audio_buffer;  // 复用缓冲区
#ifdef USE_OPUS_CODEC
    uint8_t* codec2_buffer = (uint8_t*)goldie_malloc(CODEC2_BUFFER_SIZE);
#endif	
    while (running_flag) {
        if (is_recording) {
            record_status = 1;
            if (!audio_service) { goldie_msleep(10); continue; }
            int read_len = audio_service->audio_read(audio_buffer, RECORD_BUFFER_SIZE);
            if (read_len > 0) {
                int sample_count = read_len / sizeof(short);
                int mono_samples = sample_count / 2;  // 双通道转单通道
                for (int i = 0; i < mono_samples; i++) {
                    mono_buffer[i] = audio_buffer[i * 2];
                }
                printf("read_len is %d \r\n",read_len);

#ifdef DUMP_PCM_FOR_DEBUG
                // 将单声道PCM数据写入转储文件（用于调试）
                if (dump_pcm_record_file.fs) {
                    UINT bytes_written_dump;
                    FRESULT res_dump = f_write(&dump_pcm_record_file, mono_buffer, mono_samples * sizeof(short), &bytes_written_dump);
                    if (res_dump != FR_OK) {
                        printf("Failed to write to rec_dump.pcm: %d\n", res_dump);
                    }
                }
#endif
#ifdef USE_OPUS_CODEC
                // 处理所有完整的帧（可能一次 encode_buffer 消耗多帧）
                int processed = 0;
                int16_t samples_cost = 0;
                while (processed < mono_samples) {
                    int encode_len = encode_buffer(enc, 
                                                   &mono_buffer[processed], 
                                                   mono_samples - processed,
                                                   codec2_buffer, 
                                                   &samples_cost);
                    if (encode_len <= 0 || samples_cost == 0) {
                        printf("encode_buffer error %d \r\n",mono_samples - processed);
                        break;  // 编码失败或没有足够的样本
                    }
                    printf("encode_len %d samples_cost %d \r\n",encode_len,samples_cost);
                    UINT bytes_written;
                    FRESULT res = f_write(&record_file, codec2_buffer, encode_len, &bytes_written);
                    if (res != FR_OK) {
                        printf("Failed to write to file: %d\n", res);
                        break;
                    }
                    total_audio_data_size += bytes_written;
                    processed += samples_cost;
                }
                goldie_msleep(30);
            } else {
                goldie_msleep(30);
            }
        } else {
            record_status = 0;
            goldie_msleep(30);
        }
    }
#else
                // 直接写入PCM音频数据到WAV文件（无需编解码）
                UINT bytes_written;
                FRESULT res = f_write(&record_file, mono_buffer, mono_samples * sizeof(short), &bytes_written);
                if (res != FR_OK) {
                    printf("Failed to write to file: %d\n", res);
                    break;
                }
                total_audio_data_size += bytes_written;
                goldie_msleep(30);
            } else {
                goldie_msleep(30);
            }
        } else {
            record_status = 0;
            goldie_msleep(30);
        }
    }
#endif
    goldie_free(audio_buffer);
#ifdef USE_OPUS_CODEC	
    goldie_free(codec2_buffer);
#endif	
    record_thread_exit_flag =1;	
    return 0;
}


#define MIN_DATA_SIZE  512 

// 播放数据处理线程（修改版，按数据包解码）
static int playback_thread(void *arg) {
    short* audio_buffer = (short*)goldie_malloc(PLAYBACK_BUFFER_SIZE);
#ifdef USE_OPUS_CODEC	
    uint8_t* file_buffer = (uint8_t*)goldie_malloc(4096); // 文件数据缓冲区
    uint32_t file_buf_len = 0;   // 缓冲区中有效数据长度
    uint32_t file_buf_pos = 0;   // 缓冲区中当前读取位置

    while (running_flag) {
        if (is_playing) {
            playback_status = 1;
            if (file_buf_len < MIN_DATA_SIZE) {
                memmove(file_buffer, file_buffer + file_buf_pos, file_buf_len);
                file_buf_pos = 0;

                // 读取尽可能多的数据
                uint32_t free_space = 4096 - file_buf_len;
	       free_space = (free_space/512)*512;
                if (free_space > 0) {
                    UINT bytes_read;
                    FRESULT res = f_read(&playback_file, file_buffer + file_buf_len, free_space, &bytes_read);
                    if (res == FR_OK && bytes_read > 0) {
                        file_buf_len += bytes_read;
                    } else if (res != FR_OK) {
			// 播放完成
			is_playing = false;
			playback_status = 0;
			audio_service->play_stop();
			f_close(&playback_file);
			memset(&playback_file, 0, sizeof(FIL));
			playback_file_size = 0;
			playback_position = 0;
			ProgressBarView_main->setProgress(100);
                    }
                }
            }
 	  int16_t cost;  // 解码消耗的字节数（应等于 4+data_len）
	  int samples = decode_buffer(dec, file_buffer + file_buf_pos,file_buf_len,audio_buffer,&cost);
	 if(samples>0){
	 	printf("samples is %d cost %d \r\n",samples,cost);
		file_buf_len -=cost;
		file_buf_pos +=cost;
		audio_service->audio_write(audio_buffer, samples * sizeof(int16_t));		
#else
    /* 已移除 file_buffer 和 codec2 相关变量 */
    
    while (running_flag) {
        if (is_playing) {
            playback_status = 1;
            
            // 直接读取PCM数据
            UINT bytes_read;
            FRESULT res = f_read(&playback_file, audio_buffer, PLAYBACK_BUFFER_SIZE, &bytes_read);
            
            if (res == FR_OK && bytes_read > 0) {
                // 播放音频数据
                if (audio_service) audio_service->audio_write(audio_buffer, bytes_read);
#endif
#ifdef DUMP_PCM_FOR_DEBUG
                // 将解码后的PCM数据写入转储文件（用于调试）
                if (dump_pcm_playback_file.fs) {
                    UINT bytes_written_dump;
					#ifdef USE_OPUS_CODEC
                    FRESULT res_dump = f_write(&dump_pcm_playback_file, audio_buffer, samples * sizeof(int16_t), &bytes_written_dump);
                    #else
					FRESULT res_dump = f_write(&dump_pcm_playback_file, audio_buffer, bytes_read, &bytes_written_dump);
					#endif
					if (res_dump != FR_OK) {
                        printf("Failed to write to play_dump.pcm: %d\n", res_dump);
                    }
                }
#endif
#ifdef USE_OPUS_CODEC
		playback_position += cost;
#else
		playback_position += bytes_read;
#endif		
		// 更新进度条
		if (playback_file_size > 0) {
			int progress = (int)((float)playback_position / playback_file_size * 100);
			if (progress > 100) progress = 100;
			ProgressBarView_main->setProgress(progress);
			}
#ifdef USE_OPUS_CODEC								
	  	}
		else{
		 if (playback_position >= playback_file_size) {
#else
		if (bytes_read < PLAYBACK_BUFFER_SIZE) {
#endif
	 
#ifdef DUMP_PCM_FOR_DEBUG
        if (dump_pcm_playback_file.fs) {
            f_close(&dump_pcm_playback_file);
            memset(&dump_pcm_playback_file, 0, sizeof(FIL));
        }
#endif            
                    // 播放完成
                    is_playing = false;
                    playback_status = 0;
                    audio_service->play_stop();
                    f_close(&playback_file);
                    memset(&playback_file, 0, sizeof(FIL));
                    playback_file_size = 0;
                    playback_position = 0;
                    ProgressBarView_main->setProgress(100);
                    printf("Playback completed\n");
#ifdef USE_OPUS_CODEC
                } else {
                    printf("decode error \r\n");
                    goldie_msleep(10);
                }
#else
                }
                
            } else {
                // 文件读取错误或结束
#ifdef DUMP_PCM_FOR_DEBUG
                if (dump_pcm_playback_file.fs) {
                    f_close(&dump_pcm_playback_file);
                    memset(&dump_pcm_playback_file, 0, sizeof(FIL));
                }
#endif            
                // 播放完成
                is_playing = false;
                playback_status = 0;
                audio_service->play_stop();
                f_close(&playback_file);
                memset(&playback_file, 0, sizeof(FIL));
                playback_file_size = 0;
                playback_position = 0;
                ProgressBarView_main->setProgress(100);
                printf("Playback completed or error\n");
#endif				
	  }
	 goldie_msleep(30);
        } else {
            playback_status = 0;
            goldie_msleep(50);
        }
    }

cleanup:
    goldie_free(audio_buffer);
#ifdef USE_OPUS_CODEC	
    goldie_free(file_buffer);
#endif	
    play_thread_exit_flag =1;	
    return 0;
}

static void *recording_task_handle = NULL;
static void *playback_task_handle = NULL;

static void goldie_touch_event(int pressure, int x, int y) {
    Window_1771586894951->handleEvent(pressure, x, y);
}

static void goldie_app_run(void) {
    // 获取服务
    audio_service = (AudioService*)wait_service(AUDIO_SERVICE_INDEX);
    sdcard_service = (SdCardService*)wait_service(SDCARD_SERVICE_INDEX);
    maualgo_service = (AualgoService*)get_service(AUALGO_SERVICE_INDEX);
    if (maualgo_service) maualgo_service->puase();
    // 初始化UI
    main_ui_init();
#ifdef USE_OPUS_CODEC	
    dec = decoder_init();
    enc = encoder_init();
#endif	
    // 设置按钮点击回调
    Button_record->setOnClick(on_record_button_click);
    ButtonView_play->setOnClick(on_play_button_click);
    
	running_flag = 1;
	record_thread_exit_flag = 0;
	play_thread_exit_flag = 0;

    // 创建录音数据处理线程
    recording_task_handle = goldie_thread_create(recording_thread, NULL, "recording_thread", 0x1000);
    if (recording_task_handle) {
        goldie_thread_set_priority(recording_task_handle, 20);
    }
    
    // 创建播放数据处理线程
    playback_task_handle = goldie_thread_create(playback_thread, NULL, "playback_thread", 0x1000);
    if (playback_task_handle) {
        goldie_thread_set_priority(playback_task_handle, 20);
    }
}

static void goldie_app_exit(void) {
    running_flag = 0;
    
    // 停止播放（如果正在播放）
    if (is_playing) {
        is_playing = false;
        
        // 等待播放线程结束
        while (playback_status) {
            goldie_msleep(100);
        }
        
        // 停止音频播放
        if (audio_service) {
            audio_service->play_stop();
        }
       
        
        // 关闭文件
        if (playback_file.fs) {
            f_close(&playback_file);
            memset(&playback_file, 0, sizeof(FIL));
        }

#ifdef DUMP_PCM_FOR_DEBUG
        if (dump_pcm_playback_file.fs) {
            f_close(&dump_pcm_playback_file);
            memset(&dump_pcm_playback_file, 0, sizeof(FIL));
        }
#endif
        
        playback_file_size = 0;
        playback_position = 0;
    }
    
    // 停止录音（如果正在录音）
    if (is_recording) {
        is_recording = false;

        // 等待录音线程自然结束（通过检查 is_recording 标志）
        // 线程会在下一次循环检查时自动退出
        // 停止录音服务
        if (audio_service) {
            audio_service->record_stop();
        }

        printf("bf Stop recording...\n");
        is_recording = false;
        while (record_status) {
            goldie_msleep(100);
        }
        printf("af Stop recording...\n");

        // 关闭文件
        if (record_file.fs) {
            f_close(&record_file);
            memset(&record_file, 0, sizeof(FIL));
        }

#ifdef DUMP_PCM_FOR_DEBUG
        if (dump_pcm_record_file.fs) {
            f_close(&dump_pcm_record_file);
            memset(&dump_pcm_record_file, 0, sizeof(FIL));
        }
#endif
    }

    while(!play_thread_exit_flag)
    {
	goldie_msleep(100); 
    }

    while(!record_thread_exit_flag)
    {
	goldie_msleep(100); 
    }
#ifdef USE_OPUS_CODEC
    encoder_destroy(enc);
    decoder_destroy(dec);
#endif	
    // 给线程一点时间退出
    goldie_thread_destroy(recording_task_handle);
    goldie_thread_destroy(playback_task_handle);
    window_exit();
    if (maualgo_service) maualgo_service->run();
}

static void goldie_app_suspend(void) {
    is_recording = false;
    is_playing = false;
    window_suspend();
}

static void goldie_app_resume(void) {
    window_resume();
}

static void goldie_keyboard_event(int pressure, int key);

static App_t recorder = {
    "录音", // app_name char*
    goldie_app_run, // h_app_run
    goldie_app_exit, // h_app_exit
    goldie_app_suspend, // h_app_suspend
    goldie_app_resume, // h_app_resume
    goldie_touch_event, // h_touch_event
    goldie_keyboard_event, // h_keyboard_event
    (uint16_t*)rgb16_record_icon_56_56,
};

static void goldie_keyboard_event(int pressure, int key) {
    if ((key == SYSTEM_KEY_VALUE_BACK) && (pressure == 1)) {
        goldie_exit_app(&recorder);
    }
}

static void test_entry(void) {
    install_app(&recorder);
}

GOLDIE_INIT_CALL_(test_entry);
