/*This file is automatically generated by the tinyui tool and should not be modified.*/
#ifndef INCLUDE_MAIN_UI_H
#define INCLUDE_MAIN_UI_H
#include <memory>
#include <vector>

#include "goldie_display.h" 
// 控件头文件
#include "progressbar_view.h"
#include "button_view.h"
#include "frame_view.h"
#include "window.h"

// 图片头文件
#include "rgb16_play_32_32.h"
#include "rgb16_record_button_dis_104_104.h"
#include "rgb16_record2_320_240.h"
#include "rgb16_record_button_104_104.h"
#include "rgb16_stop_32_32.h"
// 掩码头文件
#include "round_rect_248_21_r4_boundary.h"
#include "ellipse_32_32_boundary.h"
#include "ellipse_104_104_boundary.h"
// 全局控件变量定义
static std::shared_ptr<ProgressBarView> ProgressBarView_main;
static std::shared_ptr<ButtonView> ButtonView_play;
static std::shared_ptr<ButtonView> Button_record;
static std::shared_ptr<FrameView> FrameView_main;
static std::shared_ptr<Window> Window_1771586894951;

static void main_ui_init()
{
    ProgressBarView_main = std::make_shared<ProgressBarView>(248, 21);
    ProgressBarView_main->setColor(0x3F03);
    ProgressBarView_main->setTextColor(0);
    ProgressBarView_main->setBoundaryBuffer(round_rect_248_21_r4_boundary);
    ProgressBarView_main->setVisible(true);

    ButtonView_play = std::make_shared<ButtonView>(32, 32);
    ButtonView_play->setColor(0x3F03);
    ButtonView_play->setTextColor(0);
    ButtonView_play->setBoundaryBuffer(ellipse_32_32_boundary);
    ButtonView_play->setVisible(true);
    ButtonView_play->setImageBuffer((uint16_t*)&rgb16_play_32_32);

    Button_record = std::make_shared<ButtonView>(104, 104);
    Button_record->setColor(0x3F03);
    Button_record->setTextColor(0);
    Button_record->setBoundaryBuffer(ellipse_104_104_boundary);
    Button_record->setVisible(true);
    Button_record->setImageBuffer((uint16_t*)&rgb16_record_button_dis_104_104);

    FrameView_main = std::make_shared<FrameView>(320, 240);
    FrameView_main->setColor(0x59CE);
    FrameView_main->setTextColor(0);
    FrameView_main->setVisible(true);
    FrameView_main->setImageBuffer((uint16_t*)&rgb16_record2_320_240);

    Window_1771586894951 = std::make_shared<Window>(APP_WINDOW_START_X, APP_WINDOW_START_Y,320, 240);
    Window_1771586894951->setColor(0x8631);
    Window_1771586894951->setTextColor(1);
    Window_1771586894951->setVisible(true);

    // 建立控件父子关系
    FrameView_main->addView(Button_record, 104, 51);
    FrameView_main->addView(ButtonView_play, 16, 200);
    FrameView_main->addView(ProgressBarView_main, 56, 207);
    Window_1771586894951->addView(FrameView_main, 0, 0);

    // 刷新窗口
    Window_1771586894951->flush(0, 0, APP_WINDOW_WIDTH, APP_WINDOW_HEIGHT);
}

static void window_exit(void)
{
    Window_1771586894951->setVisible(false);
    Window_1771586894951->removeAllViews();
	
    FrameView_main->removeAllChilds();

    ProgressBarView_main.reset();
    ButtonView_play.reset();
    Button_record.reset();
    FrameView_main.reset();
    Window_1771586894951.reset();
}

static void window_suspend(void)
{
    Window_1771586894951->setVisible(false);
}

static void window_resume(void)
{
    Window_1771586894951->setVisible(true);
    Window_1771586894951->flush(0, 0, APP_WINDOW_WIDTH, APP_WINDOW_HEIGHT);
}

#endif //INCLUDE_MAIN_UI_H 

