/*This file is automatically generated by the tinyui tool and should not be modified.*/
#ifndef INCLUDE_MAIN_UI_H
#define INCLUDE_MAIN_UI_H
#include <memory>
#include <vector>

#include "goldie_display.h" 
// 控件头文件
#include "button_view.h"
#include "label_view.h"
#include "frame_view.h"
#include "list_view.h"
#include "window.h"

// 图片头文件
#include "rgb16_next_56_56.h"
#include "rgb16_back3_48_24.h"
#include "rgb16_start_64_61.h"
#include "rgb16_list_24_21.h"
#include "rgb16_previous_56_56.h"

// 掩码头文件
#include "ellipse_56_56_boundary.h"
#include "ellipse_64_61_boundary.h"
#include "round_rect_24_21_r1_boundary.h"
#include "round_rect_248_26_r5_boundary.h"
#include "round_rect_240_24_r1_boundary.h"
#include "ellipse_56_56_boundary.h"
#include "round_rect_320_236_r1_boundary.h"
#include "round_rect_256_32_r5_boundary.h"
#include "round_rect_320_233_r2_boundary.h"
// 全局控件变量定义
static std::shared_ptr<ButtonView> ButtonView_next;
static std::shared_ptr<ButtonView> ButtonView_back;
static std::shared_ptr<LabelView> LabelView_name1;
static std::shared_ptr<ButtonView> ButtonView_play;
static std::shared_ptr<LabelView> LabelView_list2;
static std::shared_ptr<ButtonView> ButtonView_list;
static std::shared_ptr<LabelView> LabelView_show;
static std::shared_ptr<ButtonView> ButtonView_last;
static std::shared_ptr<FrameView> FrameView_2;
static std::shared_ptr<ButtonView> ButtonView_exit;
static std::shared_ptr<ListView> ListView_storylist;
static std::shared_ptr<LabelView> LabelView_name;
static std::shared_ptr<FrameView> FrameView_1;
static std::shared_ptr<Window> Window_1770011958560;

static void main_ui_init()
{
    ButtonView_next = std::make_shared<ButtonView>(56, 56);
    ButtonView_next->setColor(0xFFFF);
    ButtonView_next->setTextColor(0);
    ButtonView_next->setBoundaryBuffer(ellipse_56_56_boundary);
    ButtonView_next->setVisible(true);
    ButtonView_next->setImageBuffer((uint16_t*)&rgb16_next_56_56);

    ButtonView_back = std::make_shared<ButtonView>(48, 24);
    ButtonView_back->setColor(0x0000);
    ButtonView_back->setTextColor(0);
    ButtonView_back->setVisible(true);
    ButtonView_back->setImageBuffer((uint16_t*)&rgb16_back3_48_24);

    LabelView_name1 = std::make_shared<LabelView>(256, 32);
    LabelView_name1->setColor(0x0000);
    LabelView_name1->setTextColor(1);
    LabelView_name1->setText("故事机");
    LabelView_name1->setBoundaryBuffer(round_rect_256_32_r5_boundary);
    LabelView_name1->setVisible(true);

    ButtonView_play = std::make_shared<ButtonView>(64, 61);
    ButtonView_play->setColor(0xFFFF);
    ButtonView_play->setTextColor(0);
    ButtonView_play->setBoundaryBuffer(ellipse_64_61_boundary);
    ButtonView_play->setVisible(true);
    ButtonView_play->setImageBuffer((uint16_t*)&rgb16_start_64_61);

    LabelView_list2 = std::make_shared<LabelView>(24, 21);
    LabelView_list2->setColor(0xFFFF);
    LabelView_list2->setTextColor(0);
    LabelView_list2->setBoundaryBuffer(round_rect_24_21_r1_boundary);
    LabelView_list2->setVisible(true);
    LabelView_list2->setImageBuffer((uint16_t*)&rgb16_list_24_21);

    ButtonView_list = std::make_shared<ButtonView>(248, 26);
    ButtonView_list->setColor(0xBEF7);
    ButtonView_list->setTextColor(0);
    ButtonView_list->setText("故事列表",109,8);
    ButtonView_list->setBoundaryBuffer(round_rect_248_26_r5_boundary);
    ButtonView_list->setVisible(true);

    LabelView_show = std::make_shared<LabelView>(240, 24);
    LabelView_show->setColor(0xFFFF);
    LabelView_show->setTextColor(0);
    LabelView_show->setText("读取中...");
    LabelView_show->setBoundaryBuffer(round_rect_240_24_r1_boundary);
    LabelView_show->setVisible(true);

    ButtonView_last = std::make_shared<ButtonView>(56, 56);
    ButtonView_last->setColor(0xFFFF);
    ButtonView_last->setTextColor(0);
    ButtonView_last->setBoundaryBuffer(ellipse_56_56_boundary);
    ButtonView_last->setVisible(true);
    ButtonView_last->setImageBuffer((uint16_t*)&rgb16_previous_56_56);

    FrameView_2 = std::make_shared<FrameView>(320, 236);
    FrameView_2->setColor(0xFFFF);
    FrameView_2->setTextColor(0);
    FrameView_2->setBoundaryBuffer(round_rect_320_236_r1_boundary);
    FrameView_2->setVisible(true);

    ButtonView_exit = std::make_shared<ButtonView>(48, 24);
    ButtonView_exit->setColor(0x3F03);
    ButtonView_exit->setTextColor(0);
    ButtonView_exit->setVisible(true);
    ButtonView_exit->setImageBuffer((uint16_t*)&rgb16_back3_48_24);

    ListView_storylist = std::make_shared<ListView>(256, 172);
    ListView_storylist->setColor(0xFFFF);
    ListView_storylist->setTextColor(0);
    ListView_storylist->setVisible(true);
    ListView_storylist->addItem("story1", 0);
    ListView_storylist->addItem("story2", 1);
    ListView_storylist->addItem("story3", 2);
    ListView_storylist->addItem("story4", 3);
    ListView_storylist->addItem("story5", 4);

    LabelView_name = std::make_shared<LabelView>(256, 32);
    LabelView_name->setColor(0x0000);
    LabelView_name->setTextColor(1);
    LabelView_name->setText("故事列表");
    LabelView_name->setBoundaryBuffer(round_rect_256_32_r5_boundary);
    LabelView_name->setVisible(true);

    FrameView_1 = std::make_shared<FrameView>(320, 233);
    FrameView_1->setColor(0xFFFF);
    FrameView_1->setTextColor(0);
    FrameView_1->setBoundaryBuffer(round_rect_320_233_r2_boundary);
    FrameView_1->setVisible(false);

    Window_1770011958560 = std::make_shared<Window>(APP_WINDOW_START_X, APP_WINDOW_START_Y,320, 240);
    Window_1770011958560->setColor(0x0000);
    Window_1770011958560->setTextColor(0);
    Window_1770011958560->setVisible(true);

    // 建立控件父子关系
    FrameView_2->addView(ButtonView_last, 60.0, 108.0);//
    FrameView_2->addView(ButtonView_list, 32.0, 194.0);
    FrameView_2->addView(LabelView_list2, 104.0, 198.0);
    FrameView_2->addView(ButtonView_play, 132.0, 103.0);//
    FrameView_2->addView(LabelView_name1, 32, 12);
    FrameView_2->addView(ButtonView_back, 40, 15);
    FrameView_2->addView(ButtonView_next, 212.0, 108);//
    FrameView_2->addView(LabelView_show, 46.0, 68.0);//
    Window_1770011958560->addView(FrameView_1, 0, 0);
    Window_1770011958560->addView(FrameView_2, 0, 0);
    FrameView_1->addView(LabelView_name, 32.0, 12);
    FrameView_1->addView(ListView_storylist, 32.0, 46.0);
    FrameView_1->addView(ButtonView_exit, 40.0, 15);

    // 刷新窗口
    Window_1770011958560->flush(0, 0, APP_WINDOW_WIDTH, APP_WINDOW_HEIGHT);
}

static void window_exit(void)
{
    Window_1770011958560->setVisible(false);
    Window_1770011958560->removeAllViews();
    FrameView_2->removeAllChilds();
    ListView_storylist->clearItems();
    FrameView_1->removeAllChilds();

    ButtonView_next.reset();
    ButtonView_back.reset();
    LabelView_name1.reset();
    ButtonView_play.reset();
    LabelView_list2.reset();
    ButtonView_list.reset();
    LabelView_show.reset();
    ButtonView_last.reset();
    ButtonView_exit.reset();
    ListView_storylist.reset();
    LabelView_name.reset();
    FrameView_2.reset();
    FrameView_1.reset();
    Window_1770011958560.reset();
}

static void window_suspend(void)
{
    Window_1770011958560->setVisible(false);
}

static void window_resume(void)
{
    Window_1770011958560->setVisible(true);
    Window_1770011958560->flush(0, 0, APP_WINDOW_WIDTH, APP_WINDOW_HEIGHT);
}

#endif //INCLUDE_MAIN_UI_H 

