/*This file is automatically generated by the tinyui tool 
and contains the main_ui. h file, which calls the initialization 
function main_ui_init() to create the UI interface. You need to 
add code related to business logic here..*/
#include "main_ui.h"
#include "default_app_icon.h" 
extern "C" { 
#include "goldie_osal.h" 
#include "service_manager.h" 
#include "app_manager.h" 
#include "mp3_player.h"
#include "../settings/assets/rgb16_selected_32_32.h"
#include <string>
#include <vector>
#include <cstring>
} 
#include "app_icon.h"
#include "rgb16_stop_64_61.h"//暂停播放图标
#include "rgb16_start_64_61.h"//播放图标
static int codec_init_flag = 0;//初始化标志

#ifdef PLATFORM_TYPE_WS63
static AualgoService* maualgo_service;
#endif


// 播放状态
static bool is_playing = false;

// static const char** story_names = nullptr;//故事名称列表
// static int story_num = 0;//故事数量        
int story_index;//故事索引
static void on_exit_click(void*);//函数声明-退出键处理

// 更新播放按钮图标
static void update_play_button_image() {
    if (is_playing) {
        // 播放中：显示停止图标（按下按钮将停止）
        ButtonView_play->setImageBuffer((uint16_t*)&rgb16_stop_64_61);
    } else {
        // 停止中：显示播放图标（按下按钮将播放）
        ButtonView_play->setImageBuffer((uint16_t*)&rgb16_start_64_61);
    }
    ButtonView_play->flush(0, 0, 32, 32);
}

static int gbk_to_utf8(const char* gbk, char* utf8, size_t utf8_size) {
    size_t out_len = 0;
    const unsigned char* p = (const unsigned char*)gbk;
    
    while (*p) {
        uint16_t uni;
        uint16_t gbk_char;
        
        // 判断是否为双字节 GBK 字符（首字节范围 0x81-0xFE）
        if (*p >= 0x81 && *p <= 0xFE && *(p+1) >= 0x40 && *(p+1) <= 0xFE && *(p+1) != 0x7F) {
            // 双字节 GBK
            gbk_char = (uint16_t)((*p << 8) | *(p+1));
            p += 2;
        } else {
            // 单字节 ASCII
            gbk_char = *p++;
        }
        
        // 使用 FatFs 的 ff_convert 将 GBK 转换为 Unicode（UTF-16）
        // 注意：ff_convert 的第一个参数是字符编码，第二个参数为 1 表示转换为 Unicode
        uni = ff_convert(gbk_char, 1);  // 返回 Unicode 码点
        
        if (uni == 0) {
            // 转换失败，用 '?' 代替
            uni = '?';
        }
        
        // 将 Unicode 码点编码为 UTF-8
        if (uni <= 0x7F) {
            if (utf8 && out_len + 1 < utf8_size) utf8[out_len] = (char)uni;
            out_len += 1;
        } else if (uni <= 0x7FF) {
            if (utf8 && out_len + 2 < utf8_size) {
                utf8[out_len]     = (char)(0xC0 | ((uni >> 6) & 0x1F));
                utf8[out_len + 1] = (char)(0x80 | (uni & 0x3F));
            }
            out_len += 2;
        } else {
            if (utf8 && out_len + 3 < utf8_size) {
                utf8[out_len]     = (char)(0xE0 | ((uni >> 12) & 0x0F));
                utf8[out_len + 1] = (char)(0x80 | ((uni >> 6) & 0x3F));
                utf8[out_len + 2] = (char)(0x80 | (uni & 0x3F));
            }
            out_len += 3;
        }
    }
    
    if (utf8 && out_len + 1 <= utf8_size) {
        utf8[out_len] = '\0';
        return (int)out_len;
    } else if (utf8 && out_len + 1 > utf8_size) {
        return -1;  // 缓冲区不足
    }
    return (int)out_len;  // 仅计算长度
}


static void remove_mp3_extension(const char *file_name, char *short_name, size_t buf_size) {
    const char *ext = strstr(file_name, ".mp3");
    size_t len;

    if (ext != NULL) {
        len = ext - file_name;
    } else {
        len = strlen(file_name); 
    }

    
    if (len >= buf_size) {
        len = buf_size - 1;
    }

    strncpy(short_name, file_name, len);
    short_name[len] = '\0';
}

static void update_display_label() {
    char file_name[64];  
    char display_text[100] ={0};

    player_state_t state = audio_player_get_state();
    int current_track = audio_player_get_current_track();
    int playlist_size = audio_player_get_playlist_size();
    if (state == PLAYER_STATE_PLAYING) {
        is_playing = true;
    } else {
        is_playing = false;
    }

    if (playlist_size == 0) {
      	LabelView_show->setText("无音频文件");
	    LabelView_show->flush(0, 0, 240, 24);
    } else {
        // 获取存储的 gtk 完整路径（注意强制转换）
        const char* full_path = audio_player_get_track_name(current_track);
        
        // 找到最后一个 '/' 的字符
        const char* last_slash = NULL;
        const char* p = full_path;
        while (*p) {
            if (*p == '/') {   //
                last_slash = p;
            }
            p++;
        }
        // 文件名部分起始指针：如果找到斜杠，则为 last_slash+1；否则从头开始
        const char* filename_gtk = (last_slash != NULL) ? (last_slash + 1) : full_path;
        // 将文件名部分转换为 UTF-8
        int name_len = gbk_to_utf8((char*)filename_gtk, file_name, sizeof(file_name) - 1);
        if (name_len < 0) {
            // 转换失败，回退
            strcpy(file_name, "未知");
        } else {
            file_name[name_len] = '\0';  // 确保结尾
        }

        // 打印调试数据（可选）
        printf("UTF-8 filename bytes: ");
        for (int i = 0; i < name_len; i++) {
            printf("0x%02x ", (unsigned char)file_name[i]);
        }
        printf("\n");
        memset(display_text,0,100);
        remove_mp3_extension(file_name,display_text,100);//去除.mp3后缀
	    LabelView_show->setText(display_text);
	    LabelView_show->flush(0, 0, 240, 24);
    }

}

// 播放/停止按钮点击处理
static void on_play_stop_click(void*) {
    if (!codec_init_flag) {
        return;
    }
    player_state_t state = audio_player_get_state();
    if (state == PLAYER_STATE_PLAYING) {
        // 当前正在播放，点击停止
        audio_player_stop();
        is_playing = false;
    } else {
        // 当前停止，点击播放
        if (audio_player_play() == 0) {
            is_playing = true;
        }
    }

    update_play_button_image();
    update_display_label();
}

// 下一首按钮点击处理
static void on_next_click(void*) {
    if (!codec_init_flag) {
        return;
    }
    audio_player_play_next();
    story_index+=1;
    story_index = audio_player_get_current_track();
    ListView_storylist->setSelected(story_index);
    is_playing = true; // 上一首会自动开始播放
    update_display_label();
    update_play_button_image();
}


// 上一首按钮点击处理
static void on_prev_click(void*) {
    if (!codec_init_flag) {
        return;
    }
    audio_player_play_prev();
    story_index = audio_player_get_current_track();
    ListView_storylist->setSelected(story_index);
    is_playing = true; // 上一首会自动开始播放
    update_display_label();
    update_play_button_image();
}

// 返回播放界面
static void on_back_click(void*) {
    if (!codec_init_flag) {
        return;
    }
    FrameView_2->setVisible(true);
    FrameView_1->setVisible(false);
}

//打开故事列表
static void on_back_list_click(void*) {
    if (!codec_init_flag) {
        return;
    }
    FrameView_1->setVisible(true);
    FrameView_2->setVisible(false);
}



// 故事列表项点击的独立回调
static void on_storylist_item_click(int itemId) {
    if (!codec_init_flag || audio_player_get_playlist_size() == 0) {
        return;
    }
    FrameView_1->setVisible(false);  // 隐藏列表页
    FrameView_2->setVisible(true);   // 显示播放页
     // 切换播放器到指定track
    audio_player_play_track(itemId);
    story_index = itemId; // 同步本地索引
    ListView_storylist->setSelected(story_index);
    is_playing = true;
    // 更新UI显示
    update_display_label();
    update_play_button_image();
    Window_1770011958560->flush(0, 0, APP_WINDOW_WIDTH, APP_WINDOW_HEIGHT);
}


//初始化界面
static void init_views() {
    FrameView_2->setVisible(true);
    FrameView_1->setVisible(false);
    ButtonView_next->setOnClick(on_next_click);//下一个
    ButtonView_last->setOnClick(on_prev_click);//上一个
    ButtonView_play->setOnClick(on_play_stop_click);//播放/停止
    ButtonView_back->setOnClick(on_exit_click);//退出应用键
    ButtonView_list->setOnClick(on_back_list_click);//故事列表键
    ButtonView_exit->setOnClick(on_back_click);//返回列表
    ListView_storylist->setOnItemClick(on_storylist_item_click);//故事列表点击
}


static void goldie_touch_event(int pressure, int x, int y)
{
    Window_1770011958560->handleEvent(pressure, x, y);
}

static void goldie_app_run(void)
{
    char file_name[64];
    char short_name[100] = {0};
    main_ui_init();
    init_views();
#ifdef PLATFORM_TYPE_WS63
    maualgo_service = (AualgoService*)wait_service(AUALGO_SERVICE_INDEX);
    maualgo_service->puase();
#endif
    is_playing = false;
    // 初始化音频播放器
    if (audio_player_init() != 0) {
        printf("Audio player initialization failed\n");
    } else {
        // 设置循环模式
        audio_player_set_loop(1);
        // 初始化显示
        update_display_label();
        update_play_button_image();
        codec_init_flag = 1;

        
        int playlist_size = audio_player_get_playlist_size();
        ListView_storylist->clearItems(); // 清空硬编码item
        ListView_storylist->setSelectedIcon((uint16_t*)&rgb16_selected_32_32, 32, 32);
        if (playlist_size > 0) {
            for (int i = 0; i < playlist_size; i++) {
            // 获取存储的 gtk 完整路径（注意强制转换）
                const char* full_path = audio_player_get_track_name(i);
                
                // 找到最后一个 '/' 的字符
                const char* last_slash = NULL;
                const char* p = full_path;
                while (*p) {
                    if (*p == '/') {   //
                        last_slash = p;
                    }
                    p++;
                }
                // 文件名部分起始指针：如果找到斜杠，则为 last_slash+1；否则从头开始
                const char* filename_gtk = (last_slash != NULL) ? (last_slash + 1) : full_path;
                // 将文件名部分转换为 UTF-8
                int name_len = gbk_to_utf8((char*)filename_gtk, file_name, sizeof(file_name) - 1);
                if (name_len < 0) {
                    // 转换失败，回退
                    strcpy(file_name, "未知");
                } else {
                    file_name[name_len] = '\0';  // 确保结尾
                }

                // 打印调试数据（可选）
                printf("UTF-8 filename bytes[%d]: ",name_len);
                for (int i = 0; i < name_len; i++) {
                    printf("0x%02x ", (unsigned char)file_name[i]);
                }
                printf("\n");
	            memset(short_name,0,100);
                remove_mp3_extension(file_name,short_name,100);//去除.mp3后缀
                // 添加到UI列表，itemId与播放器track索引一致
                ListView_storylist->addItem(short_name, i);
            }
            // 初始化当前索引为播放器默认值
            story_index = audio_player_get_current_track();
            ListView_storylist->setSelected(story_index);
            Window_1770011958560->flush(0, 0, APP_WINDOW_WIDTH, APP_WINDOW_HEIGHT);
        }
    } 
}

static void goldie_app_suspend(void)
{
    window_suspend();
}

static void goldie_app_resume(void)
{
    window_resume();
}

static void goldie_app_exit(void)
{
    printf("goldie_app_exit \r\n");
    window_exit();
     // 停止播放并清理资源
    audio_player_stop();
    audio_player_cleanup();
#ifdef PLATFORM_TYPE_WS63
    maualgo_service->run();
#endif
}

static void goldie_keyboard_event(int pressure, int key);

static App_t Story = {
    "故事机",       // app_name char*
    goldie_app_run,       // h_app_run
    goldie_app_exit,      // h_app_exit
    goldie_app_suspend,   // h_app_suspend
    goldie_app_resume,    // h_app_resume
    goldie_touch_event,   // h_touch_event
    goldie_keyboard_event,// h_keyboard_event
    (uint16_t*)rgb16_story_56_56,            
};


// 退出app
static void on_exit_click(void*) {
    goldie_exit_app(&Story);
}



static void goldie_keyboard_event(int pressure, int key)
{
    if((key == SYSTEM_KEY_VALUE_BACK) && (pressure == 1))
    {
        goldie_exit_app(&Story);
    }
}

static void test_entry(void)
{
    install_app(&Story);
}

GOLDIE_INIT_CALL_(test_entry);
