/*This file is automatically generated by the tinyui tool and should not be modified.*/
#ifndef INCLUDE_MAIN_UI_H
#define INCLUDE_MAIN_UI_H
#include <memory>
#include <vector>

#include "goldie_display.h" 
// 控件头文件
#include "imgbutton_view.h"
#include "button_view.h"
#include "label_view.h"
#include "list_view.h"
#include "spinner_view.h"
#include "frame_view.h"
#include "progressbar_view.h"
#include "textedit_view.h"
#include "inputmethod_view.h"
#include "window.h"

// 图片头文件
#include "rgb16_back3_48_24.h"
#include "rgb16_sle_scan_200_32.h"
#include "rgb16_minus_64_43.h"
#include "rgb16_back3_48_24.h"
#include "rgb16_add1_64_41.h"
#include "rgb16_back3_48_24.h"
#include "rgb16_back3_48_24.h"
#include "rgb16_avatar_female_152_136.h"
#include "rgb16_cloud_icon_40_40.h"
#include "rgb16_audio_icon_40_40.h"
#include "rgb16_sle_icon_40_40.h"
#include "rgb16_wifi_icon1_40_40.h"
#include "rgb16_voice_24_24.h"
#include "rgb16_preson_24_24.h"
#include "rgb16_relat_24_24.h"
#include "rgb16_apikey_24_24.h"
#include "rgb16_avat_24_24.h"
#include "rgb16_switch_pressed_56_24.h"
#include "rgb16_switch2_pressed_56_26.h"
#include "rgb16_switch_pressed_56_25.h"
#include "rgb16_switch1_released_56_24.h"
#include "rgb16_switch6_released_56_26.h"
#include "rgb16_switch1_released_56_25.h"
// 对话页动画精灵
#include "rgb16_bowtie_56_53.h"
#include "rgb16_bow_56_53.h"
#include "rgb16_closeeye_l_88_85.h"
#include "rgb16_closeeye_r_88_85.h"
#include "rgb16_closeeye_r1_88_85.h"
#include "rgb16_closeeye_r2_88_85.h"
#include "rgb16_closeeye_r3_88_85.h"
#include "rgb16_eye_88_85.h"
#include "rgb16_half_l_88_85.h"
#include "rgb16_half_r_88_85.h"
#include "rgb16_laugh_l_88_85.h"
#include "rgb16_laugh_r_88_85.h"
#include "rgb16_closeeye_l_new_88_85.h"
#include "rgb16_closeeye_r_new_88_85.h"
#include "rgb16_closeeye_r1_new_88_85.h"
#include "rgb16_closeeye_r2_new_88_85.h"
#include "rgb16_closeeye_r3_new_88_85.h"
#include "rgb16_eye_new_88_85.h"
#include "rgb16_half_l_new_88_85.h"
#include "rgb16_half_r_new_88_85.h"
#include "rgb16_laugh_l_new_88_85.h"
#include "rgb16_laugh_r_new_88_85.h"
#include "rgb16_angry_male_l_88_85.h"
#include "rgb16_angry_male_r1_88_85.h"
#include "rgb16_angry_male_r2_88_85.h"
#include "rgb16_doubt_male_l_88_85.h"
#include "rgb16_doubt_male_r1_88_85.h"
#include "rgb16_doubt_male_r2_88_85.h"
#include "rgb16_sad_male_l_88_85.h"
#include "rgb16_sad_male_r_88_85.h"
#include "rgb16_angry_female_l_88_85.h"
#include "rgb16_angry_female_r1_88_85.h"
#include "rgb16_angry_female_r2_88_85.h"
#include "rgb16_doubt_female_l_88_85.h"
#include "rgb16_doubt_female_r1_88_85.h"
#include "rgb16_doubt_female_r2_88_85.h"
#include "rgb16_sad_female_l_88_85.h"
#include "rgb16_sad_female_r_88_85.h"

// 掩码头文件
#include "round_rect_56_24_r1_boundary.h"
#include "round_rect_240_24_r4_boundary.h"
#include "round_rect_280_114_r1_boundary.h"
#include "round_rect_200_32_r3_boundary.h"
#include "round_rect_200_32_r4_boundary.h"
#include "round_rect_136_24_r3_boundary.h"
#include "round_rect_280_29_r3_boundary.h"
#include "round_rect_64_43_r2_boundary.h"
#include "round_rect_64_41_r2_boundary.h"
#include "round_rect_240_24_r4_boundary.h"
#include "round_rect_80_24_r4_boundary.h"
#include "round_rect_80_24_r4_boundary.h"
#include "round_rect_112_25_r1_boundary.h"
#include "round_rect_224_120_r1_boundary.h"
#include "round_rect_64_16_r1_boundary.h"
#include "round_rect_256_125_r1_boundary.h"
#include "round_rect_240_24_r4_boundary.h"
#include "round_rect_256_40_r3_boundary.h"
#include "round_rect_256_40_r3_boundary.h"
#include "round_rect_256_40_r3_boundary.h"
#include "round_rect_256_40_r3_boundary.h"
#include "round_rect_256_40_r3_boundary.h"
#include "round_rect_240_24_r3_boundary.h"
#include "round_rect_80_24_r3_boundary.h"
#include "round_rect_80_24_r3_boundary.h"
#include "round_rect_80_24_r3_boundary.h"
#include "round_rect_80_24_r3_boundary.h"
#include "round_rect_256_24_r4_boundary.h"
#include "round_rect_184_24_r3_boundary.h"
#include "round_rect_56_24_r4_boundary.h"
#include "round_rect_56_24_r4_boundary.h"
#include "round_rect_160_98_r1_boundary.h"
#include "round_rect_208_143_r1_boundary.h"
#include "round_rect_80_18_r1_boundary.h"
#include "round_rect_152_136_r1_boundary.h"
#include "round_rect_80_24_r3_boundary.h"
#include "round_rect_56_53_r1_boundary.h"
#include "round_rect_88_85_r1_boundary.h"
#include "round_rect_240_16_r1_boundary.h"
// 全局控件变量定义
static std::shared_ptr<ImgButtonView> CheckboxView_sle;
static std::shared_ptr<ButtonView> ButtonView_sle_back;
static std::shared_ptr<LabelView> LabelView_sle_tilte;
static std::shared_ptr<ListView> ListView_sle;
static std::shared_ptr<ButtonView> ButtonView_sle_scan;
static std::shared_ptr<LabelView> LabelView_sle_pcode;
static std::shared_ptr<LabelView> LabelView_sle_local_name;
static std::shared_ptr<SpinnerView> SpinnerView_sle_mode;
static std::shared_ptr<FrameView> FrameView_sle;
static std::shared_ptr<ProgressBarView> ProgressBarView_volume;
static std::shared_ptr<LabelView> LabelView_volume_text;
static std::shared_ptr<ButtonView> ButtonView_volume_back;
static std::shared_ptr<LabelView> LabelView_ptitle_show;
static std::shared_ptr<FrameView> FrameView_volume;
//wifi
static std::shared_ptr<ButtonView> ButtonView_connect;
static std::shared_ptr<ButtonView> ButtonView_cancel;
static std::shared_ptr<TextEditView> TextEditView_wifipasswd;
static std::shared_ptr<FrameView> FrameView_wifipasswd;
//sle
static std::shared_ptr<ButtonView> ButtonView_sle_connect;
static std::shared_ptr<ButtonView> ButtonView_sle_cancel;
static std::shared_ptr<TextEditView> TextEditView_sle_paircode;
static std::shared_ptr<LabelView> LabelView_del_sle_dev;
static std::shared_ptr<FrameView> FrameView_sle_pair;

static std::shared_ptr<LabelView> LabelView_wifi_t1;
static std::shared_ptr<ListView> ListView_wifilist;
static std::shared_ptr<ImgButtonView> CheckboxView_wifisw;
static std::shared_ptr<ButtonView> Button_back0;
static std::shared_ptr<LabelView> LabelView_1766049650411;
static std::shared_ptr<FrameView> FrameView_wifitext;
static std::shared_ptr<FrameView> FrameView_wifi;
static std::shared_ptr<ButtonView> Button_cloud;
static std::shared_ptr<ButtonView> Button_bt;
static std::shared_ptr<ButtonView> Button_sle;
static std::shared_ptr<ButtonView> Button_wifi;
static std::shared_ptr<LabelView> LabelView_1766049869637;
static std::shared_ptr<FrameView> FrameView_0;
static std::shared_ptr<ButtonView> ButtonView_voice;
static std::shared_ptr<ImgButtonView> CheckboxView_cloudsw;
static std::shared_ptr<ButtonView> ButtonView_person;
static std::shared_ptr<ButtonView> ButtonView_relat;
static std::shared_ptr<ButtonView> ButtonView_apikey;
static std::shared_ptr<ButtonView> ButtonView_cloudback;
static std::shared_ptr<LabelView> LabelView_cloudtitle;
static std::shared_ptr<TextEditView> TextEditView_apikey;
static std::shared_ptr<ButtonView> ButtonView_cancle17;
static std::shared_ptr<LabelView> LabelView_cfgtitle0;
static std::shared_ptr<ButtonView> ButtonView_yes17;
static std::shared_ptr<ListView> ListView_cfgwmlist;
static std::shared_ptr<FrameView> FrameView_config_wm;
static std::shared_ptr<LabelView> LabelView_avashow0;
static std::shared_ptr<LabelView> LabelView_pic;
static std::shared_ptr<ButtonView> ButtonView_ava;
static std::shared_ptr<LabelView> LabelView_status_conn;
static std::shared_ptr<LabelView> LabelView_status_conv;
static std::shared_ptr<ButtonView> ButtonView_enter_talk;  /* 进入对话按钮，引擎运行时可见 */
static std::shared_ptr<FrameView> FrameView_cloud;
static std::shared_ptr<InputMethodView> InputMethodView_0;
// 对话页控件
static std::shared_ptr<FrameView> FrameView_talk;
static std::shared_ptr<FrameView> FrameView_talk_L;
static std::shared_ptr<FrameView> FrameView_talk_R;
static std::shared_ptr<LabelView> LabelView_talk_eyeL;
static std::shared_ptr<LabelView> LabelView_talk_eyeR;
static std::shared_ptr<LabelView> LabelView_talk_tie;
static std::shared_ptr<LabelView> LabelView_talk_text;
static std::shared_ptr<Window> Window_main;

static void main_ui_init()
{
    CheckboxView_sle = std::make_shared<ImgButtonView>(56, 24);
    CheckboxView_sle->setColor(0x3F03);
    CheckboxView_sle->setTextColor(0);
    CheckboxView_sle->setBoundaryBuffer(round_rect_56_24_r1_boundary);
    CheckboxView_sle->setVisible(true);
    CheckboxView_sle->setPressedImage((uint16_t*)&rgb16_switch_pressed_56_24);
    CheckboxView_sle->setReleasedImage((uint16_t*)&rgb16_switch1_released_56_24);
    CheckboxView_sle->setSelfLocking(true);

    // 点击此按钮退出到设置主页面
    ButtonView_sle_back = std::make_shared<ButtonView>(48, 24);
    ButtonView_sle_back->setColor(0xFFFF);
    ButtonView_sle_back->setTextColor(0);
    ButtonView_sle_back->setVisible(true);
    ButtonView_sle_back->setImageBuffer((uint16_t*)&rgb16_back3_48_24);

    // sle标题
    LabelView_sle_tilte = std::make_shared<LabelView>(240, 24);
    LabelView_sle_tilte->setColor(0x0000);
    LabelView_sle_tilte->setTextColor(1);
    LabelView_sle_tilte->setText("星闪设置");
    LabelView_sle_tilte->setBoundaryBuffer(round_rect_240_24_r4_boundary);
    LabelView_sle_tilte->setVisible(true);

    // 显示搜索到的sle设备
    ListView_sle = std::make_shared<ListView>(280, 114);
    ListView_sle->setColor(0xFFFF);
    ListView_sle->setTextColor(0);
    ListView_sle->setBoundaryBuffer(round_rect_280_114_r1_boundary);
    ListView_sle->setVisible(true);

    ButtonView_sle_scan = std::make_shared<ButtonView>(200, 32);
    ButtonView_sle_scan->setColor(0x3F03);
    ButtonView_sle_scan->setTextColor(0);
    ButtonView_sle_scan->setBoundaryBuffer(round_rect_200_32_r3_boundary);
    ButtonView_sle_scan->setVisible(false);
    ButtonView_sle_scan->setImageBuffer((uint16_t*)&rgb16_sle_scan_200_32);

    LabelView_sle_pcode = std::make_shared<LabelView>(200, 32);
    LabelView_sle_pcode->setColor(0x3CE7);
    LabelView_sle_pcode->setTextColor(0);
    LabelView_sle_pcode->setBoundaryBuffer(round_rect_200_32_r4_boundary);
    LabelView_sle_pcode->setVisible(false);

    LabelView_sle_local_name = std::make_shared<LabelView>(200, 32);
    LabelView_sle_local_name->setColor(0x3CE7);
    LabelView_sle_local_name->setText("本机设备地址：加载中...");
    LabelView_sle_local_name->setTextColor(0);
    LabelView_sle_local_name->setBoundaryBuffer(round_rect_200_32_r4_boundary);
    LabelView_sle_local_name->setVisible(true);

    SpinnerView_sle_mode = std::make_shared<SpinnerView>(136, 24);
    SpinnerView_sle_mode->setColor(0x3CE7);
    SpinnerView_sle_mode->setTextColor(0);
    SpinnerView_sle_mode->setBoundaryBuffer(round_rect_136_24_r3_boundary);
    SpinnerView_sle_mode->setVisible(true);
    SpinnerView_sle_mode->setButtonColor(0x0000);
    SpinnerView_sle_mode->setTriangleColor(0xFFFF);
    SpinnerView_sle_mode->initializeViews();
    SpinnerView_sle_mode->addItem("主机模式", 0);
    SpinnerView_sle_mode->addItem("从机模式", 1);

    FrameView_sle = std::make_shared<FrameView>(320, 240);
    FrameView_sle->setColor(0xFFFF);
    FrameView_sle->setTextColor(0);
    FrameView_sle->setVisible(false);

    ProgressBarView_volume = std::make_shared<ProgressBarView>(280, 29);
    ProgressBarView_volume->setColor(0x3F03);
    ProgressBarView_volume->setTextColor(0);
    ProgressBarView_volume->setBoundaryBuffer(round_rect_280_29_r3_boundary);
    ProgressBarView_volume->setVisible(true);

    LabelView_volume_text = std::make_shared<LabelView>(48, 24);
    LabelView_volume_text->setColor(0xffff);
    LabelView_volume_text->setTextColor(0);
    LabelView_volume_text->setVisible(true);

    // 返回到设置主页面
    ButtonView_volume_back = std::make_shared<ButtonView>(48, 24);
    ButtonView_volume_back->setColor(0x3F03);
    ButtonView_volume_back->setTextColor(0);
    ButtonView_volume_back->setVisible(true);
    ButtonView_volume_back->setImageBuffer((uint16_t*)&rgb16_back3_48_24);



    LabelView_ptitle_show = std::make_shared<LabelView>(240, 24);
    LabelView_ptitle_show->setColor(0x0000);
    LabelView_ptitle_show->setTextColor(1);
    LabelView_ptitle_show->setText("音量设置");
    LabelView_ptitle_show->setBoundaryBuffer(round_rect_240_24_r4_boundary);
    LabelView_ptitle_show->setVisible(true);

    FrameView_volume = std::make_shared<FrameView>(320, 240);
    FrameView_volume->setColor(0xFFFF);
    FrameView_volume->setTextColor(0);
    FrameView_volume->setVisible(false);

    // 点击该按键后，保存输入的密码，并且用该密码来连接当前点击的网络。
    ButtonView_connect = std::make_shared<ButtonView>(80, 24);
    ButtonView_connect->setColor(0xFD87);
    ButtonView_connect->setTextColor(0);
    ButtonView_connect->setText("确定");
    ButtonView_connect->setBoundaryBuffer(round_rect_80_24_r4_boundary);
    ButtonView_connect->setVisible(true);

    // 点击该按键后，保存输入的密码，并且用该密码来连接当前点击的网络。
    ButtonView_cancel = std::make_shared<ButtonView>(80, 24);
    ButtonView_cancel->setColor(0x4C6B);
    ButtonView_cancel->setTextColor(0);
    ButtonView_cancel->setText("取消");
    ButtonView_cancel->setBoundaryBuffer(round_rect_80_24_r4_boundary);
    ButtonView_cancel->setVisible(true);

    // 用于显示和输入该网络的密码。如果已经保存过该网络的密码，则显示它。
    TextEditView_wifipasswd = std::make_shared<TextEditView>(112, 25);
    TextEditView_wifipasswd->setColor(0xFFFF);
    TextEditView_wifipasswd->setTextColor(0);
    TextEditView_wifipasswd->setBoundaryBuffer(round_rect_112_25_r1_boundary);
    TextEditView_wifipasswd->setVisible(true);

    // 输入wifi密码的frame，平时不可见，当点击wifilist中的item时，弹出.并且从wifiservice获得该网络的密码，填入密码输入框。如果获取不到，则密码输入框显示空。
    FrameView_wifipasswd = std::make_shared<FrameView>(224, 120);
    FrameView_wifipasswd->setColor(0x3CE7);
    FrameView_wifipasswd->setTextColor(0);
    FrameView_wifipasswd->setText("输入密码",85,8);
    FrameView_wifipasswd->setBoundaryBuffer(round_rect_224_120_r1_boundary);
    FrameView_wifipasswd->setVisible(false);

    LabelView_wifi_t1 = std::make_shared<LabelView>(64, 16);
    LabelView_wifi_t1->setColor(0xFFFF);
    LabelView_wifi_t1->setTextColor(0);
    LabelView_wifi_t1->setText("可用网络");
    LabelView_wifi_t1->setBoundaryBuffer(round_rect_64_16_r1_boundary);
    LabelView_wifi_t1->setVisible(true);

    // 显示扫描到的网络名称，点击它的item后，弹出输入密码对话框。
    ListView_wifilist = std::make_shared<ListView>(256, 125);
    ListView_wifilist->setColor(0xFFFF);
    ListView_wifilist->setTextColor(0);
    ListView_wifilist->setBoundaryBuffer(round_rect_256_125_r1_boundary);
    ListView_wifilist->setVisible(true);

    ButtonView_sle_connect = std::make_shared<ButtonView>(80, 24);
    ButtonView_sle_connect->setColor(0xFD87);
    ButtonView_sle_connect->setTextColor(0);
    ButtonView_sle_connect->setText("确定");
    ButtonView_sle_connect->setBoundaryBuffer(round_rect_80_24_r4_boundary);
    ButtonView_sle_connect->setVisible(true);

    
    ButtonView_sle_cancel = std::make_shared<ButtonView>(80, 24);
    ButtonView_sle_cancel->setColor(0x4C6B);
    ButtonView_sle_cancel->setTextColor(0);
    ButtonView_sle_cancel->setText("取消");
    ButtonView_sle_cancel->setBoundaryBuffer(round_rect_80_24_r4_boundary);
    ButtonView_sle_cancel->setVisible(true);

    //用于显示和输入配对码。如果已经保存过该从机的配对码，则显示它。
    TextEditView_sle_paircode = std::make_shared<TextEditView>(112, 25);
    TextEditView_sle_paircode->setColor(0xFFFF);
    TextEditView_sle_paircode->setTextColor(0);
    TextEditView_sle_paircode->setBoundaryBuffer(round_rect_112_25_r1_boundary);
    TextEditView_sle_paircode->setVisible(true);

   LabelView_del_sle_dev = std::make_shared<LabelView>(112, 25);
   LabelView_del_sle_dev->setColor(0x3CE7);
   LabelView_del_sle_dev->setTextColor(0);
   LabelView_del_sle_dev->setText("是否移除设备？");
   LabelView_del_sle_dev->setBoundaryBuffer(round_rect_112_25_r1_boundary);
   LabelView_del_sle_dev->setVisible(false);

    FrameView_sle_pair = std::make_shared<FrameView>(224, 120);
    FrameView_sle_pair->setColor(0x3CE7);
    FrameView_sle_pair->setTextColor(0);
    FrameView_sle_pair->setText("输入配对码", 85, 8);
    FrameView_sle_pair->setBoundaryBuffer(round_rect_224_120_r1_boundary);
    FrameView_sle_pair->setVisible(false);

    CheckboxView_wifisw = std::make_shared<ImgButtonView>(56, 26);
    CheckboxView_wifisw->setColor(0x3F03);
    CheckboxView_wifisw->setTextColor(0);
    CheckboxView_wifisw->setVisible(true);
    CheckboxView_wifisw->setPressedImage((uint16_t*)&rgb16_switch2_pressed_56_26);
    CheckboxView_wifisw->setReleasedImage((uint16_t*)&rgb16_switch6_released_56_26);
    CheckboxView_wifisw->setSelfLocking(true);

    // 返回到设置主界面
    Button_back0 = std::make_shared<ButtonView>(48, 24);
    Button_back0->setColor(0xBAD6);
    Button_back0->setTextColor(0);
    Button_back0->setVisible(true);
    Button_back0->setImageBuffer((uint16_t*)&rgb16_back3_48_24);

    LabelView_1766049650411 = std::make_shared<LabelView>(240, 24);
    LabelView_1766049650411->setColor(0x0000);
    LabelView_1766049650411->setTextColor(1);
    LabelView_1766049650411->setText("wifi设置");
    LabelView_1766049650411->setBoundaryBuffer(round_rect_240_24_r4_boundary);
    LabelView_1766049650411->setVisible(true);

    FrameView_wifitext = std::make_shared<FrameView>(256, 40);
    FrameView_wifitext->setColor(0x3CE7);
    FrameView_wifitext->setTextColor(0);
    FrameView_wifitext->setText("Wifi开关",16,12);
    FrameView_wifitext->setBoundaryBuffer(round_rect_256_40_r3_boundary);
    FrameView_wifitext->setVisible(true);

    // wifi设置页面总容器,设置它的visable，进入wifi设置页面。进入设置页面时，如果wifi处于打开状态，自动搜索一次网络。
    FrameView_wifi = std::make_shared<FrameView>(320, 240);
    FrameView_wifi->setColor(0xFFFF);
    FrameView_wifi->setTextColor(0);
    FrameView_wifi->setVisible(false);

    // 点击该按钮，暂时不做操作。
    Button_cloud = std::make_shared<ButtonView>(256, 40);
    Button_cloud->setColor(0x3CE7);
    Button_cloud->setTextColor(0);
    Button_cloud->setText("AI设置");
    Button_cloud->setBoundaryBuffer(round_rect_256_40_r3_boundary);
    Button_cloud->setVisible(true);
    Button_cloud->setIcon((uint16_t*)&rgb16_cloud_icon_40_40,40,40);

    // 点击该按钮，暂时不做操作.
    Button_bt = std::make_shared<ButtonView>(256, 40);
    Button_bt->setColor(0x3CE7);
    Button_bt->setTextColor(0);
    Button_bt->setText("音量设置");
    Button_bt->setBoundaryBuffer(round_rect_256_40_r3_boundary);
    Button_bt->setVisible(true);
    Button_bt->setIcon((uint16_t*)&rgb16_audio_icon_40_40,40,40);

    // 点击该按钮暂时不做操作.
    Button_sle = std::make_shared<ButtonView>(256, 40);
    Button_sle->setColor(0x3CE7);
    Button_sle->setTextColor(0);
    Button_sle->setText("星闪连接");
    Button_sle->setBoundaryBuffer(round_rect_256_40_r3_boundary);
    Button_sle->setVisible(true);
    Button_sle->setIcon((uint16_t*)&rgb16_sle_icon_40_40,40,40);

    Button_wifi = std::make_shared<ButtonView>(256, 40);
    Button_wifi->setColor(0x3CE7);
    Button_wifi->setTextColor(0);
    Button_wifi->setText("wifi设置");
    Button_wifi->setBoundaryBuffer(round_rect_256_40_r3_boundary);
    Button_wifi->setVisible(true);
    Button_wifi->setIcon((uint16_t*)&rgb16_wifi_icon1_40_40,40,40);

    LabelView_1766049869637 = std::make_shared<LabelView>(240, 24);
    LabelView_1766049869637->setColor(0x0000);
    LabelView_1766049869637->setTextColor(1);
    LabelView_1766049869637->setText("系统设置");
    LabelView_1766049869637->setBoundaryBuffer(round_rect_240_24_r3_boundary);
    LabelView_1766049869637->setVisible(true);

    // 设置主页面，设置它的visable，进入设置主页面。
    FrameView_0 = std::make_shared<FrameView>(320, 240);
    FrameView_0->setColor(0xFFFF);
    FrameView_0->setTextColor(0);
    FrameView_0->setVisible(true);

    // 音色设置按钮
    ButtonView_voice = std::make_shared<ButtonView>(80, 24);
    ButtonView_voice->setColor(0x3CE7);
    ButtonView_voice->setTextColor(0);
    ButtonView_voice->setText("   音色");
    ButtonView_voice->setBoundaryBuffer(round_rect_80_24_r3_boundary);
    ButtonView_voice->setVisible(true);
    ButtonView_voice->setIcon((uint16_t*)&rgb16_voice_24_24,24,24);

    CheckboxView_cloudsw = std::make_shared<ImgButtonView>(56, 25);
    CheckboxView_cloudsw->setColor(0x3F03);
    CheckboxView_cloudsw->setTextColor(0);
    CheckboxView_cloudsw->setVisible(true);
    CheckboxView_cloudsw->setPressedImage((uint16_t*)&rgb16_switch_pressed_56_25);
    CheckboxView_cloudsw->setReleasedImage((uint16_t*)&rgb16_switch1_released_56_25);
    CheckboxView_cloudsw->setSelfLocking(true);

    // 性格设置按钮
    ButtonView_person = std::make_shared<ButtonView>(80, 24);
    ButtonView_person->setColor(0x3CE7);
    ButtonView_person->setTextColor(0);
    ButtonView_person->setText("   个性");
    ButtonView_person->setBoundaryBuffer(round_rect_80_24_r3_boundary);
    ButtonView_person->setVisible(true);
    ButtonView_person->setIcon((uint16_t*)&rgb16_preson_24_24,24,24);

    // 人物关系按钮
    ButtonView_relat = std::make_shared<ButtonView>(80, 24);
    ButtonView_relat->setColor(0x3CE7);
    ButtonView_relat->setTextColor(0);
    ButtonView_relat->setText("   关系");
    ButtonView_relat->setBoundaryBuffer(round_rect_80_24_r3_boundary);
    ButtonView_relat->setVisible(true);
    ButtonView_relat->setIcon((uint16_t*)&rgb16_relat_24_24,24,24);

    // APIKey设置按钮
    ButtonView_apikey = std::make_shared<ButtonView>(80, 24);
    ButtonView_apikey->setColor(0x3CE7);
    ButtonView_apikey->setTextColor(0);
    ButtonView_apikey->setText("    APIKey");
    ButtonView_apikey->setBoundaryBuffer(round_rect_80_24_r3_boundary);
    ButtonView_apikey->setVisible(true);
    ButtonView_apikey->setIcon((uint16_t*)&rgb16_apikey_24_24,24,24);

    // 点击该按键，返回到设置主界面
    ButtonView_cloudback = std::make_shared<ButtonView>(48, 24);
    ButtonView_cloudback->setColor(0x9AD6);
    ButtonView_cloudback->setTextColor(0);
    ButtonView_cloudback->setVisible(true);
    ButtonView_cloudback->setImageBuffer((uint16_t*)&rgb16_back3_48_24);

    LabelView_cloudtitle = std::make_shared<LabelView>(256, 24);
    LabelView_cloudtitle->setColor(0x0000);
    LabelView_cloudtitle->setTextColor(1);
    LabelView_cloudtitle->setText("AI设置");
    LabelView_cloudtitle->setBoundaryBuffer(round_rect_256_24_r4_boundary);
    LabelView_cloudtitle->setVisible(true);

    TextEditView_apikey = std::make_shared<TextEditView>(184, 24);
    TextEditView_apikey->setColor(0xFFAF);
    TextEditView_apikey->setTextColor(0);
    TextEditView_apikey->setBoundaryBuffer(round_rect_184_24_r3_boundary);
    TextEditView_apikey->setVisible(false);

    ButtonView_cancle17 = std::make_shared<ButtonView>(56, 24);
    ButtonView_cancle17->setColor(0x55AD);
    ButtonView_cancle17->setTextColor(0);
    ButtonView_cancle17->setText("取消");
    ButtonView_cancle17->setBoundaryBuffer(round_rect_56_24_r4_boundary);
    ButtonView_cancle17->setVisible(false);

    LabelView_cfgtitle0 = std::make_shared<LabelView>(104, 16);
    LabelView_cfgtitle0->setColor(0x1CE7);
    LabelView_cfgtitle0->setTextColor(0);
    LabelView_cfgtitle0->setText("形象设置");
    LabelView_cfgtitle0->setVisible(true);

    ButtonView_yes17 = std::make_shared<ButtonView>(56, 24);
    ButtonView_yes17->setColor(0x3F03);
    ButtonView_yes17->setTextColor(0);
    ButtonView_yes17->setText("确定");
    ButtonView_yes17->setBoundaryBuffer(round_rect_56_24_r4_boundary);
    ButtonView_yes17->setVisible(false);

    ListView_cfgwmlist = std::make_shared<ListView>(160, 98);
    ListView_cfgwmlist->setColor(0xFFFF);
    ListView_cfgwmlist->setTextColor(0);
    ListView_cfgwmlist->setBoundaryBuffer(round_rect_160_98_r1_boundary);
    ListView_cfgwmlist->setVisible(true);

    FrameView_config_wm = std::make_shared<FrameView>(208, 143);
    FrameView_config_wm->setColor(0x3CE7);
    FrameView_config_wm->setTextColor(0);
    FrameView_config_wm->setBoundaryBuffer(round_rect_208_143_r1_boundary);
    FrameView_config_wm->setVisible(true);

    // 显示当前选择的形象的名称
    LabelView_avashow0 = std::make_shared<LabelView>(80, 18);
    LabelView_avashow0->setColor(0xFFFF);
    LabelView_avashow0->setTextColor(0);
    LabelView_avashow0->setBoundaryBuffer(round_rect_80_18_r1_boundary);
    LabelView_avashow0->setVisible(true);

    // 用于显示形象的照片
    LabelView_pic = std::make_shared<LabelView>(152, 136);
    LabelView_pic->setColor(0xFFFF);
    LabelView_pic->setTextColor(0);
    LabelView_pic->setBoundaryBuffer(round_rect_152_136_r1_boundary);
    LabelView_pic->setVisible(true);
    LabelView_pic->setImageBuffer((uint16_t*)&rgb16_avatar_female_152_136);

    // 形象设置按钮
    ButtonView_ava = std::make_shared<ButtonView>(80, 24);
    ButtonView_ava->setColor(0x3CE7);
    ButtonView_ava->setTextColor(0);
    ButtonView_ava->setText("   形象");
    ButtonView_ava->setBoundaryBuffer(round_rect_80_24_r3_boundary);
    ButtonView_ava->setVisible(true);
    ButtonView_ava->setIcon((uint16_t*)&rgb16_avat_24_24,24,24);

    /* status indicator lights (connection + conversation state)
     * placed side-by-side below the avatar, aligned to its right edge */
    LabelView_status_conn = std::make_shared<LabelView>(76, 16);
    LabelView_status_conn->setColor(0x0000);        /* red background = disconnected */
    LabelView_status_conn->setTextColor(0xFFFF);     /* white text */
    LabelView_status_conn->setText("● 未连接");
    LabelView_status_conn->setVisible(true);

    LabelView_status_conv = std::make_shared<LabelView>(76, 16);
    LabelView_status_conv->setColor(0x1082);         /* dark blue background = idle */
    LabelView_status_conv->setTextColor(0xFFFF);      /* white text */
    LabelView_status_conv->setText("空闲");
    LabelView_status_conv->setVisible(true);

    /* "进入对话" 按钮：引擎连接后可见，放在头像右侧空白区 */
    ButtonView_enter_talk = std::make_shared<ButtonView>(36, 20);
    ButtonView_enter_talk->setColor(0x3F03);          /* green */
    ButtonView_enter_talk->setTextColor(0xFFFF);       /* white text */
    ButtonView_enter_talk->setText("对话");
    ButtonView_enter_talk->setVisible(false);           /* 默认隐藏 */

    // 云服务设置界面
    FrameView_cloud = std::make_shared<FrameView>(320, 240);
    FrameView_cloud->setColor(0xFFFF);
    FrameView_cloud->setTextColor(0);
    FrameView_cloud->setVisible(false);

    // 输入法控件,正常情况下设置vsiable 为false，需要在textedit的点击回调中设置它的vsiable 为ture。
    InputMethodView_0 = std::make_shared<InputMethodView>(296, 240);
    InputMethodView_0->setColor(0xFFFF);
    InputMethodView_0->setTextColor(0);
    InputMethodView_0->setVisible(false);

    // ---- 对话页控件 (FrameView_talk, 320x240 全屏) ----
    LabelView_talk_tie = std::make_shared<LabelView>(56, 53);
    LabelView_talk_tie->setColor(0xFFFF);
    LabelView_talk_tie->setTextColor(0);
    LabelView_talk_tie->setBoundaryBuffer(round_rect_56_53_r1_boundary);
    LabelView_talk_tie->setVisible(true);
    LabelView_talk_tie->setImageBuffer((uint16_t*)&rgb16_bowtie_56_53);

    LabelView_talk_eyeR = std::make_shared<LabelView>(88, 85);
    LabelView_talk_eyeR->setColor(0xFFFF);
    LabelView_talk_eyeR->setTextColor(0);
    LabelView_talk_eyeR->setBoundaryBuffer(round_rect_88_85_r1_boundary);
    LabelView_talk_eyeR->setVisible(true);
    LabelView_talk_eyeR->setImageBuffer((uint16_t*)&rgb16_closeeye_r1_88_85);

    FrameView_talk_R = std::make_shared<FrameView>(160, 240);
    FrameView_talk_R->setColor(0x0000);
    FrameView_talk_R->setTextColor(0);
    FrameView_talk_R->setVisible(true);

    LabelView_talk_eyeL = std::make_shared<LabelView>(88, 85);
    LabelView_talk_eyeL->setColor(0xFFFF);
    LabelView_talk_eyeL->setTextColor(0);
    LabelView_talk_eyeL->setBoundaryBuffer(round_rect_88_85_r1_boundary);
    LabelView_talk_eyeL->setVisible(true);
    LabelView_talk_eyeL->setImageBuffer((uint16_t*)&rgb16_closeeye_l_88_85);

    FrameView_talk_L = std::make_shared<FrameView>(160, 240);
    FrameView_talk_L->setColor(0x0000);
    FrameView_talk_L->setTextColor(0);
    FrameView_talk_L->setVisible(true);

    LabelView_talk_text = std::make_shared<LabelView>(240, 16);
    LabelView_talk_text->setColor(0x0000);
    LabelView_talk_text->setTextColor(0xFFFF);
    LabelView_talk_text->setText("准备中....");
    LabelView_talk_text->setBoundaryBuffer(round_rect_240_16_r1_boundary);
    LabelView_talk_text->setVisible(true);

    FrameView_talk = std::make_shared<FrameView>(320, 240);
    FrameView_talk->setColor(0x0000);
    FrameView_talk->setTextColor(0);
    FrameView_talk->setVisible(false);

    Window_main = std::make_shared<Window>(APP_WINDOW_START_X, APP_WINDOW_START_Y,320, 240);
    Window_main->setColor(0x8631);
    Window_main->setTextColor(0);
    Window_main->setVisible(true);

    // 建立控件父子关系
    FrameView_sle->addView(SpinnerView_sle_mode, 40, 42);
    FrameView_sle->addView(LabelView_sle_pcode, 56, 78);
    FrameView_sle->addView(ButtonView_sle_scan, 56, 78);
    FrameView_sle->addView(ListView_sle, 24, 80);
    FrameView_sle->addView(LabelView_sle_tilte, 40, 8);
    FrameView_sle->addView(ButtonView_sle_back, 56, 8);
    FrameView_sle->addView(CheckboxView_sle, 232, 43);
    FrameView_sle->addView(FrameView_sle_pair, 48, 40);
    FrameView_sle->addView(LabelView_sle_local_name, 56, 200);
    
    
    Window_main->addView(FrameView_cloud, 0, 0);
    Window_main->addView(FrameView_0, 0, 0);
    Window_main->addView(FrameView_wifi, 0, 0);
    Window_main->addView(FrameView_volume, 0, 0);
    Window_main->addView(FrameView_sle, 0, 0);
    FrameView_volume->addView(LabelView_ptitle_show, 40, 8);
    FrameView_volume->addView(ButtonView_volume_back, 56, 8);
    FrameView_volume->addView(ProgressBarView_volume, 24, 120);
    FrameView_volume->addView(LabelView_volume_text, 136, 80);
	
    FrameView_wifipasswd->addView(TextEditView_wifipasswd, 64, 35);
    FrameView_wifipasswd->addView(ButtonView_cancel, 136, 78);
    FrameView_wifipasswd->addView(ButtonView_connect, 16, 78);
    
    FrameView_sle_pair->addView(LabelView_del_sle_dev, 64, 35);
    FrameView_sle_pair->addView(TextEditView_sle_paircode, 64, 35);
    FrameView_sle_pair->addView(ButtonView_sle_cancel, 136, 78);
    FrameView_sle_pair->addView(ButtonView_sle_connect, 16, 78);

    FrameView_wifi->addView(LabelView_1766049650411, 40, 8);
    FrameView_wifi->addView(Button_back0, 56, 8);

    
    FrameView_wifi->addView(FrameView_wifitext, 32, 54);
    FrameView_wifi->addView(CheckboxView_wifisw, 224, 62);
    FrameView_wifi->addView(ListView_wifilist, 32, 116);
    FrameView_wifi->addView(LabelView_wifi_t1, 32, 96);
	
    FrameView_wifi->addView(FrameView_wifipasswd, 48, 40);
    FrameView_0->addView(LabelView_1766049869637, 40, 8);
    FrameView_0->addView(Button_wifi, 32, 47);
    FrameView_0->addView(Button_sle, 32, 96);
    FrameView_0->addView(Button_bt, 32, 192);
    FrameView_0->addView(Button_cloud, 32, 143);
    FrameView_cloud->addView(ButtonView_ava, 16, 48);
    FrameView_cloud->addView(LabelView_pic, 128, 76);
    FrameView_cloud->addView(LabelView_avashow0, 168, 44);
    FrameView_cloud->addView(FrameView_config_wm, 104, 71);
    FrameView_cloud->addView(LabelView_cloudtitle, 40, 8);
    FrameView_cloud->addView(ButtonView_cloudback, 64, 8);
    FrameView_cloud->addView(ButtonView_apikey, 16, 200);
    FrameView_cloud->addView(ButtonView_relat, 16, 163);
    FrameView_cloud->addView(ButtonView_person, 16, 125);
    FrameView_cloud->addView(CheckboxView_cloudsw, 256, 41);
    FrameView_cloud->addView(LabelView_status_conn, 128, 216);
    FrameView_cloud->addView(LabelView_status_conv, 204, 216);
    FrameView_cloud->addView(ButtonView_enter_talk, 284, 76);  /* 头像右侧 */
    FrameView_cloud->addView(ButtonView_voice, 16, 88);
    FrameView_config_wm->addView(ListView_cfgwmlist, 24, 26);
    FrameView_config_wm->addView(ButtonView_yes17, 32, 87);
    FrameView_config_wm->addView(LabelView_cfgtitle0, 56, 5);
    FrameView_config_wm->addView(ButtonView_cancle17, 128, 88);
    FrameView_config_wm->addView(TextEditView_apikey, 16, 39);
    Window_main->addView(InputMethodView_0, 16, 0);
    // 对话页父子关系
    Window_main->addView(FrameView_talk, 0, 0);
    FrameView_talk->addView(LabelView_talk_text, 40, 155);
    FrameView_talk->addView(FrameView_talk_L, 0, 0);
    FrameView_talk->addView(FrameView_talk_R, 160, 0);
    FrameView_talk->addView(LabelView_talk_tie, 140, 155);
    FrameView_talk_R->addView(LabelView_talk_eyeR, 8, 67);
    FrameView_talk_L->addView(LabelView_talk_eyeL, 72, 66);
    // 刷新窗口
    Window_main->flush(0, 0, APP_WINDOW_WIDTH, APP_WINDOW_HEIGHT);
}

static void window_exit(void)
{
    Window_main->setVisible(false);
    Window_main->removeAllViews();
	
    ListView_sle->clearItems();
    SpinnerView_sle_mode->clearItems();
    FrameView_sle_pair->removeAllChilds();
    ListView_wifilist->clearItems();
    ListView_cfgwmlist->clearItems();
    FrameView_sle->removeAllChilds();
    FrameView_volume->removeAllChilds();
    FrameView_wifipasswd->removeAllChilds();
    FrameView_wifitext->removeAllChilds();
    FrameView_wifi->removeAllChilds();
    FrameView_0->removeAllChilds();
    FrameView_config_wm->removeAllChilds();
    FrameView_cloud->removeAllChilds();
    FrameView_talk->removeAllChilds();
    SpinnerView_sle_mode->destoryViews();

    CheckboxView_sle.reset();
    ButtonView_sle_back.reset();
    LabelView_sle_tilte.reset();
    ListView_sle.reset();
    ButtonView_sle_scan.reset();
    LabelView_sle_pcode.reset();
    LabelView_sle_local_name.reset();
    SpinnerView_sle_mode.reset();
    ProgressBarView_volume.reset();
    LabelView_volume_text.reset();

    ButtonView_volume_back.reset();	
    LabelView_ptitle_show.reset();
    ButtonView_connect.reset();
    ButtonView_cancel.reset();
    TextEditView_wifipasswd.reset();
    ButtonView_sle_connect.reset();
    ButtonView_sle_cancel.reset();
    TextEditView_sle_paircode.reset();
    FrameView_sle_pair.reset();
    LabelView_wifi_t1.reset();
    ListView_wifilist.reset();
    CheckboxView_wifisw.reset();
    Button_back0.reset();
    LabelView_1766049650411.reset();
    Button_cloud.reset();
    Button_bt.reset();
    Button_sle.reset();
    Button_wifi.reset();
    LabelView_1766049869637.reset();
    ButtonView_voice.reset();
    CheckboxView_cloudsw.reset();
    ButtonView_person.reset();
    ButtonView_relat.reset();
    ButtonView_apikey.reset();
    ButtonView_cloudback.reset();
    LabelView_cloudtitle.reset();
    TextEditView_apikey.reset();
    ButtonView_cancle17.reset();
    LabelView_cfgtitle0.reset();
    ButtonView_yes17.reset();
    ListView_cfgwmlist.reset();
    LabelView_avashow0.reset();
    LabelView_pic.reset();
    ButtonView_ava.reset();
    LabelView_status_conn.reset();
    LabelView_status_conv.reset();
    ButtonView_enter_talk.reset();
    InputMethodView_0.reset();
    // 对话页控件
    LabelView_talk_tie.reset();
    LabelView_talk_eyeR.reset();
    LabelView_talk_eyeL.reset();
    LabelView_talk_text.reset();
    FrameView_talk_R.reset();
    FrameView_talk_L.reset();
    FrameView_talk.reset();
    FrameView_sle.reset();
    FrameView_volume.reset();
    FrameView_wifipasswd.reset();
    FrameView_wifitext.reset();
    FrameView_wifi.reset();
    FrameView_0.reset();
    FrameView_config_wm.reset();
    FrameView_cloud.reset();
    Window_main.reset();
}

static void window_suspend(void)
{
    Window_main->setVisible(false);
}

static void window_resume(void)
{
    Window_main->setVisible(true);
    Window_main->flush(0, 0, APP_WINDOW_WIDTH, APP_WINDOW_HEIGHT);
}

#endif //INCLUDE_MAIN_UI_H 

