/*This file is automatically generated by the tinyui tool and should not be modified.*/
#ifndef INCLUDE_MAIN_UI_H
#define INCLUDE_MAIN_UI_H
#include <memory>
#include <vector>

#include "goldie_display.h" 
// 控件头文件
#include "label_view.h"
#include "window.h"

// 图片头文件
#include "rgb16_wink_4_160_160.h"
#include "rgb16_wink_4_160_160.h"

// 掩码头文件
#include "round_rect_160_160_r1_boundary.h"
#include "round_rect_160_160_r1_boundary.h"
// 全局控件变量定义
static std::shared_ptr<LabelView> LabelView_left_word;
static std::shared_ptr<LabelView> LabelView_right_word;
static std::shared_ptr<LabelView> LabelView_right;
static std::shared_ptr<LabelView> LabelView_left;
static std::shared_ptr<Window> Window_1777432726401;

static void main_ui_init()
{
    LabelView_left_word = std::make_shared<LabelView>(160, 160);
    LabelView_left_word->setColor(0xFFFF);
    LabelView_left_word->setTextColor(0);
    LabelView_left_word->setBoundaryBuffer(round_rect_160_160_r1_boundary);
    LabelView_left_word->setVisible(false);

    LabelView_right_word = std::make_shared<LabelView>(160, 160);
    LabelView_right_word->setColor(0xFFFF);
    LabelView_right_word->setTextColor(0);
    LabelView_right_word->setBoundaryBuffer(round_rect_160_160_r1_boundary);
    LabelView_right_word->setVisible(false);

    LabelView_right = std::make_shared<LabelView>(160, 160);
    LabelView_right->setColor(0xFFFF);
    LabelView_right->setTextColor(0);
    LabelView_right->setVisible(true);
    LabelView_right->setImageBuffer((uint16_t*)&rgb16_wink_4_160_160);

    LabelView_left = std::make_shared<LabelView>(160, 160);
    LabelView_left->setColor(0xFFFF);
    LabelView_left->setTextColor(0);
    LabelView_left->setVisible(true);
    LabelView_left->setImageBuffer((uint16_t*)&rgb16_wink_4_160_160);

    Window_1777432726401 = std::make_shared<Window>(APP_WINDOW_START_X, APP_WINDOW_START_Y,320, 160);
    Window_1777432726401->setColor(0x8631);
    Window_1777432726401->setTextColor(0);
    Window_1777432726401->setVisible(true);

    // 建立控件父子关系
    Window_1777432726401->addView(LabelView_left, 160, 0);
    Window_1777432726401->addView(LabelView_right, 0, 0);
    Window_1777432726401->addView(LabelView_right_word, 160, 0);
    Window_1777432726401->addView(LabelView_left_word, 0, 0);

    // 刷新窗口
    Window_1777432726401->flush(0, 0, APP_WINDOW_WIDTH, APP_WINDOW_HEIGHT);
}

static void window_exit(void)
{
    LabelView_left_word.reset();
    LabelView_right_word.reset();
    LabelView_right.reset();
    LabelView_left.reset();
    Window_1777432726401->setVisible(false);
    Window_1777432726401->removeAllViews();
    Window_1777432726401.reset();
}

static void window_suspend(void)
{
    Window_1777432726401->setVisible(false);
}

static void window_resume(void)
{
    Window_1777432726401->setVisible(true);
    Window_1777432726401->flush(0, 0, APP_WINDOW_WIDTH, APP_WINDOW_HEIGHT);
}

#endif //INCLUDE_MAIN_UI_H 

