/*This file is automatically generated by the tinyui tool 
and contains the main_ui. h file, which calls the initialization 
function main_ui_init() to create the UI interface. You need to 
add code related to business logic here..*/
#include "main_ui.h"
#include "default_app_icon.h" 
#include "goldie_thread.h"
extern "C" { 
#include "goldie_osal.h" 
#include "service_manager.h" 
#include "app_manager.h" 
#include "rgb16_wink_woman_1_160_160.h"
#include "rgb16_wink_woman_2_160_160.h"
#include "rgb16_wink_woman_3_160_160.h"
#include "rgb16_wink_man_1_160_160.h"
#include "rgb16_wink_man_2_160_160.h"
#include "rgb16_wink_man_3_160_160.h"
#include "rgb16_wink_4_160_160.h"
#include "rgb16_happy_1_160_160.h"
#include "rgb16_happy_2_160_160.h"
#include "rgb16_angry_woman_1_160_160.h"
#include "rgb16_angry_man_1_160_160.h"
#include "rgb16_cry_woman_1_160_160.h"
#include "rgb16_cry_woman_2_160_160.h"
#include "rgb16_cry_man_1_160_160.h"
#include "rgb16_cry_man_2_160_160.h"
#include "rgb16_confused_1_160_160.h"
#include "rgb16_confused_2_160_160.h"
} 

static WifiService* wifi_service = NULL;
static EventService* mevtservice = NULL;

#ifndef 	USE_EXT_ASR_CHIP_AC2817	
static AualgoService* maualgo_service;
#endif

static goldie_mutex msgque_mutex;
#define MAX_CHAT_MSG_LEN 1500

enum {
    PLAY_TYPE_SILENCE = 0,
    PLAY_TYPE_SPEAK,
    PLAY_TYPE_SLEEP,
};

// 情绪枚举
enum {
    EMOTION_NEUTRAL = 0,
    EMOTION_HAPPY,
    EMOTION_ANGRY,
    EMOTION_SAD,
    EMOTION_DOUBT,
};

static int play_type = PLAY_TYPE_SILENCE;
static int wifi_config_mode = 0;  // 配网模式标志，进入配网时不显示眼睛
static void *task_handle = NULL;
static char wifi_ssid_before_config[32] = {0}; 

typedef struct _Chat_Msg {
    int uid;
    char msg_buf[MAX_CHAT_MSG_LEN];
} Chat_Msg;

#define MAX_MSG_NUM 4
typedef struct {
    Chat_Msg messages[MAX_MSG_NUM];
    int head;
    int tail;
    int count;
} MsgQueue;

static MsgQueue s_msg_queue = {0};

// 移除整图动画相关的Avatar_Animation结构体（改用眼睛状态模拟）
static int avatar_id = 0;
static int current_emotion = EMOTION_NEUTRAL; //新增
static CloudService* cloud_service = NULL;
static int cloud_service_st = CLOUD_STATUS_STOPED;
static int cloud_speak_st = CLOUD_SPEAK_STATUS_SILENCE;

static int play_animation(void);
static void stop_animation(void);
static void update_status(void);
static void cloud_status_callback(int status);

static void add_msg(BroadcastMessage* msg) {
    int msg_len = msg->msg_len;
    int userid = msg->ext[0];
    if (msg_len > (MAX_CHAT_MSG_LEN - 1)) {
        msg_len = MAX_CHAT_MSG_LEN - 1;
    }

    goldie_mutex_lock(&msgque_mutex);
    if (s_msg_queue.count < MAX_MSG_NUM) {
        s_msg_queue.messages[s_msg_queue.tail].uid = userid;
        memset(s_msg_queue.messages[s_msg_queue.tail].msg_buf, 0, MAX_CHAT_MSG_LEN);
        memcpy(s_msg_queue.messages[s_msg_queue.tail].msg_buf, msg->msg, msg_len);
        s_msg_queue.tail = (s_msg_queue.tail + 1) % MAX_MSG_NUM;
        s_msg_queue.count++;
    }
    goldie_mutex_unlock(&msgque_mutex);
}
// 模拟眼睛状态变化
static void update_avatar_ui(int play_type) { 
    if(avatar_id)//男性
    {
        switch(play_type){
            case PLAY_TYPE_SLEEP:
                LabelView_left->setImageBuffer((uint16_t*)&rgb16_wink_4_160_160);
                LabelView_right->setImageBuffer((uint16_t*)&rgb16_wink_4_160_160);
                goldie_msleep(500);
                break;
            case PLAY_TYPE_SILENCE:
                for (size_t i = 0; i < 3; i++)
                {
                    LabelView_left->setImageBuffer((uint16_t*)&rgb16_wink_man_1_160_160);
                    LabelView_right->setImageBuffer((uint16_t*)&rgb16_wink_man_1_160_160);
                    goldie_msleep(150);
                    LabelView_left->setImageBuffer((uint16_t*)&rgb16_wink_man_2_160_160);
                    LabelView_right->setImageBuffer((uint16_t*)&rgb16_wink_man_2_160_160);
                    goldie_msleep(150);
                }
                /*眨眼*/
                LabelView_left->setImageBuffer((uint16_t*)&rgb16_wink_man_3_160_160);
                LabelView_right->setImageBuffer((uint16_t*)&rgb16_wink_man_3_160_160);
                goldie_msleep(100);
                LabelView_left->setImageBuffer((uint16_t*)&rgb16_wink_4_160_160);
                LabelView_right->setImageBuffer((uint16_t*)&rgb16_wink_4_160_160);
                goldie_msleep(100);
                break;
            case PLAY_TYPE_SPEAK:
                if(current_emotion==EMOTION_NEUTRAL)//平静
                {
                    LabelView_left->setImageBuffer((uint16_t*)&rgb16_wink_man_1_160_160);
                    LabelView_right->setImageBuffer((uint16_t*)&rgb16_wink_man_1_160_160);
                    goldie_msleep(150);
                    LabelView_left->setImageBuffer((uint16_t*)&rgb16_wink_man_2_160_160);
                    LabelView_right->setImageBuffer((uint16_t*)&rgb16_wink_man_2_160_160);
                    goldie_msleep(150);
                }else if(current_emotion==EMOTION_HAPPY){//开心
                    LabelView_left->setImageBuffer((uint16_t*)&rgb16_happy_1_160_160);
                    LabelView_right->setImageBuffer((uint16_t*)&rgb16_happy_1_160_160);
                    goldie_msleep(150);
                    LabelView_left->setImageBuffer((uint16_t*)&rgb16_happy_2_160_160);
                    LabelView_right->setImageBuffer((uint16_t*)&rgb16_happy_2_160_160);
                    goldie_msleep(150);
                }else if(current_emotion==EMOTION_ANGRY){//生气
                    LabelView_left->setImageBuffer((uint16_t*)&rgb16_wink_man_3_160_160);
                    LabelView_right->setImageBuffer((uint16_t*)&rgb16_wink_man_3_160_160);
                    goldie_msleep(100);
                    LabelView_left->setImageBuffer((uint16_t*)&rgb16_angry_man_1_160_160);
                    LabelView_right->setImageBuffer((uint16_t*)&rgb16_angry_man_1_160_160);
                    goldie_msleep(2000);
                }else if(current_emotion==EMOTION_SAD){//伤心
                    LabelView_left->setImageBuffer((uint16_t*)&rgb16_cry_man_1_160_160);
                    LabelView_right->setImageBuffer((uint16_t*)&rgb16_cry_man_1_160_160);
                    goldie_msleep(150);
                    LabelView_left->setImageBuffer((uint16_t*)&rgb16_cry_man_2_160_160);
                    LabelView_right->setImageBuffer((uint16_t*)&rgb16_cry_man_2_160_160);
                    goldie_msleep(150);
                }else if(current_emotion==EMOTION_DOUBT){//疑惑
                    LabelView_left->setImageBuffer((uint16_t*)&rgb16_confused_1_160_160);
                    LabelView_right->setImageBuffer((uint16_t*)&rgb16_confused_1_160_160);
                    goldie_msleep(150);
                    LabelView_left->setImageBuffer((uint16_t*)&rgb16_confused_2_160_160);
                    LabelView_right->setImageBuffer((uint16_t*)&rgb16_confused_2_160_160);
                    goldie_msleep(150);
                }else{
                    goldie_msleep(300);
                }
                break;
            default:
                goldie_msleep(300);
                break;
        }
    }else{//女性
        switch(play_type){
            case PLAY_TYPE_SLEEP:
                LabelView_left->setImageBuffer((uint16_t*)&rgb16_wink_4_160_160);
                LabelView_right->setImageBuffer((uint16_t*)&rgb16_wink_4_160_160);
                goldie_msleep(500);
                break;
            case PLAY_TYPE_SILENCE:
                for (size_t i = 0; i < 3; i++)
                {
                    LabelView_left->setImageBuffer((uint16_t*)&rgb16_wink_woman_1_160_160);
                    LabelView_right->setImageBuffer((uint16_t*)&rgb16_wink_woman_1_160_160);
                    goldie_msleep(150);
                    LabelView_left->setImageBuffer((uint16_t*)&rgb16_wink_woman_2_160_160);
                    LabelView_right->setImageBuffer((uint16_t*)&rgb16_wink_woman_2_160_160);
                    goldie_msleep(150);
                }
                /*眨眼*/
                LabelView_left->setImageBuffer((uint16_t*)&rgb16_wink_woman_3_160_160);
                LabelView_right->setImageBuffer((uint16_t*)&rgb16_wink_woman_3_160_160);
                goldie_msleep(100);
                LabelView_left->setImageBuffer((uint16_t*)&rgb16_wink_4_160_160);
                LabelView_right->setImageBuffer((uint16_t*)&rgb16_wink_4_160_160);
                goldie_msleep(100);
                break;
            case PLAY_TYPE_SPEAK:
                if(current_emotion==EMOTION_NEUTRAL)//平静
                {
                    LabelView_left->setImageBuffer((uint16_t*)&rgb16_wink_woman_1_160_160);
                    LabelView_right->setImageBuffer((uint16_t*)&rgb16_wink_woman_1_160_160);
                    goldie_msleep(150);
                    LabelView_left->setImageBuffer((uint16_t*)&rgb16_wink_woman_2_160_160);
                    LabelView_right->setImageBuffer((uint16_t*)&rgb16_wink_woman_2_160_160);
                    goldie_msleep(150);
                }else if(current_emotion==EMOTION_HAPPY){//开心
                    LabelView_left->setImageBuffer((uint16_t*)&rgb16_happy_1_160_160);
                    LabelView_right->setImageBuffer((uint16_t*)&rgb16_happy_1_160_160);
                    goldie_msleep(150);
                    LabelView_left->setImageBuffer((uint16_t*)&rgb16_happy_2_160_160);
                    LabelView_right->setImageBuffer((uint16_t*)&rgb16_happy_2_160_160);
                    goldie_msleep(150);
                }else if(current_emotion==EMOTION_ANGRY){//生气
                    LabelView_left->setImageBuffer((uint16_t*)&rgb16_wink_woman_3_160_160);
                    LabelView_right->setImageBuffer((uint16_t*)&rgb16_wink_woman_3_160_160);
                    goldie_msleep(100);
                    LabelView_left->setImageBuffer((uint16_t*)&rgb16_angry_woman_1_160_160);
                    LabelView_right->setImageBuffer((uint16_t*)&rgb16_angry_woman_1_160_160);
                    goldie_msleep(2000);
                }else if(current_emotion==EMOTION_SAD){//伤心
                    LabelView_left->setImageBuffer((uint16_t*)&rgb16_cry_woman_1_160_160);
                    LabelView_right->setImageBuffer((uint16_t*)&rgb16_cry_woman_1_160_160);
                    goldie_msleep(150);
                    LabelView_left->setImageBuffer((uint16_t*)&rgb16_cry_woman_2_160_160);
                    LabelView_right->setImageBuffer((uint16_t*)&rgb16_cry_woman_2_160_160);
                    goldie_msleep(150);
                }else if(current_emotion==EMOTION_DOUBT){//疑惑
                    LabelView_left->setImageBuffer((uint16_t*)&rgb16_confused_1_160_160);
                    LabelView_right->setImageBuffer((uint16_t*)&rgb16_confused_1_160_160);
                    goldie_msleep(150);
                    LabelView_left->setImageBuffer((uint16_t*)&rgb16_confused_2_160_160);
                    LabelView_right->setImageBuffer((uint16_t*)&rgb16_confused_2_160_160);
                    goldie_msleep(150);
                }else{
                    goldie_msleep(300);
                }
                break;
            default:
                goldie_msleep(300);
                break;
        }
    }
}



static int eye_img_task(void *param) {
    (void*)param;
    while (1) {
        if (wifi_config_mode) {
            goldie_msleep(300);
            LabelView_right_word->setText("配网模式", 55, 70);
            LabelView_left_word->setText("配网模式", 55, 70);
            if (wifi_service->svr_sta_isConnected()) {
                char* current_ssid = wifi_service->svr_sta_connection_name();
                if (current_ssid) {
                // 如果之前有记录SSID，且当前SSID不同 → 配网成功
                // 如果之前没记录SSID（未连接），现在有SSID → 配网成功
                if (wifi_ssid_before_config[0] == '\0' || 
                    strcmp(current_ssid, wifi_ssid_before_config) != 0) {
                    
                    wifi_config_mode = 0;
                    LabelView_left_word->setVisible(false);
                    LabelView_right_word->setVisible(false);
                    LabelView_left->setVisible(true);
                    LabelView_right->setVisible(true);
                    LabelView_left->setImageBuffer((uint16_t*)&rgb16_wink_4_160_160);
                    LabelView_right->setImageBuffer((uint16_t*)&rgb16_wink_4_160_160);
                    }
                }
            }else{
            // WiFi未连接，确保眼睛隐藏，只显示文字
            LabelView_left->setVisible(false);
            LabelView_right->setVisible(false);
            LabelView_left_word->setVisible(true);
            LabelView_right_word->setVisible(true);
            LabelView_right_word->setText("配网模式", 55, 70);
            LabelView_left_word->setText("配网模式", 55, 70);
            // 每3秒重启一次SoftAP，确保配网模式可用
            static int softap_restart_cnt = 0;
            softap_restart_cnt++;
                if (softap_restart_cnt >= 10) {
                    softap_restart_cnt = 0;
                    if (!wifi_service->svr_softap_isEnabled()) {
                        printf("[eye_img_task] SoftAP was closed, restarting...\n");
                        char ap_ssid[] = "xiaohe";
                        char ap_password[] = "12345678";
                        wifi_service->svr_softap_config(ap_ssid, ap_password);
                        wifi_service->trigger_event(WIFI_EVENT_SOFTAP_ENABLE, NULL);
                    }
                }
            }
        }else{
        update_status();
        // 更新状态机
        if ((cloud_service_st == CLOUD_STATUS_STOPED) || (cloud_service_st == CLOUD_STATUS_SLEEPED)) {
            play_type = PLAY_TYPE_SLEEP;
        } else {
            if (cloud_speak_st == CLOUD_SPEAK_STATUS_SILENCE) {
                play_type = PLAY_TYPE_SILENCE;
            } else {
                play_type = PLAY_TYPE_SPEAK;
            }
        }

        // 更新头像UI（眼睛）
        update_avatar_ui(play_type);
        }
    }
    return 0;
}


static int priv_atoi(char* str) {
    int str_len = strlen(str);
    if (str_len < 3) {
        return 0;
    }
    if ((str[0] == 'i') && (str[1] == 'd') && (str[2] == '_')) {
        return atoi(str + 3);
    }
    return 0;
}

static void update_status() {
    if (cloud_service) {
        char* cfg_str = cloud_service->get_config(CONFIG_AVATAR);
        avatar_id = priv_atoi(cfg_str);
        cloud_service_st = cloud_service->get_status();
        cloud_speak_st = cloud_service->get_speak_status();
        // 获取情绪并转换为枚举
        char* emotion_str = cloud_service->get_config(EMOTION);
        if (emotion_str) {
            if (strcmp(emotion_str, "happy") == 0) {
                current_emotion = EMOTION_HAPPY;
            } else if (strcmp(emotion_str, "angry") == 0) {
                current_emotion = EMOTION_ANGRY;
            } else if (strcmp(emotion_str, "sad") == 0) {
                current_emotion = EMOTION_SAD;
            } else if (strcmp(emotion_str, "doubt") == 0) {
                current_emotion = EMOTION_DOUBT;
            } else {
                current_emotion = EMOTION_NEUTRAL;
            }
        // printf("\r\n\r\nemotion: %s\r\n\r\n", emotion_str);
        }
    }
}

static void cloud_status_callback(int status) {
    cloud_service_st = status;
}

static void goldie_touch_event(int pressure, int x, int y)
{
    Window_1777432726401->handleEvent(pressure, x, y);
}

static void goldie_app_run(void)
{
    main_ui_init();
    LabelView_left->setImageBuffer((uint16_t*)&rgb16_wink_4_160_160);
    LabelView_right->setImageBuffer((uint16_t*)&rgb16_wink_4_160_160);
 // 服务初始化
    mevtservice = (EventService*)wait_service(EVENT_SERVICE_INDEX);
    if (mevtservice) {
        mevtservice->register_broadcast_recv(EVENT_BROADCAST_ADDMSG, add_msg);
    }

    cloud_service = (CloudService*)wait_service(CLOUD_SERVICE_INDEX);
    if (cloud_service) {
        cloud_service->register_status_callback(cloud_status_callback);
        cloud_service_st = cloud_service->get_status();
    }

    wifi_service = (WifiService*)wait_service(WIFI_SERVICE_INDEX);
    
    if (wifi_service) {
        for (int i = 0; i < 50; i++) {  // 等待5秒（50次 × 100ms）
            if (wifi_service->svr_sta_isConnected()) {
                wifi_config_mode = 0;  // 已连接，正常模式
                LabelView_left->setVisible(true);
                LabelView_right->setVisible(true);
                LabelView_left_word->setVisible(false);
                LabelView_right_word->setVisible(false);
                break;
            }
            goldie_msleep(100);
            if (i == 49) {
                wifi_config_mode = 1;  // 5秒后仍未连接，进入配网模式
                LabelView_left->setVisible(false);
                LabelView_right->setVisible(false);
                LabelView_left_word->setVisible(true);
                LabelView_right_word->setVisible(true);
                char ap_ssid[] = "xiaohe";
                char ap_password[] = "12345678";
                wifi_service->svr_softap_config(ap_ssid, ap_password);
                wifi_service->trigger_event(WIFI_EVENT_SOFTAP_ENABLE, NULL);
            }
        }
    } else {
        goldie_msleep(50);
        wifi_config_mode = 1;  // 没有WiFi服务，直接进入配网模式
        LabelView_left->setVisible(true);
        LabelView_right->setVisible(true);
        LabelView_left_word->setVisible(false);
        LabelView_right_word->setVisible(false);
        char ap_ssid[] = "xiaohe";
        char ap_password[] = "12345678";
        wifi_service->svr_softap_config(ap_ssid, ap_password);
        wifi_service->trigger_event(WIFI_EVENT_SOFTAP_ENABLE, NULL);
    }

    goldie_thread_lock();
    task_handle = goldie_thread_create((goldie_thread_handler)eye_img_task, 0, 
                                       "eye_img_task", 0x1000);
    if (task_handle) {
    goldie_thread_set_priority(task_handle, 24);  // 设置线程优先级
    }
    goldie_thread_unlock();
}

static void goldie_app_suspend(void)
{
    window_suspend();
}

static void goldie_app_resume(void)
{
    window_resume();
    
}

static void goldie_app_exit(void)
{
    window_exit();
    // 销毁线程资源
    if (task_handle != NULL) {
        goldie_thread_destroy(task_handle);
        task_handle = NULL;
    }
}

static void goldie_keyboard_event(int pressure, int key);

static App_t dualscreen_ai_app = {
    "dualscreen_ai",       // app_name char*
    goldie_app_run,       // h_app_run
    goldie_app_exit,      // h_app_exit
    goldie_app_suspend,   // h_app_suspend
    goldie_app_resume,    // h_app_resume
    goldie_touch_event,   // h_touch_event
    goldie_keyboard_event,// h_keyboard_event
    (uint16_t*)gImage_default_icon,             
};

static void goldie_keyboard_event(int pressure, int key)
{
    static unsigned int ts[5] = {0};
    static unsigned char count = 0;

    // 只监测左键（HOME键）按下
    if (key == 301 && pressure == 1) {
        goldie_timeval tv;
        goldie_gettimeofday(&tv);
        unsigned int now_ms = (unsigned int)(tv.tv_sec * 1000 + tv.tv_usec / 1000);

        // 超时重置：首次按下 或 距第一次按下超过 3000ms
        if (count == 0 || (now_ms - ts[0] > 3000)) {
            count = 0;
        }

        ts[count] = now_ms;
        count++;

        if (count >= 5) {
            count = 0;  // 重置计数

            // 1. 断开云服务
            if (cloud_service == NULL) {
                cloud_service = (CloudService*)wait_service(CLOUD_SERVICE_INDEX);
            }
            if (cloud_service != NULL) {
                cloud_service->triger_event(CLOUD_EVENT_STOP);
                printf("[DualScreen] 5-click -> cloud service stopped\n");
            }

            // 2. 重启 WiFi
            if (wifi_service == NULL) {
                wifi_service = (WifiService*)wait_service(WIFI_SERVICE_INDEX);
            }
            if (wifi_service != NULL) {
                  // 记录当前连接的WiFi名称
                if (wifi_service->svr_sta_isConnected()) {
                    char* name = wifi_service->svr_sta_connection_name();
                    if (name) {
                        strncpy(wifi_ssid_before_config, name, sizeof(wifi_ssid_before_config) - 1);
                        printf("[DualScreen] Record current WiFi: %s\n", wifi_ssid_before_config);
                    }
                } else {
                    wifi_ssid_before_config[0] = '\0';  // 未连接，清空
                }
                // 3. 启动 SoftAP 模式
                char ap_ssid[] = "xiaohe";
                char ap_password[] = "12345678";
                wifi_service->svr_softap_config(ap_ssid, ap_password);
                wifi_service->trigger_event(WIFI_EVENT_SOFTAP_ENABLE, NULL);
                printf("[DualScreen] 5-click -> SoftAP started: SSID=%s, PASS=%s\n", ap_ssid, ap_password);
                LabelView_left->setVisible(false);
                LabelView_right->setVisible(false);
                LabelView_left_word->setVisible(true);
                LabelView_right_word->setVisible(true);
                wifi_config_mode = 1;
            }
              
        }
        
    }
}

static void dualscreen_ai_entry(void)
{
    install_app(&dualscreen_ai_app);
}

GOLDIE_INIT_CALL_(dualscreen_ai_entry);
