/**
 * @file convai_bridge.h
 * @brief Thin integration layer: goldieos apps -> ConvAI SDK public API.
 *
 * Thin integration layer: goldieos apps -> ConvAI SDK public API.
 * Transport/protocol are stubs; key API calls log to stdout.
 */
#ifndef CONVAI_BRIDGE_H
#define CONVAI_BRIDGE_H

#include "convai/convai_api.h"

#ifdef __cplusplus
extern "C" {
#endif

/* ---- Service index (CONVAI_SERVICE_INDEX = 4) ---- */
#define CONVAI_BRIDGE_SERVICE_INDEX  4

/* ---- Lifecycle ---- */

/**
 * Create an engine with default config and logging callbacks.
 * Registers itself as CONVAI_BRIDGE_SERVICE_INDEX in the service manager.
 */
void convai_bridge_init(void);

/**
 * Start the engine session (wake-up / begin conversation).
 * Logs the call; transport connect is stubbed.
 */
int  convai_bridge_start(void);

/**
 * Stop the engine session (sleep / end conversation).
 */
int  convai_bridge_stop(void);

/**
 * Restart: stop + start.
 */
int  convai_bridge_restart(void);

/* ---- Accessors ---- */

/** Get the engine handle for direct SDK calls. */
convai_engine_t convai_bridge_get_engine(void);

/** Get current agent status (mapped from on_convai_conversation_status). */
convai_status_e convai_bridge_get_status(void);

/** Non-zero if agent is currently speaking. */
int convai_bridge_is_speaking(void);

/** Opaque audio source handle (AudioService from goldieos). */
typedef void convai_audio_source_t;

/**
 * Set the audio source for automatic mic recording during sessions.
 * Must be called before convai_bridge_start(). Pass NULL to disable.
 * When set, start() spawns a background thread that reads PCM from
 * the source and feeds it to convai_send_audio_data().
 */
void convai_bridge_set_audio_source(convai_audio_source_t *src,
                                    int sample_rate, int channels, int bits);

/**
 * Send a PCM audio frame to the agent.
 * Logs the call; actual network send is stubbed.
 */
int convai_bridge_send_audio(const uint8_t *data, size_t len,
                             const convai_audio_frame_info_t *info);

/* ---- Callback types (for apps that need status notifications) ---- */
typedef void (*convai_bridge_status_cb)(convai_status_e status);
typedef void (*convai_bridge_event_cb)(convai_event_code_e event_type, const char *info);
typedef void (*convai_bridge_message_cb)(const char *message);

/** Register callbacks for status changes, connection events, and emotion updates. */
void convai_bridge_on_status(convai_bridge_status_cb cb);
void convai_bridge_on_event(convai_bridge_event_cb cb);
void convai_bridge_on_message(convai_bridge_message_cb cb);

/**
 * Set / get the startup config JSON passed to convai_start() via
 * opt.config_json.  Call set() before start() to supply the AI
 * personality/voice configuration generated by the settings UI.
 * Returns NULL if no config has been set.
 */
void convai_bridge_set_startup_config(const char *config);
const char *convai_bridge_get_startup_config(void);

#ifdef __cplusplus
}
#endif

#endif /* CONVAI_BRIDGE_H */