/*This file is automatically generated by the tinyui tool 
and contains the main_ui. h file, which calls the initialization 
function main_ui_init() to create the UI interface. You need to 
add code related to business logic here..*/
#include "main_ui.h"
#include "default_app_icon.h" 
// 包含所有电源图片头文件
#include "rgb16_charge1_64_27.h"
#include "rgb16_charge2_64_27.h"
#include "rgb16_charge3_64_27.h"
#include "rgb16_charge4_64_27.h"
#include "rgb16_charge5_64_27.h"
#include "goldie_thread.h"

extern "C" { 
#include "goldie_osal.h" 
#include "service_manager.h" 
#include "driver_manager.h" 
#include "app_manager.h" 
} 

// 图片切换相关变量
static void* image_switch_thread = NULL;
static volatile int thread_running = 0;
static int current_image_index = 5; // 当前图片索引 (1-5)


// 图片切换线程函数
static int image_switch_thread_func(void* data)
{
    (void)data;
    goldie_msleep(500);
    while (thread_running) {
        // 切换到下一张图片
        current_image_index++;
        if (current_image_index > 5) {
            current_image_index = 1;
        }
        
        // 根据当前索引更新图片显示
        if (LabelView_img) {
            switch (current_image_index) {
                case 1:
                    LabelView_img->setImageBuffer((uint16_t*)&rgb16_charge1_64_27);
                    break;
                case 2:
                    LabelView_img->setImageBuffer((uint16_t*)&rgb16_charge2_64_27);
                    break;
                case 3:
                    LabelView_img->setImageBuffer((uint16_t*)&rgb16_charge3_64_27);
                    break;
                case 4:
                    LabelView_img->setImageBuffer((uint16_t*)&rgb16_charge4_64_27);
                    break;
                case 5:
                    LabelView_img->setImageBuffer((uint16_t*)&rgb16_charge5_64_27);
                    break;
                default:
                    LabelView_img->setImageBuffer((uint16_t*)&rgb16_charge1_64_27);
                    break;
            }
            // 刷新控件显示
            LabelView_img->flush(0, 0, 64, 27);
        }

        // 等待一段时间
        goldie_msleep(1000);
    }
    
    return 0;
}

// 启动图片切换线程
static void start_image_switch_thread(void)
{   
    thread_running = 1;
    image_switch_thread = goldie_thread_create(image_switch_thread_func, NULL, "charging_only", 2048);
}

// 停止图片切换线程
static void stop_image_switch_thread(void)
{    
    thread_running = 0;
    if (image_switch_thread) {
        goldie_thread_destroy(image_switch_thread);
        image_switch_thread = NULL;
    }
}

static void goldie_touch_event(int pressure, int x, int y)
{
    Window_1775700353792->handleEvent(pressure, x, y);
}

static void goldie_app_run(void)
{
    main_ui_init();
    
    printf("[charging_only] App started\n");
    
    // 启动图片切换线程
    start_image_switch_thread();
    printf("[charging_only] Image switch thread started\n");
}

static void goldie_app_suspend(void)
{
    window_suspend();
    // 暂停时停止图片切换线程
    stop_image_switch_thread();
}

static void goldie_app_resume(void)
{
    window_resume();
    // 恢复时重新启动图片切换线程
    start_image_switch_thread();
}

static void goldie_app_exit(void)
{
    
    // 停止图片切换线程
    stop_image_switch_thread();
    window_exit();
}

static void goldie_keyboard_event(int pressure, int key);

static App_t charging_only = {
    "charging_only",       // app_name char*
    goldie_app_run,       // h_app_run
    goldie_app_exit,      // h_app_exit
    goldie_app_suspend,   // h_app_suspend
    goldie_app_resume,    // h_app_resume
    goldie_touch_event,   // h_touch_event
    nullptr,// h_keyboard_event
    nullptr,             
};

static void goldie_keyboard_event(int pressure, int key)
{
    if((key == SYSTEM_KEY_VALUE_BACK) && (pressure == 1))
    {
        goldie_exit_app(&charging_only);
    }
}

static void test_entry(void)
{
    install_app(&charging_only);
}

GOLDIE_INIT_CALL_(test_entry);