/*This file is automatically generated by the tinyui tool and should not be modified.*/
#ifndef INCLUDE_MAIN_UI_H
#define INCLUDE_MAIN_UI_H
#include <memory>
#include <vector>

#include "goldie_display.h" 
// 控件头文件
#include "label_view.h"
#include "frame_view.h"
#include "window.h"

// 图片头文件
#include "rgb16_light_32_25.h"
#include "rgb16_charge5_64_27.h"

// 掩码头文件
#include "round_rect_32_25_r1_boundary.h"
#include "round_rect_64_27_r1_boundary.h"
#include "round_rect_320_240_r1_boundary.h"
// 全局控件变量定义
static std::shared_ptr<LabelView> LabelView_light;
static std::shared_ptr<LabelView> LabelView_img;
static std::shared_ptr<FrameView> FrameView_1775700381905;
static std::shared_ptr<Window> Window_1775700353792;

static void main_ui_init()
{
    LabelView_light = std::make_shared<LabelView>(32, 25);
    LabelView_light->setColor(0x0000);
    LabelView_light->setTextColor(0);
    LabelView_light->setBoundaryBuffer(round_rect_32_25_r1_boundary);
    LabelView_light->setVisible(true);
    LabelView_light->setImageBuffer((uint16_t*)&rgb16_light_32_25);

    LabelView_img = std::make_shared<LabelView>(64, 27);
    LabelView_img->setColor(0x0000);
    LabelView_img->setTextColor(0);
    LabelView_img->setBoundaryBuffer(round_rect_64_27_r1_boundary);
    LabelView_img->setVisible(true);
    LabelView_img->setImageBuffer((uint16_t*)&rgb16_charge5_64_27);

    FrameView_1775700381905 = std::make_shared<FrameView>(320, 240);
    FrameView_1775700381905->setColor(0x0000);
    FrameView_1775700381905->setTextColor(0);
    FrameView_1775700381905->setBoundaryBuffer(round_rect_320_240_r1_boundary);
    FrameView_1775700381905->setVisible(true);

    Window_1775700353792 = std::make_shared<Window>(APP_WINDOW_START_X, APP_WINDOW_START_Y,320, 240);
    Window_1775700353792->setColor(0x0000);
    Window_1775700353792->setTextColor(0);
    Window_1775700353792->setVisible(true);

    // 建立控件父子关系
    FrameView_1775700381905->addView(LabelView_img, 128.0, 96);
    FrameView_1775700381905->addView(LabelView_light, 144.0, 130);
    Window_1775700353792->addView(FrameView_1775700381905, 0.0, 0);

    // 刷新窗口
    Window_1775700353792->flush(0, 0, APP_WINDOW_WIDTH, APP_WINDOW_HEIGHT);
}

static void window_exit(void)
{
    LabelView_light.reset();
    LabelView_img.reset();
    FrameView_1775700381905->removeAllChilds();
    FrameView_1775700381905.reset();
    Window_1775700353792->setVisible(false);
    Window_1775700353792->removeAllViews();
    Window_1775700353792.reset();
}

static void window_suspend(void)
{
    Window_1775700353792->setVisible(false);
}

static void window_resume(void)
{
    Window_1775700353792->setVisible(true);
    Window_1775700353792->flush(0, 0, APP_WINDOW_WIDTH, APP_WINDOW_HEIGHT);
}

#endif //INCLUDE_MAIN_UI_H 

