/*This file is automatically generated by the tinyui tool 
and contains the main_ui. h file, which calls the initialization 
function main_ui_init() to create the UI interface. You need to 
add code related to business logic here..*/
#include "main_ui.h"
#include "default_app_icon.h" 
#include <vector>
#include <string>
#include <cstdio>
#include <fstream>
#include <sstream>
#include "rgb16_clock_56_56.h"
extern "C" { 
#include "goldie_osal.h" 
#include "service_manager.h" 
#include "app_manager.h" 
#include "audio_service.h"  // 添加音频服务头文件
#include "sdcard_service.h" // 添加SD卡服务头文件
#include "ntp_service.h"    // 添加NTP服务头文件
} 

// 闹钟服务指针
static AlarmService* alarm_service = NULL;

// 当前正在编辑的闹钟索引（-1表示新建闹钟）
static int current_edit_index = -1;

// 全局变量保存当前编辑的时间（用于UI显示）
static std::string current_time = "12:00"; // 默认时间改为12:00

// 闹钟列表（用于UI显示）
static std::vector<AlarmInfo> alarm_list_for_display;

// 获取闹钟服务
static AlarmService* get_alarm_service() {
    if (alarm_service == NULL) {
        alarm_service = (AlarmService*)get_service(ALARM_SERVICE_INDEX);
        if (alarm_service == NULL) {
            printf("[Alarm] Failed to get alarm service\n");
        }
    }
    return alarm_service;
}

// 从服务加载闹钟列表
static void load_alarms_from_service() {
    AlarmService* service = get_alarm_service();
    if (service == NULL) {
        printf("[Alarm] Cannot load alarms: service not available\n");
        return;
    }
    
    // 清空当前列表
    alarm_list_for_display.clear();
    
    // 从服务获取闹钟列表
    AlarmInfo alarm_buffer[10]; // 最大10个闹钟
    int count = service->get_alarm_list(alarm_buffer, 10);
    
    if (count > 0) {
        for (int i = 0; i < count; i++) {
            alarm_list_for_display.push_back(alarm_buffer[i]);
        }
        printf("[Alarm] Loaded %d alarms from service\n", count);
    } else {
        printf("[Alarm] No alarms loaded from service (count=%d)\n", count);
    }
}

// 从字符串时间解析小时和分钟
static void parse_time_string(const std::string& time_str, char* hour, char* min) {
    if (time_str.length() >= 5 && time_str[2] == ':') {
        *hour = (char)std::stoi(time_str.substr(0, 2));
        *min = (char)std::stoi(time_str.substr(3, 2));
    } else {
        *hour = 12;
        *min = 0;
    }
}

// 将小时和分钟格式化为字符串
static std::string format_time_string(char hour, char min) {
    char time_str[6];
    snprintf(time_str, sizeof(time_str), "%02d:%02d", hour, min);
    return std::string(time_str);
}

// 更新ListView显示
static void update_listview_display() {
    if (!ListView_clock) {
        printf("[Alarm] ListView_clock is null\n");
        return;
    }
    
    // 清空ListView
    ListView_clock->clearItems();
    
    // 添加所有闹钟到ListView
    for (size_t i = 0; i < alarm_list_for_display.size(); i++) {
        const AlarmInfo& alarm = alarm_list_for_display[i];
        std::string item_text = format_time_string(alarm.m_hour, alarm.m_min) + " " + (alarm.enabled ? "开启" : "关闭");
        ListView_clock->addItem(item_text.c_str(), i); // 使用索引作为itemId
    }
    
    printf("[Alarm] ListView updated with %zu alarms\n", alarm_list_for_display.size());
}

// 获取当前正在编辑的闹钟（如果current_edit_index为-1，返回一个临时闹钟）
static AlarmInfo& get_current_alarm() {
    static AlarmInfo temp_alarm;
    if (current_edit_index >= 0 && current_edit_index < (int)alarm_list_for_display.size()) {
        return alarm_list_for_display[current_edit_index];
    }
    return temp_alarm;
}

static void on_back_click(void*);
// 更新UI显示的时间
static void update_time_display() {
    if (TextEditView_set_time) {
        TextEditView_set_time->setText(current_time.c_str());
        Window_1770348934687->flush(0, 0, APP_WINDOW_WIDTH, APP_WINDOW_HEIGHT);
        printf("[Alarm] Update display to: %s\n", current_time.c_str());
    }
}

// 开关按钮回调函数
static void on_switch_click(void* id) {
    if (ImgButtonView_set_switch) {
        AlarmInfo& current_alarm = get_current_alarm();
        
        if (ImgButtonView_set_switch->isLocked()) {
            current_alarm.enabled = true;
            ImgButtonView_set_switch->setLocked(true);
            printf("[Alarm] Switch turned OFF\n");
        } else {
            current_alarm.enabled = false;
            ImgButtonView_set_switch->setLocked(false);
            printf("[Alarm] Switch turned ON\n");
        }
    }
}




// 星期选择复选框回调函数
static void on_weekday_click(void* id) {
    // 根据id确定是哪个复选框被点击
    // CheckboxView_1 到 CheckboxView_7 对应周一(0)到周日(6)
    int weekday_index = -1;
    
    if (id == CheckboxView_1->getId()) {
        weekday_index = 0; // 周一
    } else if (id == CheckboxView_2->getId()) {
        weekday_index = 1; // 周二
    } else if (id == CheckboxView_3->getId()) {
        weekday_index = 2; // 周三
    } else if (id == CheckboxView_4->getId()) {
        weekday_index = 3; // 周四
    } else if (id == CheckboxView_5->getId()) {
        weekday_index = 4; // 周五
    } else if (id == CheckboxView_6->getId()) {
        weekday_index = 5; // 周六
    } else if (id == CheckboxView_7->getId()) {
        weekday_index = 6; // 周日
    }
    
    if (weekday_index >= 0 && weekday_index < 7) {
        bool checked = false;
        // 获取复选框状态
        if (id == CheckboxView_1->getId()) {
            checked = CheckboxView_1->isChecked();
        } else if (id == CheckboxView_2->getId()) {
            checked = CheckboxView_2->isChecked();
        } else if (id == CheckboxView_3->getId()) {
            checked = CheckboxView_3->isChecked();
        } else if (id == CheckboxView_4->getId()) {
            checked = CheckboxView_4->isChecked();
        } else if (id == CheckboxView_5->getId()) {
            checked = CheckboxView_5->isChecked();
        } else if (id == CheckboxView_6->getId()) {
            checked = CheckboxView_6->isChecked();
        } else if (id == CheckboxView_7->getId()) {
            checked = CheckboxView_7->isChecked();
        }
        
        AlarmInfo& current_alarm = get_current_alarm();
        current_alarm.weekdays[weekday_index] = checked;
        printf("[Alarm] Weekday %d set to: %s\n", weekday_index + 1, checked ? "enabled" : "disabled");
    }
}

// ListView item点击回调函数
static void on_listview_item_click(int itemId) {
    printf("[Alarm] ListView item clicked: %d\n", itemId);
    
    if (itemId >= 0 && itemId < (int)alarm_list_for_display.size()) {
        // 设置当前编辑的闹钟索引
        current_edit_index = itemId;
        const AlarmInfo& alarm = alarm_list_for_display[itemId];
        
        // 更新当前编辑时间
        current_time = format_time_string(alarm.m_hour, alarm.m_min);
        
        printf("[Alarm] Editing alarm %d: time=%s, enabled=%s\n", 
               itemId, current_time.c_str(), alarm.enabled ? "true" : "false");
        
        // 隐藏主界面，显示设置界面
        FrameView_main->setVisible(false);
        FrameView_set->setVisible(true);
        
        // 更新设置界面显示
        if (TextEditView_set_time) {
            TextEditView_set_time->setText(current_time.c_str());
        }
        
        // 更新复选框状态
        CheckboxView_1->setChecked(alarm.weekdays[0]);
        CheckboxView_2->setChecked(alarm.weekdays[1]);
        CheckboxView_3->setChecked(alarm.weekdays[2]);
        CheckboxView_4->setChecked(alarm.weekdays[3]);
        CheckboxView_5->setChecked(alarm.weekdays[4]);
        CheckboxView_6->setChecked(alarm.weekdays[5]);
        CheckboxView_7->setChecked(alarm.weekdays[6]);
        
        // 更新开关状态
        if (ImgButtonView_set_switch) {
            if (alarm.enabled) {
                ImgButtonView_set_switch->setLocked(true);  // 开启状态设为锁定
            } else {
                ImgButtonView_set_switch->setLocked(false); // 关闭状态设为未锁定
            }
        }
        
        // 刷新窗口
        Window_1770348934687->flush(0, 0, APP_WINDOW_WIDTH, APP_WINDOW_HEIGHT);
    }
}

// 设置界面返回按钮回调函数 - 显示主界面，隐藏设置界面，并刷新ListView显示
static void on_set_back_click(void* nouse) {
    printf("[Alarm] Set back button clicked\n");
    
    // 获取闹钟服务
    AlarmService* service = get_alarm_service();
    if (service == NULL) {
        printf("[Alarm] Cannot save alarm: service not available\n");
        return;
    }
    
    // 更新当前编辑的闹钟数据
    if (current_edit_index >= 0 && current_edit_index < (int)alarm_list_for_display.size()) {
        AlarmInfo& alarm = alarm_list_for_display[current_edit_index];
        
        // 解析时间字符串
        char hour, min;
        parse_time_string(current_time, &hour, &min);
        alarm.m_hour = hour;
        alarm.m_min = min;
        
        // 从UI获取复选框状态
        alarm.weekdays[0] = CheckboxView_1->isChecked();
        alarm.weekdays[1] = CheckboxView_2->isChecked();
        alarm.weekdays[2] = CheckboxView_3->isChecked();
        alarm.weekdays[3] = CheckboxView_4->isChecked();
        alarm.weekdays[4] = CheckboxView_5->isChecked();
        alarm.weekdays[5] = CheckboxView_6->isChecked();
        alarm.weekdays[6] = CheckboxView_7->isChecked();
        
        printf("[Alarm] Alarm %d updated: time=%s, enabled=%s\n", 
               current_edit_index, current_time.c_str(), alarm.enabled ? "true" : "false");
        
        // 调用服务接口更新闹钟
        int ret = service->update_alarm(current_edit_index, &alarm);
        if (ret != 0) {
            printf("[Alarm] Failed to update alarm in service, error=%d\n", ret);
        } else {
            printf("[Alarm] Alarm updated in service successfully\n");
        }
    }
    
    // 重新从服务加载闹钟列表以确保数据同步
    load_alarms_from_service();
    
    // 更新ListView显示
    update_listview_display();
    
    // 显示主界面，隐藏设置界面
    FrameView_set->setVisible(false);
    FrameView_main->setVisible(true);
    Window_1770348934687->flush(0, 0, APP_WINDOW_WIDTH, APP_WINDOW_HEIGHT);
    
    printf("[Alarm] Returned to main frame from setting\n");
}

// 删除当前闹钟按钮回调函数（从列表中移除）
static void on_delete_click(void*) {
    printf("[Alarm] Delete current alarm button clicked\n");
    
    // 获取闹钟服务
    AlarmService* service = get_alarm_service();
    if (service == NULL) {
        printf("[Alarm] Cannot delete alarm: service not available\n");
        return;
    }
    
    // 检查当前是否有正在编辑的闹钟
    if (current_edit_index >= 0 && current_edit_index < (int)alarm_list_for_display.size()) {
        printf("[Alarm] Deleting alarm at index %d\n", current_edit_index);
        
        // 从服务中删除闹钟（按索引删除）
        int ret = service->del_alarm(current_edit_index);
        if (ret != 0) {
            printf("[Alarm] Failed to delete alarm from service, error=%d\n", ret);
        }
        
        // 重新从服务加载闹钟列表以确保数据同步
        load_alarms_from_service();
        
        // 重置当前编辑索引
        current_edit_index = -1;
        current_time = "12:00"; // 重置为默认时间
        
        printf("[Alarm] Alarm deleted, remaining alarms: %zu\n", alarm_list_for_display.size());
        
        // 更新ListView显示
        update_listview_display();
        
        // 返回到主界面
        FrameView_set->setVisible(false);
        FrameView_main->setVisible(true);
        Window_1770348934687->flush(0, 0, APP_WINDOW_WIDTH, APP_WINDOW_HEIGHT);
        
        printf("[Alarm] Returned to main frame after deletion\n");
    } else {
        printf("[Alarm] No alarm to delete\n");
    }
}

// 添加闹钟按钮点击回调函数
static void on_add_clock_click(void*)
{
    printf("[Alarm] Add clock button clicked\n");
    
    // 获取闹钟服务
    AlarmService* service = get_alarm_service();
    if (service == NULL) {
        printf("[Alarm] Cannot add alarm: service not available\n");
        return;
    }
    
    // 检查闹钟数量是否已达到上限（10个）
    if (alarm_list_for_display.size() >= 10) {
        printf("[Alarm] Cannot add more alarms, maximum limit (10) reached\n");
        // 可以在这里显示一个提示消息给用户
        return;
    }
    
    // 创建新的闹钟
    AlarmInfo new_alarm;
    new_alarm.enabled = false; // 默认关闭状态
    new_alarm.m_hour = 12;     // 默认小时
    new_alarm.m_min = 0;       // 默认分钟
    new_alarm.ring_index = 0;  // 默认铃声索引
    for (int i = 0; i < 7; i++) {
        new_alarm.weekdays[i] = true;
    }
    
    // 添加到服务
    int added_index = service->add_alarm(&new_alarm);
    if (added_index < 0) {
        printf("[Alarm] Failed to add alarm to service, error=%d\n", added_index);
        return;
    }
    
    printf("[Alarm] New alarm added at index %d\n", added_index);
    
    // 重新从服务加载闹钟列表以确保数据同步
    load_alarms_from_service();
    
    // 设置当前编辑索引为新添加的闹钟索引
    current_edit_index = added_index;
    current_time = "12:00"; // 重置当前编辑时间为默认值
    
    printf("[Alarm] Editing new alarm at index %d, total alarms: %zu\n", 
           current_edit_index, alarm_list_for_display.size());
    
    // 隐藏主界面，显示设置界面
    FrameView_main->setVisible(false);
    FrameView_set->setVisible(true);
    
    // 重置设置界面到默认状态
    if (TextEditView_set_time) {
        TextEditView_set_time->setText("12:00");
    }
    
    // 更新开关状态
    if (ImgButtonView_set_switch) {
        if (new_alarm.enabled) {
            ImgButtonView_set_switch->setLocked(true);
        } else {
            ImgButtonView_set_switch->setLocked(false);
        }
    }
    
    // 重置复选框状态
    CheckboxView_1->setChecked(true);
    CheckboxView_2->setChecked(true);
    CheckboxView_3->setChecked(true);
    CheckboxView_4->setChecked(true);
    CheckboxView_5->setChecked(true);
    CheckboxView_6->setChecked(true);
    CheckboxView_7->setChecked(true);
    
    // 刷新窗口
    Window_1770348934687->flush(0, 0, APP_WINDOW_WIDTH, APP_WINDOW_HEIGHT);
}

// // 小时增加按钮回调函数
// static void on_add_1_click(void*)
// {    
//     // 使用全局变量更新小时
//     if (current_time.length() >= 5) {
//         // 提取小时部分
//         std::string hour_str = current_time.substr(0, 2);
//         int hour = std::stoi(hour_str);
//         printf("[Alarm] Current hour: %d\n", hour);
        
//         // 小时加1，超过23变成0（循环）
//         hour++;
//         if (hour > 23) {
//             hour = 0;
//         }
        
//         // 更新全局时间变量
//         char new_hour_str[3];
//         snprintf(new_hour_str, sizeof(new_hour_str), "%02d", hour);
//         current_time = std::string(new_hour_str) + current_time.substr(2);
//         printf("[Alarm] New time: %s\n", current_time.c_str());
        
//         // 更新UI显示
//         update_time_display();
//     }
// }

// // 小时减少按钮回调函数
// static void on_dec_1_click(void*)
// {  
//     // 使用全局变量更新小时
//     if (current_time.length() >= 5) {
//         // 提取小时部分
//         std::string hour_str = current_time.substr(0, 2);
//         int hour = std::stoi(hour_str);
//         printf("[Alarm] Current hour: %d\n", hour);
        
//         // 小时减1，超过0变成23（循环）
//         hour--;
//         if (hour < 0) {
//             hour = 23;
//         }
        
//         // 更新全局时间变量
//         char new_hour_str[3];
//         snprintf(new_hour_str, sizeof(new_hour_str), "%02d", hour);
//         current_time = std::string(new_hour_str) + current_time.substr(2);
//         printf("[Alarm] New time: %s\n", current_time.c_str());
        
//         // 更新UI显示
//         update_time_display();
//     }
// }

// // 分钟增加按钮回调函数
// static void on_add_2_click(void*)
// {   
//     // 使用全局变量更新分钟
//     if (current_time.length() >= 5) {
//         // 提取分钟部分
//         std::string minute_str = current_time.substr(3, 2);
//         int minute = std::stoi(minute_str);
//         printf("[Alarm] Current minute: %d\n", minute);
        
//         // 分钟加1，超过59变成0（循环）
//         minute++;
//         if (minute > 59) {
//             minute = 0;
//         }
        
//         // 更新全局时间变量
//         char new_minute_str[3];
//         snprintf(new_minute_str, sizeof(new_minute_str), "%02d", minute);
//         current_time = current_time.substr(0, 3) + std::string(new_minute_str);
//         printf("[Alarm] New time: %s\n", current_time.c_str());
        
//         // 更新UI显示
//         update_time_display();
//     }
// }

// // 分钟减少按钮回调函数
// static void on_dec_2_click(void*)
// {
//     // 使用全局变量更新分钟
//     if (current_time.length() >= 5) {
//         // 提取分钟部分
//         std::string minute_str = current_time.substr(3, 2);
//         int minute = std::stoi(minute_str);
//         printf("[Alarm] Current minute: %d\n", minute);
        
//         // 分钟减1，超过0变成59（循环）
//         minute--;
//         if (minute < 0) {
//             minute = 59;
//         }
        
//         // 更新全局时间变量
//         char new_minute_str[3];
//         snprintf(new_minute_str, sizeof(new_minute_str), "%02d", minute);
//         current_time = current_time.substr(0, 3) + std::string(new_minute_str);
//         printf("[Alarm] New time: %s\n", current_time.c_str());
        
//         // 更新UI显示
//         update_time_display();
//     }
// }

// ListView_sethour 点击回调函数 (设置小时)
static void on_hour_list_click(int itemId) {
    // itemId 对应 0-23
    printf("[Alarm] Hour list item clicked: %d\n", itemId);
    
    if (current_time.length() >= 5) {
        // 格式化新的小时部分
        char new_hour_str[3];
        snprintf(new_hour_str, sizeof(new_hour_str), "%02d", itemId);
        // 替换原时间字符串的小时部分
        current_time = std::string(new_hour_str) + current_time.substr(2);
        
        printf("[Alarm] New time after hour change: %s\n", current_time.c_str());
        // 更新UI显示
        update_time_display();
    }
}

// ListView_setmin 点击回调函数 (设置分钟)
static void on_minute_list_click(int itemId) {
    // itemId 对应 0-59
    printf("[Alarm] Minute list item clicked: %d\n", itemId);
    
    if (current_time.length() >= 5) {
        // 格式化新的分钟部分
        char new_min_str[3];
        snprintf(new_min_str, sizeof(new_min_str), "%02d", itemId);
        // 替换原时间字符串的分钟部分
        current_time = current_time.substr(0, 3) + std::string(new_min_str);
        
        printf("[Alarm] New time after minute change: %s\n", current_time.c_str());
        // 更新UI显示
        update_time_display();
    }
}


static void goldie_touch_event(int pressure, int x, int y)
{
    Window_1770348934687->handleEvent(pressure, x, y);
}

static void goldie_app_run(void)
{
    // 获取闹钟服务
    AlarmService* service = get_alarm_service();
    if (service == NULL) {
        printf("[Alarm] Alarm service not available, UI may not work properly\n");
    } else {
        // 初始化服务
        service->init();
        // 从服务加载闹钟列表
        load_alarms_from_service();
    }
    
    main_ui_init();
    
    // 初始化ListView显示 - 显示从服务加载的闹钟列表
    update_listview_display();
    
    // 为添加闹钟按钮设置点击事件
    ButtonView_add_clock->setOnClick(on_add_clock_click);
    
    // // 为时间调整按钮设置点击事件
    // ButtonView_add_1->setOnClick(on_add_1_click);
    // ButtonView_dec_1->setOnClick(on_dec_1_click);
    // ButtonView_add_2->setOnClick(on_add_2_click);
    // ButtonView_dec_2->setOnClick(on_dec_2_click);
    
    // 为开关按钮设置点击事件
    if (ImgButtonView_set_switch) {
        ImgButtonView_set_switch->setOnClick(on_switch_click);
    }
    
    // 为星期选择复选框设置点击事件
    CheckboxView_1->setOnClick(on_weekday_click);
    CheckboxView_2->setOnClick(on_weekday_click);
    CheckboxView_3->setOnClick(on_weekday_click);
    CheckboxView_4->setOnClick(on_weekday_click);
    CheckboxView_5->setOnClick(on_weekday_click);
    CheckboxView_6->setOnClick(on_weekday_click);
    CheckboxView_7->setOnClick(on_weekday_click);
    
    // 为删除闹钟按钮设置点击事件（从列表中移除闹钟）
    if (ButtonView_delete) {
        ButtonView_delete->setOnClick(on_delete_click);
    }
    

    
    // 为设置界面返回按钮设置点击事件
    if (ButtonView_set_back) {
        ButtonView_set_back->setOnClick(on_set_back_click);
    }
    
    // 为ListView设置item点击回调
    if (ListView_clock) {
        ListView_clock->setOnItemClick(on_listview_item_click);
    }

    // 为闹钟设置界面的小时和分钟列表添加点击回调
    if (ListView_sethour) {
        ListView_sethour->setOnItemClick(on_hour_list_click);
    }
    
    if (ListView_setmin) {
        ListView_setmin->setOnItemClick(on_minute_list_click);
    }

    // 检查是否有活跃闹钟（闹钟正在响铃），有则直接跳转到对应的设置界面
    if (service != NULL) {
        int mindex = service->get_actived_alarm();
        if (mindex >= 0) {
            on_listview_item_click(mindex);
        }
    }
    
    printf("[Alarm] All callbacks registered, %zu alarms displayed\n", alarm_list_for_display.size());
}

static void goldie_app_suspend(void)
{
    window_suspend();
}

static void goldie_app_resume(void)
{
    window_resume();
     // 检查是否有活跃闹钟（闹钟正在响铃），有则直接跳转到对应的设置界面
    AlarmService* service = get_alarm_service();
    if (service != NULL) {
        load_alarms_from_service();
        update_listview_display();
        
        int mindex = service->get_actived_alarm();
        if (mindex >= 0) {
            on_listview_item_click(mindex);
        }
    }
}

static void goldie_app_exit(void)
{
    // 注意：闹钟数据由服务管理，不需要应用保存
    window_exit();
}

static void goldie_keyboard_event(int pressure, int key);

static App_t alarm = {
    "闹钟",       // app_name char*
    goldie_app_run,       // h_app_run
    goldie_app_exit,      // h_app_exit
    goldie_app_suspend,   // h_app_suspend
    goldie_app_resume,    // h_app_resume
    goldie_touch_event,   // h_touch_event
    goldie_keyboard_event,// h_keyboard_event
    (uint16_t*)rgb16_clock_56_56,             
};

// 返回按钮回调函数 - 返回到上一级界面
static void on_back_click(void*) {
    goldie_exit_app(&alarm);
	if(alarm_service){
		alarm_service->cancel_alarm();
	}
}

static void goldie_keyboard_event(int pressure, int key)
{
    if((key == SYSTEM_KEY_VALUE_BACK) && (pressure == 1))
    {
    	printf("goldie_keyboard_event %p \r\n",FrameView_set);
    	if(FrameView_set&&FrameView_set->isVisible())
    	{
		on_set_back_click(NULL);
	}else{
        		goldie_exit_app(&alarm);
		if(alarm_service){
			alarm_service->cancel_alarm();
		}
	}
    }
}

static void test_entry(void)
{
    install_app(&alarm);
}

GOLDIE_INIT_CALL_(test_entry);
