/*This file is automatically generated by the tinyui tool and should not be modified.*/
#ifndef INCLUDE_MAIN_UI_H
#define INCLUDE_MAIN_UI_H
#include <memory>
#include <vector>

#include "goldie_display.h" 
// 控件头文件
#include "imgbutton_view.h"
#include "button_view.h"
#include "textedit_view.h"
#include "checkbox_view.h"
#include "frame_view.h"
#include "list_view.h"
#include "window.h"

// 图片头文件
#include "rgb16_add1_40_28.h"
#include "rgb16_add1_40_28.h"
#include "rgb16_back3_48_24.h"
#include "rgb16_switch_64_19.h"
#include "rgb16_minus_40_28.h"
#include "rgb16_minus_40_28.h"
#include "rgb16_switch_pressed_pressed_56_24.h"
#include "rgb16_switch_released_56_24.h"

// 掩码头文件
#include "round_rect_56_24_r5_boundary.h"
#include "round_rect_112_26_r2_boundary.h"
#include "round_rect_40_28_r1_boundary.h"
#include "round_rect_40_27_r1_boundary.h"
#include "round_rect_40_28_r1_boundary.h"
#include "ellipse_32_29_boundary.h"
#include "round_rect_48_24_r1_boundary.h"
#include "round_rect_72_25_r1_boundary.h"
#include "round_rect_272_32_r3_boundary.h"
#include "round_rect_64_19_r0_boundary.h"
#include "round_rect_72_25_r1_boundary.h"
#include "round_rect_272_26_r3_boundary.h"
#include "round_rect_40_28_r1_boundary.h"
#include "round_rect_40_28_r1_boundary.h"
#include "ellipse_32_29_boundary.h"
#include "ellipse_32_29_boundary.h"
#include "ellipse_32_29_boundary.h"
#include "ellipse_32_29_boundary.h"
#include "ellipse_32_29_boundary.h"
#include "ellipse_32_29_boundary.h"
#include "round_rect_56_25_r1_boundary.h"
#include "ellipse_24_24_boundary.h"
#include "round_rect_272_34_r4_boundary.h"
#include "round_rect_272_104_r1_boundary.h"
#include "round_rect_272_40_r2_boundary.h"
// 全局控件变量定义
static std::shared_ptr<ListView> ListView_sethour;
static std::shared_ptr<ListView> ListView_setmin;
static std::shared_ptr<ButtonView> ButtonView_delete;
static std::shared_ptr<TextEditView> TextEditView_set_time;
static std::shared_ptr<CheckboxView> CheckboxView_1;
static std::shared_ptr<ButtonView> ButtonView_set_back;
static std::shared_ptr<TextEditView> TextEditView_1770369232635;
static std::shared_ptr<FrameView> FrameView_set_top;
static std::shared_ptr<ImgButtonView> ImgButtonView_set_switch;
static std::shared_ptr<TextEditView> TextEditView_1770369580146;
static std::shared_ptr<FrameView> FrameView_switch;
static std::shared_ptr<CheckboxView> CheckboxView_2;
static std::shared_ptr<CheckboxView> CheckboxView_3;
static std::shared_ptr<CheckboxView> CheckboxView_4;
static std::shared_ptr<CheckboxView> CheckboxView_5;
static std::shared_ptr<CheckboxView> CheckboxView_7;
static std::shared_ptr<CheckboxView> CheckboxView_6;
static std::shared_ptr<FrameView> FrameView_set;
static std::shared_ptr<TextEditView> TextEditView_top;
static std::shared_ptr<ButtonView> ButtonView_back;
static std::shared_ptr<FrameView> FrameView_top;
static std::shared_ptr<ListView> ListView_clock;
static std::shared_ptr<ButtonView> ButtonView_add_clock;
static std::shared_ptr<FrameView> FrameView_main;
static std::shared_ptr<Window> Window_1770348934687;

static void main_ui_init()
{
    


    ButtonView_delete = std::make_shared<ButtonView>(112, 26);
    ButtonView_delete->setColor(0x8AFA);
    ButtonView_delete->setTextColor(1);
    ButtonView_delete->setText("删除闹钟");
    ButtonView_delete->setBoundaryBuffer(round_rect_112_26_r2_boundary);
    ButtonView_delete->setVisible(true);


    TextEditView_set_time = std::make_shared<TextEditView>(40, 27);
    TextEditView_set_time->setColor(0xFFFF);
    TextEditView_set_time->setTextColor(0);
    TextEditView_set_time->setText("00:00");
    TextEditView_set_time->setBoundaryBuffer(round_rect_40_27_r1_boundary);
    TextEditView_set_time->setVisible(true);


    CheckboxView_1 = std::make_shared<CheckboxView>(32, 29);
    CheckboxView_1->setColor(0x5906);
    CheckboxView_1->setTextColor(1);
    CheckboxView_1->setText("一");
    CheckboxView_1->setBoundaryBuffer(ellipse_32_29_boundary);
    CheckboxView_1->setVisible(true);

    ButtonView_set_back = std::make_shared<ButtonView>(48,24);
    ButtonView_set_back->setColor(0x3F03);
    ButtonView_set_back->setTextColor(0);
    ButtonView_set_back->setVisible(true);
    ButtonView_set_back->setImageBuffer((uint16_t*)&rgb16_back3_48_24);

    TextEditView_1770369232635 = std::make_shared<TextEditView>(72, 25);
    TextEditView_1770369232635->setColor(0x0000);
    TextEditView_1770369232635->setTextColor(1);
    TextEditView_1770369232635->setText("闹钟设置");
    TextEditView_1770369232635->setBoundaryBuffer(round_rect_72_25_r1_boundary);
    TextEditView_1770369232635->setVisible(true);

    FrameView_set_top = std::make_shared<FrameView>(272, 32);
    FrameView_set_top->setColor(0x0000);
    FrameView_set_top->setTextColor(0);
    FrameView_set_top->setBoundaryBuffer(round_rect_272_32_r3_boundary);
    FrameView_set_top->setVisible(true);

    ImgButtonView_set_switch = std::make_shared<ImgButtonView>(56, 24);
    ImgButtonView_set_switch->setColor(0xFFFF);
    ImgButtonView_set_switch->setTextColor(0);
    ImgButtonView_set_switch->setVisible(true);
    ImgButtonView_set_switch->setPressedImage((uint16_t*)&rgb16_switch_pressed_pressed_56_24);
    ImgButtonView_set_switch->setReleasedImage((uint16_t*)&rgb16_switch_released_56_24);
    ImgButtonView_set_switch->setSelfLocking(true);


    ListView_sethour = std::make_shared<ListView>(60, 79);
    ListView_sethour->setColor(0xFFFF);
    ListView_sethour->setTextColor(0);
    ListView_sethour->setVisible(true);
    for(char i=0;i<=23;i++)
    {
        char hour_str[3] = {0};
        snprintf(hour_str, sizeof(hour_str), "%02d", i);
        ListView_sethour->addItem(hour_str, i);
    }
    
    ListView_setmin = std::make_shared<ListView>(60, 79);
    ListView_setmin->setColor(0xFFFF);
    ListView_setmin->setTextColor(0);
    ListView_setmin->setVisible(true);
     for(char i=0;i<=59;i++)
    {
        char min_str[3] = {0};
        snprintf(min_str, sizeof(min_str), "%02d", i);
        ListView_setmin->addItem(min_str, i);
    }

    TextEditView_1770369580146 = std::make_shared<TextEditView>(72, 25);
    TextEditView_1770369580146->setColor(0xDFF7);
    TextEditView_1770369580146->setTextColor(0);
    TextEditView_1770369580146->setText("开启闹钟");
    TextEditView_1770369580146->setBoundaryBuffer(round_rect_72_25_r1_boundary);
    TextEditView_1770369580146->setVisible(true);

    FrameView_switch = std::make_shared<FrameView>(272, 26);
    FrameView_switch->setColor(0xDFF7);
    FrameView_switch->setTextColor(0);
    FrameView_switch->setBoundaryBuffer(round_rect_272_26_r3_boundary);
    FrameView_switch->setVisible(true);

    CheckboxView_2 = std::make_shared<CheckboxView>(32, 29);
    CheckboxView_2->setColor(0x5906);
    CheckboxView_2->setTextColor(1);
    CheckboxView_2->setText("二");
    CheckboxView_2->setBoundaryBuffer(ellipse_32_29_boundary);
    CheckboxView_2->setVisible(true);

    CheckboxView_3 = std::make_shared<CheckboxView>(32, 29);
    CheckboxView_3->setColor(0x5F05);
    CheckboxView_3->setTextColor(1);
    CheckboxView_3->setText("三");
    CheckboxView_3->setBoundaryBuffer(ellipse_32_29_boundary);
    CheckboxView_3->setVisible(true);

    CheckboxView_4 = std::make_shared<CheckboxView>(32, 29);
    CheckboxView_4->setColor(0x5906);
    CheckboxView_4->setTextColor(1);
    CheckboxView_4->setText("四");
    CheckboxView_4->setBoundaryBuffer(ellipse_32_29_boundary);
    CheckboxView_4->setVisible(true);

    CheckboxView_5 = std::make_shared<CheckboxView>(32, 29);
    CheckboxView_5->setColor(0x5906);
    CheckboxView_5->setTextColor(1);
    CheckboxView_5->setText("五");
    CheckboxView_5->setBoundaryBuffer(ellipse_32_29_boundary);
    CheckboxView_5->setVisible(true);

    CheckboxView_7 = std::make_shared<CheckboxView>(32, 29);
    CheckboxView_7->setColor(0x5906);
    CheckboxView_7->setTextColor(1);
    CheckboxView_7->setText("七");
    CheckboxView_7->setBoundaryBuffer(ellipse_32_29_boundary);
    CheckboxView_7->setVisible(true);

    CheckboxView_6 = std::make_shared<CheckboxView>(32, 29);
    CheckboxView_6->setColor(0xFF57);
    CheckboxView_6->setTextColor(1);
    CheckboxView_6->setText("六");
    CheckboxView_6->setBoundaryBuffer(ellipse_32_29_boundary);
    CheckboxView_6->setVisible(true);

    FrameView_set = std::make_shared<FrameView>(320, 240);
    FrameView_set->setColor(0xFFFF);
    FrameView_set->setTextColor(0);
    FrameView_set->setVisible(false);

    TextEditView_top = std::make_shared<TextEditView>(56, 25);
    TextEditView_top->setColor(0x0000);
    TextEditView_top->setTextColor(1);
    TextEditView_top->setText("闹钟");
    TextEditView_top->setBoundaryBuffer(round_rect_56_25_r1_boundary);
    TextEditView_top->setVisible(true);

    ButtonView_back = std::make_shared<ButtonView>(48,24);
    ButtonView_back->setColor(0xFFFF);
    ButtonView_back->setTextColor(0);
    ButtonView_back->setVisible(false);
    ButtonView_back->setImageBuffer((uint16_t*)&rgb16_back3_48_24);

    FrameView_top = std::make_shared<FrameView>(272, 34);
    FrameView_top->setColor(0x0000);
    FrameView_top->setTextColor(0);
    FrameView_top->setBoundaryBuffer(round_rect_272_34_r4_boundary);
    FrameView_top->setVisible(true);

    ListView_clock = std::make_shared<ListView>(272, 104);
    ListView_clock->setColor(0xFFFF);
    ListView_clock->setTextColor(0);
    ListView_clock->setBoundaryBuffer(round_rect_272_104_r1_boundary);
    ListView_clock->setVisible(true);

    ButtonView_add_clock = std::make_shared<ButtonView>(272, 40);
    ButtonView_add_clock->setColor(0xFBDE);
    ButtonView_add_clock->setTextColor(0);
    ButtonView_add_clock->setText("添加闹钟");
    ButtonView_add_clock->setBoundaryBuffer(round_rect_272_40_r2_boundary);
    ButtonView_add_clock->setVisible(true);

    FrameView_main = std::make_shared<FrameView>(320, 240);
    FrameView_main->setColor(0xFFFF);
    FrameView_main->setTextColor(0);
    FrameView_main->setVisible(true);

    Window_1770348934687 = std::make_shared<Window>(APP_WINDOW_START_X, APP_WINDOW_START_Y,320, 240);
    Window_1770348934687->setColor(0x8631);
    Window_1770348934687->setTextColor(0);
    Window_1770348934687->setVisible(true);

    // 建立控件父子关系
    FrameView_set->addView(ListView_setmin, 187.0, 80.0);
    FrameView_set->addView(ListView_sethour, 80.0, 80.0);
    FrameView_set->addView(CheckboxView_6, 224.0, 176);
    FrameView_set->addView(CheckboxView_7, 264.0, 176);
    FrameView_set->addView(CheckboxView_5, 184, 176);
    FrameView_set->addView(CheckboxView_4, 144.0, 176);
    FrameView_set->addView(CheckboxView_3, 104.0, 176);
    FrameView_set->addView(CheckboxView_2, 64.0, 176);
    FrameView_set->addView(FrameView_switch, 16, 55);
    FrameView_set->addView(FrameView_set_top, 24, 18);
    FrameView_set->addView(CheckboxView_1, 24.0, 176);
    FrameView_set->addView(TextEditView_set_time, 144, 114);
    FrameView_set->addView(ButtonView_delete, 104, 210.0);
    FrameView_set_top->addView(TextEditView_1770369232635, 110.0, 3.0);
    FrameView_set_top->addView(ButtonView_set_back, 8, 4);
    FrameView_switch->addView(TextEditView_1770369580146, 16.0, 2.0);
    FrameView_switch->addView(ImgButtonView_set_switch, 210, 0);
    Window_1770348934687->addView(FrameView_main, 0, 0);
    Window_1770348934687->addView(FrameView_set, 0, 0);
    FrameView_top->addView(ButtonView_back, 8, 5);
    FrameView_top->addView(TextEditView_top, 115, 5);
    FrameView_main->addView(ButtonView_add_clock, 24, 59);
    FrameView_main->addView(ListView_clock, 24, 106);
    FrameView_main->addView(FrameView_top, 24, 18);

    // 刷新窗口
    Window_1770348934687->flush(0, 0, APP_WINDOW_WIDTH, APP_WINDOW_HEIGHT);
}

static void window_exit(void)
{
    Window_1770348934687->setVisible(false);
    Window_1770348934687->removeAllViews();	
    FrameView_set_top->removeAllChilds();
    FrameView_switch->removeAllChilds();
    FrameView_set->removeAllChilds();
    FrameView_top->removeAllChilds();
    FrameView_main->removeAllChilds();

    ListView_sethour->clearItems();
    ListView_setmin->clearItems();
    ListView_clock->clearItems();

 
    ImgButtonView_set_switch.reset();
    ListView_sethour.reset();
    ListView_setmin.reset();
    ButtonView_delete.reset();
    TextEditView_set_time.reset();
    CheckboxView_1.reset();
    ButtonView_set_back.reset();
    TextEditView_1770369232635.reset();
    TextEditView_1770369580146.reset();
    CheckboxView_2.reset();
    CheckboxView_3.reset();
    CheckboxView_4.reset();
    CheckboxView_5.reset();
    CheckboxView_7.reset();
    CheckboxView_6.reset();
    TextEditView_top.reset();
    ButtonView_back.reset();
    ListView_clock.reset();
    ButtonView_add_clock.reset();
    FrameView_set_top.reset();
    FrameView_switch.reset();
    FrameView_set.reset();
    FrameView_top.reset();
    FrameView_main.reset();
    Window_1770348934687.reset();
}

static void window_suspend(void)
{
    Window_1770348934687->setVisible(false);
}

static void window_resume(void)
{
    Window_1770348934687->setVisible(true);
    Window_1770348934687->flush(0, 0, APP_WINDOW_WIDTH, APP_WINDOW_HEIGHT);
}

#endif //INCLUDE_MAIN_UI_H 

