/*This file is automatically generated by the tinyui tool and should not be modified.*/
#ifndef INCLUDE_MAIN_UI_H
#define INCLUDE_MAIN_UI_H
#include <memory>
#include <vector>

#include "goldie_display.h" 
// 控件头文件
#include "button_view.h"
#include "label_view.h"
#include "frame_view.h"
#include "window.h"

// 图片头文件
#include "rgb16_bowtie_56_53.h"
#include "rgb16_bow_56_53.h"
#include "rgb16_back2_48_48.h"
#include "rgb16_closeeye_r1_88_85.h"
#include "rgb16_closeeye_l_88_85.h"

// 掩码头文件
#include "round_rect_56_53_r1_boundary.h"
#include "ellipse_48_48_boundary.h"
#include "round_rect_88_85_r1_boundary.h"
#include "round_rect_88_85_r1_boundary.h"
#include "round_rect_240_16_r1_boundary.h"
// 全局控件变量定义
static std::shared_ptr<LabelView> LabelView_tie;
static std::shared_ptr<LabelView> LabelView_R;
static std::shared_ptr<FrameView> FrameView_R;
static std::shared_ptr<LabelView> LabelView_L;
static std::shared_ptr<FrameView> FrameView_L;
static std::shared_ptr<LabelView> LabelView_text;
static std::shared_ptr<Window> Window_1770202198007;

static void main_ui_init()
{
    LabelView_tie = std::make_shared<LabelView>(56, 53);
    LabelView_tie->setColor(0xFFFF);
    LabelView_tie->setTextColor(0);
    LabelView_tie->setBoundaryBuffer(round_rect_56_53_r1_boundary);
    LabelView_tie->setVisible(true);
    LabelView_tie->setImageBuffer((uint16_t*)&rgb16_bowtie_56_53);

    LabelView_R = std::make_shared<LabelView>(88, 85);
    LabelView_R->setColor(0xFFFF);
    LabelView_R->setTextColor(0);
    LabelView_R->setBoundaryBuffer(round_rect_88_85_r1_boundary);
    LabelView_R->setVisible(true);
    LabelView_R->setImageBuffer((uint16_t*)&rgb16_closeeye_r1_88_85);

    FrameView_R = std::make_shared<FrameView>(160, 240);
    FrameView_R->setColor(0x0000);
    FrameView_R->setTextColor(0);
    FrameView_R->setVisible(true);

    LabelView_L = std::make_shared<LabelView>(88, 85);
    LabelView_L->setColor(0xFFFF);
    LabelView_L->setTextColor(0);
    LabelView_L->setBoundaryBuffer(round_rect_88_85_r1_boundary);
    LabelView_L->setVisible(true);
    LabelView_L->setImageBuffer((uint16_t*)&rgb16_closeeye_l_88_85);

    FrameView_L = std::make_shared<FrameView>(160, 240);
    FrameView_L->setColor(0x0000);
    FrameView_L->setTextColor(0);
    FrameView_L->setVisible(true);

    LabelView_text = std::make_shared<LabelView>(240, 16);
    LabelView_text->setColor(0x0000);
    LabelView_text->setTextColor(0);
    LabelView_text->setText("正在思考....");
    LabelView_text->setBoundaryBuffer(round_rect_240_16_r1_boundary);
    LabelView_text->setVisible(true);

    Window_1770202198007 = std::make_shared<Window>(APP_WINDOW_START_X, APP_WINDOW_START_Y,320, 240);
    Window_1770202198007->setColor(0x0000);
    Window_1770202198007->setTextColor(0);
    

    // 建立控件父子关系
    Window_1770202198007->addView(LabelView_text, 40, 155);
    Window_1770202198007->addView(FrameView_L, 0, 0);
    Window_1770202198007->addView(FrameView_R, 160, 0);
    Window_1770202198007->addView(LabelView_tie, 140, 155);
    FrameView_R->addView(LabelView_R, 8, 67);
    FrameView_L->addView(LabelView_L, 72, 66);

     Window_1770202198007->setVisible(true);
    // 刷新窗口
    Window_1770202198007->flush(0, 0, APP_WINDOW_WIDTH, APP_WINDOW_HEIGHT);

}

static void window_exit(void)
{
    Window_1770202198007->setVisible(false);
    Window_1770202198007->removeAllViews();
    FrameView_R->removeAllChilds();
    FrameView_L->removeAllChilds();

    LabelView_R.reset();
    LabelView_L.reset();
    LabelView_text.reset();
    
    FrameView_R.reset();
    FrameView_L.reset();
    Window_1770202198007.reset();
}

static void window_suspend(void)
{
    Window_1770202198007->setVisible(false);
}

static void window_resume(void)
{
    Window_1770202198007->setVisible(true);
    Window_1770202198007->flush(0, 0, APP_WINDOW_WIDTH, APP_WINDOW_HEIGHT);
}

#endif //INCLUDE_MAIN_UI_H 

